export type HistoricalCreedBodyContent = {
  bodyZh: string[];
  bodyZhTw: string[];
  bodyEn: string[];
};

/** Small creed bodies kept in the main bundle; long texts load on demand. */
export const INLINE_HISTORICAL_CREED_BODIES: Record<string, HistoricalCreedBodyContent> = {
  "apostles-creed": {
    bodyZh: [
      "我信上帝，全能的父，创造天地的主。",
      "我信我主耶稣基督，上帝的独生子；因圣灵感孕，从童贞女马利亚所生；在本丢·彼拉多手下受难，被钉在十字架上，死了，而且埋葬了；下到阴间；第三天从死里复活；升天，坐在全能父上帝的右边；",
      "我信圣灵；我信圣而公之教会；圣徒相通；罪得赦免；身体复活；永生。阿们。",
    ],
    bodyZhTw: [
      "我信上帝，全能的父，創造天地的主。",
      "我信我主耶穌基督，上帝的獨生子；因聖靈感孕，從童貞女馬利亞所生；在本丟·彼拉多手下受難，被釘在十字架上，死了，而且埋葬了；下到陰間；第三天從死裡復活；升天，坐在全能父上帝的右邊；",
      "我信聖靈；我信聖而公之教會；聖徒相通；罪得赦免；身體復活；永生。阿們。",
    ],
    bodyEn: [
      "I believe in God, the Father almighty, creator of heaven and earth.",
      "I believe in Jesus Christ, his only Son, our Lord, who was conceived by the Holy Spirit, born of the Virgin Mary, suffered under Pontius Pilate, was crucified, died, and was buried; he descended to the dead; on the third day he rose again; he ascended into heaven, and is seated at the right hand of the Father;",
      "I believe in the Holy Spirit, the holy catholic church, the communion of saints, the forgiveness of sins, the resurrection of the body, and the life everlasting. Amen.",
    ],
  },
  "nicene-creed": {
    bodyZh: [
      "我信独一上帝，全能的父，创造天地万物，以及一切可见与不可见之物的主。",
      "我信独一主耶稣基督，上帝独生的子，为父所生，先说一切受造之物之前，由上帝所生，真神出自真神，诸光之光，自光而出之真神，与父同质，万物藉祂而造。",
      "祂为拯救我们世人，从天降下，因圣灵由童贞女马利亚取人身成为人；在本丢·彼拉多手下为我们钉十字架，受难，埋葬；第三天照圣经的话复活；升天，坐在父的右边；将来必从那里降临，审判活人死人。",
      "我信圣灵，是主、是赐生命者，从父和子出来，与父、子同受敬拜，同受尊荣；祂曾藉众先知说话。",
      "我信独一、神圣、大公、使徒的教会。我认一个洗礼，使罪得赦。我指望死人复活，并指望来世的生命。阿们。",
    ],
    bodyZhTw: [
      "我信獨一上帝，全能的父，創造天地萬物，以及一切可見與不可見之物的主。",
      "我信獨一主耶穌基督，上帝獨生的子，為父所生，先於一切受造之物之前，由上帝所生，真神出自真神，諸光之光，自光而出之真神，與父同質，萬物藉祂而造。",
      "祂為拯救我們世人，從天降下，因聖靈由童貞女馬利亞取人身成為人；在本丟·彼拉多手下為我們釘十字架，受難，埋葬；第三天照聖經的話復活；升天，坐在父的右邊；將來必從那裡降臨，審判活人死人。",
      "我信聖靈，是主、是賜生命者，從父和子出來，與父、子同受敬拜，同受尊榮；祂曾藉眾先知說話。",
      "我信獨一、神聖、大公、使徒的教會。我認一個洗禮，使罪得赦。我指望死人復活，並指望來世的生命。阿們。",
    ],
    bodyEn: [
      "We believe in one God, the Father, the Almighty, maker of heaven and earth, of all that is, seen and unseen.",
      "We believe in one Lord, Jesus Christ, the only Son of God, eternally begotten of the Father, God from God, Light from Light, true God from true God, begotten, not made, of one Being with the Father; through him all things were made.",
      "For us and for our salvation he came down from heaven, was incarnate of the Holy Spirit and the Virgin Mary and became truly human. For our sake he was crucified under Pontius Pilate; he suffered death and was buried. On the third day he rose again in accordance with the Scriptures; he ascended into heaven and is seated at the right hand of the Father. He will come again in glory to judge the living and the dead.",
      "We believe in the Holy Spirit, the Lord, the giver of life, who proceeds from the Father and the Son, who with the Father and the Son is worshiped and glorified, who has spoken through the prophets.",
      "We believe in one holy catholic and apostolic Church. We acknowledge one baptism for the forgiveness of sins. We look for the resurrection of the dead, and the life of the world to come. Amen.",
    ],
  },
  "chalcedonian-definition": {
    bodyZh: [
      "我们照圣洁教父的教导，一致定信我们的主耶稣基督是真神，也是真人；",
      "就祂的神性而言，与父同质；就祂的人性而言，与我们有同一血肉之躯；",
      "在一切事上与我们有相同，只是没有罪；",
      "就祂的神性而言，在万世之前由父而生；就祂的人性而言，在这末世为着我们和我们的救恩，由童贞女马利亚——按祂的神性她是上帝之母，按祂的人性她是人之母——所生；",
      "这一个位格的基督、圣子、主、独生子，我们必须认祂有两种本性：神性、人性；",
      "这二性不相混，不相换，不相分，不相离；",
      "神性的特质归于神性，人性的特质归于人性，各保持完全，合于一个位格、一个基督里；",
      "不是分成两个位格，而是同一位、独一的子、基督、主、独生子；",
      "正如先知从起初所宣告的，主耶稣基督向我们显明，教父的信仰信经传给我们，普世教会现在仍如此认信。",
    ],
    bodyZhTw: [
      "我們照聖潔教父的教導，一致定信我們的主耶穌基督是真神，也是真人；",
      "就祂的神性而言，與父同質；就祂的人性而言，與我們有同一血肉之軀；",
      "在一切事上與我們有相同，只是沒有罪；",
      "就祂的神性而言，在萬世之前由父而生；就祂的人性而言，在這末世為著我們和我們的救恩，由童貞女馬利亞——按祂的神性她是上帝之母，按祂的人性她是人之母——所生；",
      "這一個位格的基督、聖子、主、獨生子，我們必須認祂有兩種本性：神性、人性；",
      "這二性不相混，不相換，不相分，不相離；",
      "神性的特質歸於神性，人性的特質歸於人性，各保持完全，合於一個位格、一個基督裡；",
      "不是分成兩個位格，而是同一位、獨一的子、基督、主、獨生子；",
      "正如先知從起初所宣告的，主耶穌基督向我們顯明，教父的信仰信經傳給我們，普世教會現在仍如此認信。",
    ],
    bodyEn: [
      "Following the holy fathers, we unanimously teach one and the same Son, our Lord Jesus Christ: the same perfect in divinity and perfect in humanity, the same truly God and truly man.",
      "Consubstantial with the Father as regards his divinity, and the same consubstantial with us as regards his humanity; like us in all things except sin;",
      "Begotten before the ages from the Father as regards his divinity, and in the last days the same, for us and for our salvation, born of Mary the virgin God-bearer as regards his humanity;",
      "One and the same Christ, Son, Lord, only-begotten, acknowledged in two natures which undergo no confusion, no change, no division, no separation;",
      "The distinction between natures being in no way annulled by the union, but rather the characteristics of each nature being preserved and coming together to form one person and subsistence, one Christ, not parted or divided into two persons, but one and the same Son and only-begotten God the Word, Lord Jesus Christ.",
    ],
  },
  "athanasian-creed": {
    bodyZh: [
      "凡要得救，必先持守大公信仰。",
      "此信仰若不全，人就不能无瑕疵地持守，必永远灭亡。",
      "大公信仰乃是：我们敬拜一位神于三位，又敬拜三位于一位，不可混乱三位，亦不可分离三位。",
      "因为父是一位，子是一位，圣灵也是一位。",
      "然而父、子、圣灵不是三位神，只是一位神。",
      "父非受造，子非受造，圣灵亦非受造。",
      "父非受生，子乃受生，圣灵亦非受生，乃由父与子而出。",
      "父是神，子是神，圣灵也是神；然而不是三位神，只是一位神。",
      "父是主，子是主，圣灵也是主；然而不是三位主，只是一位主。",
      "正如我们被主救恩的真理所迫，必须认基督是真神又是真人；",
      "祂的神性不是后于、次于父的神性，乃与父同质；",
      "祂的人性也不少于我们的人性，乃与我们同质，只是没有罪。",
      "我们的主拿撒勒人耶稣，按神性说，是上帝的儿子；按人性说，是马利亚的儿子；",
      "祂是完全的神，又是完全的人，有理性灵魂，有人性身体；",
      "按神性与父同质，按人性与我们有同一血肉之躯；",
      "祂为救我们而受苦，下到阴间，第三日从死复活，升天，坐在父的右边；",
      "将来要从那里来，审判活人死人；",
      "祂降临的时候，众人都要身体复活，把所行的事陈述出来；",
      "行善的进入永生，行恶的进入永火。",
      "这是大公信仰；人若不全心全意信这信仰，就不能得救。",
    ],
    bodyZhTw: [
      "凡要得救，必先持守大公信仰。",
      "此信仰若不全，人就不能無瑕疵地持守，必永遠滅亡。",
      "大公信仰乃是：我們敬拜一位神於三位，又敬拜三位於一位，不可混亂三位，亦不可分離三位。",
      "因為父是一位，子是一位，聖靈也是一位。",
      "然而父、子、聖靈不是三位神，只是一位神。",
      "父非受造，子非受造，聖靈亦非受造。",
      "父非受生，子乃受生，聖靈亦非受生，乃由父與子而出。",
      "父是神，子是神，聖靈也是神；然而不是三位神，只是一位神。",
      "父是主，子是主，聖靈也是主；然而不是三位主，只是一位主。",
      "正如我們被主救恩的真理所迫，必須認基督是真神又是真人；",
      "祂的神性不是後於、次於父的神性，乃與父同質；",
      "祂的人性也不少於我們的人性，乃與我們同質，只是沒有罪。",
      "我們的主拿撒勒人耶穌，按神性說，是上帝的兒子；按人性說，是馬利亞的兒子；",
      "祂是完全的神，又是完全的人，有理性靈魂，有人性身體；",
      "按神性與父同質，按人性與我們有同一血肉之軀；",
      "祂為救我們而受苦，下到陰間，第三日從死復活，升天，坐在父的右邊；",
      "將來要從那裡來，審判活人死人；",
      "祂降臨的時候，眾人都要身體復活，把所行的事陳述出來；",
      "行善的進入永生，行惡的進入永火。",
      "這是大公信仰；人若不全心全意信這信仰，就不能得救。",
    ],
    bodyEn: [
      "Whoever desires to be saved should above all hold to the catholic faith.",
      "Anyone who does not keep it whole and unbroken will doubtless perish eternally.",
      "Now the catholic faith is this: that we worship one God in Trinity, and Trinity in Unity, neither confusing the persons nor dividing the substance.",
      "For there is one person of the Father, another of the Son, and another of the Holy Spirit.",
      "But the Godhead of the Father, of the Son, and of the Holy Spirit is all one, the glory equal, the majesty coeternal.",
      "Such as the Father is, such is the Son, and such is the Holy Spirit.",
      "The Father uncreated, the Son uncreated, and the Holy Spirit uncreated.",
      "The Father incomprehensible, the Son incomprehensible, and the Holy Spirit incomprehensible.",
      "And yet there are not three eternal beings, but one eternal being.",
      "So likewise the Father is almighty, the Son almighty, and the Holy Spirit almighty; and yet there are not three almighty beings, but one almighty being.",
      "So the Father is God, the Son is God, and the Holy Spirit is God; and yet there are not three Gods, but one God.",
      "Our Lord Jesus Christ, the Son of God, is God and man: perfect God and perfect man, of a rational soul and human flesh subsisting;",
      "Equal to the Father as regards his Godhead, and inferior to the Father as regards his manhood;",
      "Who, although he is God and man, yet he is not two, but one Christ.",
      "One, not by conversion of the Godhead into flesh, but by taking of the manhood into God.",
      "One altogether, not by confusion of substance, but by unity of person.",
      "For as the rational soul and flesh is one man, so God and man is one Christ.",
      "Who suffered for our salvation, descended into hell, rose again the third day from the dead.",
      "He ascended into heaven, and sits at the right hand of God the Father almighty; from there he shall come to judge the living and the dead.",
      "At his coming all people will rise again with their bodies and give an account of their own deeds.",
      "Those who have done good will enter eternal life, and those who have done evil will enter eternal fire.",
      "This is the catholic faith; one cannot be saved without believing this firmly and faithfully.",
    ],
  },
};

/** @deprecated Use historicalCreedHasBody / resolveHistoricalCreedBodyParagraphs instead. */
export const HISTORICAL_CREED_BODIES = INLINE_HISTORICAL_CREED_BODIES;
