// 由 tools/gen-reading-plans.mjs 从 data/bible-reading-plans/registry.json + zh-CN.json + mobile-brief.zh-CN.json 生成，勿手改。

/// 计划目录一条。title/subtitle/blurb 是 zh-CN 文案（pages.read.plansCatalog.*），name 是英文表名。
struct ReadingPlanEntry: Identifiable, Hashable {
    let planId: String
    let name: String
    let description: String
    let title: String
    let subtitle: String
    let blurb: String
    let dayCount: Int
    let maxReadingsPerDay: Int
    let listPriority: Int
    /// 手机版精简文案（mobile-brief.zh-CN.json）：徽标 / 一句话 / 要点 chips / 怎么读 / 长版说明
    let badge: String
    let tagline: String
    let facts: [PlanFact]
    let how: [PlanFact]
    let detail: String
    var id: String { planId }
}

/// 图标名 + 短句（图标名 → Material 字形见 PlanIcons）
struct PlanFact: Hashable {
    let icon: String
    let text: String
}

enum ReadingPlanCatalog {
    static let tripleLoopId = "triple-loop"
    static let ntDeepRepeatId = "nt-deep-repeat"
    /// 已按 listPriority / planId 排好（RN sortPlans）
    static let plans: [ReadingPlanEntry] = [
        ReadingPlanEntry(planId: "triple-loop", name: "轻松循环读经计划", description: "旧约、新约、智慧书三条独立循环；不按日历补读。", title: "轻松循环读经计划", subtitle: "AskBible 方法一 · 无压力通读", blurb: "旧约、新约、智慧书三条独立循环，每日各一小段；不补读、不展示落后。适合第一次建立习惯，或希望低压、可持续回到神话语的人。", dayCount: 1, maxReadingsPerDay: 3, listPriority: -20,
            badge: "方法一 · 轻松读经", tagline: "旧约、新约、智慧书，每天各读一小段",
            facts: [PlanFact(icon: "today", text: "每日 3 段"), PlanFact(icon: "loop", text: "随时跟上"), PlanFact(icon: "swap", text: "三条进度各走各的")],
            how: [PlanFact(icon: "sync", text: "读哪条就推哪条，三条互不绑定"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读"), PlanFact(icon: "replay", text: "读完一环末章，回到该环起点")],
            detail: "适合第一次建立习惯，或希望低压、可持续地回到神话语的人。三轨默认每日各进一章，你可随时在章节页推进，也可以恢复默认进度。"),
        ReadingPlanEntry(planId: "nt-deep-repeat", name: "新约深读 · 旧约通读", description: "AskBible 方法二 · 有效深读：参考麦克阿瑟研经法，52 阶，7 / 14 / 28 天深度。", title: "正式研经", subtitle: "AskBible 方法二 · 有效深读", blurb: "参考麦克阿瑟新约研读法，我们整理为 52 阶（4–6 章/阶）。从每阶 7 天起，可选 14 / 28 天深度；约 12 个月 / 2 年 / 4 年一轮，旧约每日一章并行。若刚开始，建议先用方法一。", dayCount: 1, maxReadingsPerDay: 2, listPriority: -15,
            badge: "方法二 · 正式研读", tagline: "同一段新约反复读，直到读进心里",
            facts: [PlanFact(icon: "stairs", text: "新约 52 阶"), PlanFact(icon: "repeat", text: "每阶 7 / 14 / 28 天"), PlanFact(icon: "book", text: "旧约每日 1 章")],
            how: [PlanFact(icon: "stairs", text: "新约分 52 阶，每阶 4–6 章"), PlanFact(icon: "repeat", text: "同一阶连读 7、14 或 28 天"), PlanFact(icon: "book", text: "旧约每天 1 章并行通读")],
            detail: "参考约翰·麦克阿瑟的新约研读法。「读 N 遍」= 每阶连读 N 天；走完 52 阶为一轮，约 12 个月 / 2 年 / 4 年。停了再回来，别担心漏读；若刚开始读经，建议先用方法一。"),
        ReadingPlanEntry(planId: "esvthroughthebible", name: "Through The Bible", description: "Through the Biblewww.esv.org", title: "按书卷顺序通读圣经", subtitle: "Through The Bible", blurb: "每日旧约、新约各一段（多为两截经文），一年通读；列表里与「旧约新约并进」类计划只保留这一种较轻的节奏。", dayCount: 365, maxReadingsPerDay: 2, listPriority: 0,
            badge: "经典日课表", tagline: "每日旧约、新约各一段（多为两截经文），一年通读",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 2 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "每日旧约、新约各一段（多为两截经文），一年通读；列表里与「旧约新约并进」类计划只保留这一种较轻的节奏。"),
        ReadingPlanEntry(planId: "backtothebiblechronological", name: "Back to the Bible Chronological", description: "Copyright Back to the Bible www.backtothebible.org", title: "按历史时间线读通圣经", subtitle: "Back to the Bible Chronological", blurb: "按历史线索重排经文顺序的一年通读，常穿插约伯记等段落。适合想从「故事时间线」进入整本圣经的人。表内版权信息以英文标注为准。", dayCount: 365, maxReadingsPerDay: 6, listPriority: 1,
            badge: "经典日课表", tagline: "按历史线索重排经文顺序的一年通读，常穿插约伯记等段落",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 6 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "按历史线索重排经文顺序的一年通读，常穿插约伯记等段落。适合想从「故事时间线」进入整本圣经的人。表内版权信息以英文标注为准。"),
        ReadingPlanEntry(planId: "esvgospelsandepistles", name: "Gospel and Epistles", description: "Gospel and Epistleswww.esv.org", title: "福音与书信", subtitle: "Gospel and Epistles", blurb: "聚焦新约福音与书信脉络的一年轨道，可与旧约通读计划搭配使用。", dayCount: 365, maxReadingsPerDay: 1, listPriority: 2,
            badge: "经典日课表", tagline: "聚焦新约福音与书信脉络的一年轨道，可与旧约通读计划搭配使用",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 1 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "聚焦新约福音与书信脉络的一年轨道，可与旧约通读计划搭配使用。"),
        ReadingPlanEntry(planId: "esvchroniclesandprophets", name: "Chronicles and Prophets", description: "Chronicles and Prophetswww.esv.org", title: "历代志与先知书", subtitle: "Chronicles and Prophets", blurb: "以历代志与先知书等书卷为主线编排的读经轨道，偏历史与神论脉络。名称中的 ESV 为来源资料标签。", dayCount: 365, maxReadingsPerDay: 1, listPriority: 100,
            badge: "经典日课表", tagline: "以历代志与先知书等书卷为主线编排的读经轨道，偏历史与神论脉络",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 1 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "以历代志与先知书等书卷为主线编排的读经轨道，偏历史与神论脉络。名称中的 ESV 为来源资料标签。"),
        ReadingPlanEntry(planId: "esveverydayinword", name: "Every Day In the Word", description: "Every Day in the Wordwww.esv.org", title: "每日读经（叙事分块）", subtitle: "Every Day In the Word", blurb: "每日多段经文，常按叙事大块划分（含跨章经节）。适合愿意跟随编辑划分细读的人；英文经题有助于对照原表。", dayCount: 365, maxReadingsPerDay: 5, listPriority: 100,
            badge: "经典日课表", tagline: "每日多段经文，常按叙事大块划分（含跨章经节）",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 5 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "每日多段经文，常按叙事大块划分（含跨章经节）。适合愿意跟随编辑划分细读的人；英文经题有助于对照原表。"),
        ReadingPlanEntry(planId: "esvliterarystudybible", name: "ESV Literary Study Bible Plan", description: "ESV Literary Study Biblewww.esv.org", title: "文学研读圣经计划", subtitle: "ESV Literary Study Bible Plan", blurb: "按「文学研读」思路拆分的日课，常一日多段。名称含 ESV 为来源标签；正文仍以你在站内选择的译本为准。", dayCount: 365, maxReadingsPerDay: 4, listPriority: 100,
            badge: "经典日课表", tagline: "按「文学研读」思路拆分的日课，常一日多段",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 4 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "按「文学研读」思路拆分的日课，常一日多段。名称含 ESV 为来源标签；正文仍以你在站内选择的译本为准。"),
        ReadingPlanEntry(planId: "esvpentateuchandhistoryofisrael", name: "Pentateuch and History of Israel", description: "Pentateuch and History of Israelwww.esv.org", title: "五经与以色列历史", subtitle: "Pentateuch and History of Israel", blurb: "自摩西五经延伸至列国与王朝叙事，适合想从立约与历史骨架读起的人。", dayCount: 365, maxReadingsPerDay: 1, listPriority: 100,
            badge: "经典日课表", tagline: "自摩西五经延伸至列国与王朝叙事，适合想从立约与历史骨架读起的人",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 1 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "自摩西五经延伸至列国与王朝叙事，适合想从立约与历史骨架读起的人。"),
        ReadingPlanEntry(planId: "esvpsalmsandwisdomliterature", name: "Psalms and Wisdom Literature", description: "Psalm and Wisdom Literaturewww.esv.org", title: "诗篇与智慧文学", subtitle: "Psalms and Wisdom Literature", blurb: "以诗篇、箴言、传道书等智慧传统为主的轨道，可与叙事类计划互补。", dayCount: 365, maxReadingsPerDay: 1, listPriority: 100,
            badge: "经典日课表", tagline: "以诗篇、箴言、传道书等智慧传统为主的轨道，可与叙事类计划互补",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 1 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "以诗篇、箴言、传道书等智慧传统为主的轨道，可与叙事类计划互补。"),
        ReadingPlanEntry(planId: "mcheyne", name: "M'Cheyne", description: "M'Cheyne Reading Plan", title: "麦琴读经表", subtitle: "M'Cheyne Reading Plan", blurb: "每日四章并行，约一年内通读旧约一遍，新约与诗篇各约两遍。节奏较密，适合能稳定安排读经时间的人。副题与经题保留英文，便于查对常见版本。", dayCount: 365, maxReadingsPerDay: 4, listPriority: 100,
            badge: "经典日课表", tagline: "每日四章并行，约一年内通读旧约一遍，新约与诗篇各约两遍",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 4 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "每日四章并行，约一年内通读旧约一遍，新约与诗篇各约两遍。节奏较密，适合能稳定安排读经时间的人。副题与经题保留英文，便于查对常见版本。"),
        ReadingPlanEntry(planId: "oneyearchronological", name: "One Year Chronological", description: "One Year Chronologicalwww.oneyearbibleonline.com", title: "一年编年通读（多段并行）", subtitle: "One Year Chronological", blurb: "按编年思路编排；部分日期会并列多段经文以贴近历史平行叙事。单日阅读量可能较多，可按自己的节奏延展完成。", dayCount: 365, maxReadingsPerDay: 15, listPriority: 100,
            badge: "经典日课表", tagline: "按编年思路编排",
            facts: [PlanFact(icon: "calendar", text: "365 天"), PlanFact(icon: "today", text: "每日 ≤ 15 段")],
            how: [PlanFact(icon: "calendar", text: "按日课表逐日读，一年读完"), PlanFact(icon: "today", text: "从今天起算，或对齐今年 1 月 1 日"), PlanFact(icon: "spa", text: "停了再回来，别担心漏读")],
            detail: "按编年思路编排；部分日期会并列多段经文以贴近历史平行叙事。单日阅读量可能较多，可按自己的节奏延展完成。"),
    ]
    static func plan(id: String) -> ReadingPlanEntry? { plans.first { $0.planId == id } }
    /// 目录页分组：主推（三循环、新约深读，按此序）与其它
    static var featured: [ReadingPlanEntry] { [tripleLoopId, ntDeepRepeatId].compactMap(plan(id:)) }
    static var others: [ReadingPlanEntry] { plans.filter { $0.planId != tripleLoopId && $0.planId != ntDeepRepeatId } }
    static func isPointerPlan(_ id: String) -> Bool { id == tripleLoopId || id == ntDeepRepeatId }
}

/// 读经计划相关文案（zh-CN.json 的 pages.read.*）。`f` 做 {{name}} 占位替换。
enum PlanCopy {
    static let strings: [String: String] = [
        "pages.read.ntDeepRepeatActivateHint": "设为当前计划后，今天为第 1 天，从第 1 阶《约翰一书》与创世纪第 1 章开始；先选深读节奏（三选一），再点「使用此计划」。",
        "pages.read.ntDeepRepeatAdvanceButtonNt": "本节已读，推进{{track}}",
        "pages.read.ntDeepRepeatAdvanceHintNt": "若已读完本节，可推进「{{track}}」的下一段（本阶共 {{days}} 天，读满再换段）；旧约通读不会变。",
        "pages.read.ntDeepRepeatLabelSep": " · ",
        "pages.read.ntDeepRepeatLadderLead": "共 {{stages}} 阶，每阶连读 {{days}} 天；约 {{cycle}} 天走完一轮。",
        "pages.read.ntDeepRepeatLadderTitle": "新约 52 版块",
        "pages.read.ntDeepRepeatLighterPathLead": "若你刚开始读经，或希望无压力通读，可先用方法一「三循环」建立节奏，再进阶方法二。",
        "pages.read.ntDeepRepeatLighterPathLink": "试试无压力通读（方法一）",
        "pages.read.ntDeepRepeatLighterPathTitle": "更适合方法一？",
        "pages.read.ntDeepRepeatPace14Summary": "二年轻松读14遍新约圣经",
        "pages.read.ntDeepRepeatPace14Title": "14 天 · 两周",
        "pages.read.ntDeepRepeatPace28Summary": "四年轻松读28遍新约圣经",
        "pages.read.ntDeepRepeatPace28Title": "28 天 · 四周",
        "pages.read.ntDeepRepeatPace7Summary": "一年轻松读7遍新约圣经",
        "pages.read.ntDeepRepeatPace7Title": "7 天 · 一周",
        "pages.read.ntDeepRepeatPaceContinuousNote": "从启用当天开始连续读 {{days}} 天；第 {{nextDay}} 天进入下一段，之后每段都按相同天数推进。",
        "pages.read.ntDeepRepeatPaceFirstSegmentNote": "若今日开始：首段 {{days}} 天，至 {{endDate}} 结束。",
        "pages.read.ntDeepRepeatPaceIntro": "同一段新约反复读，直到熟悉；旧约每天 1 章陪着读。参考麦克阿瑟研经法，从 7 天/段起步。",
        "pages.read.ntDeepRepeatPaceOneCycle": "{{duration}}",
        "pages.read.ntDeepRepeatPaceOtNote": "同期旧约每日一章通读；约 {{years}} 年可通读一遍旧约（与新约并行）",
        "pages.read.ntDeepRepeatPacePass14": "14 遍（每阶 14 天）",
        "pages.read.ntDeepRepeatPacePass28": "28 遍（每阶 28 天）",
        "pages.read.ntDeepRepeatPacePass7": "7 遍（每阶 7 天）",
        "pages.read.ntDeepRepeatPaceTimelineDuration": "大约",
        "pages.read.ntDeepRepeatPaceTimelineHeader": "三种深度，大约需要多久",
        "pages.read.ntDeepRepeatPaceTimelinePass": "深度",
        "pages.read.ntDeepRepeatPaceTitle": "选一种深度（三选一）",
        "pages.read.ntDeepRepeatPlansMeta": "旧约通读 · 新约 52 阶 · 7 / 14 / 28 天节奏",
        "pages.read.ntDeepRepeatPrinciple1": "方法二 · 有效深读：新约 52 阶（每阶通常 4–6 章），参考麦克阿瑟「同段反复读进心里」；「N 遍」= 每阶连读 N 天；旧约每日一章通读。",
        "pages.read.ntDeepRepeatPrinciple2": "不按中断补读，不展示「落后」；停了再回来即可。",
        "pages.read.ntDeepRepeatPrinciple3": "从 7 天/阶起步，可选 14 / 28 天加深；走完 52 阶为一轮，约 12 个月 / 2 年 / 4 年。",
        "pages.read.ntDeepRepeatPrinciplesTitle": "AskBible 深读方法",
        "pages.read.ntDeepRepeatSegmentLabel": "第 {{day}}/{{total}} 天 · {{segment}}",
        "pages.read.ntDeepRepeatSegmentRange": "第 {{start}}–{{end}} 章",
        "pages.read.ntDeepRepeatSegmentSingleChapter": "第 {{chapter}} 章",
        "pages.read.ntDeepRepeatSetStageAsTodayBody": "将第 {{n}} 阶「{{range}}」设为今日新约读经？",
        "pages.read.ntDeepRepeatSetStageAsTodayCancel": "取消",
        "pages.read.ntDeepRepeatSetStageAsTodayConfirm": "设为今日",
        "pages.read.ntDeepRepeatSetStageAsTodayTitle": "设为今日读经",
        "pages.read.ntDeepRepeatStageBookRange": "{{name}} 第 {{start}}–{{end}} 章",
        "pages.read.ntDeepRepeatStageBookSingle": "{{name}} 第 {{chapter}} 章",
        "pages.read.ntDeepRepeatStageCurrent": "进行中 · 第 {{day}}/{{total}} 天",
        "pages.read.ntDeepRepeatStageDone": "已完成本阶",
        "pages.read.ntDeepRepeatStageLabel": "第 {{n}} 阶",
        "pages.read.ntDeepRepeatStagesBelowHint": "点选某一阶，可设为今日新约读经。",
        "pages.read.ntDeepRepeatStartNote": "自选定计划日起计；今日为",
        "pages.read.ntDeepRepeatTodaySummary": "先读新约当前阶，再读旧约一章；两条进度互不影响。",
        "pages.read.ntDeepRepeatTodayTitle": "今日读经",
        "pages.read.ntDeepRepeatTrackNt": "新约深读",
        "pages.read.ntDeepRepeatTrackOt": "旧约通读",
        "pages.read.ntDeepRepeatWhyArticleLink": "麦克阿瑟研经法原文与说明",
        "pages.read.planActivateClear": "取消当前计划",
        "pages.read.planActivateCurrentDay": "今日为第 {{n}} 天",
        "pages.read.planActivateHeading": "使用此计划",
        "pages.read.planActivateUpdate": "更新起始方式",
        "pages.read.planActivateUse": "设为当前计划",
        "pages.read.planAnchorFromToday": "从今天开始",
        "pages.read.planAnchorFromTodayHint": "选定的这一天为第 1 天；之后按自然日推进。",
        "pages.read.planAnchorJan1": "对齐当年 1 月 1 日",
        "pages.read.planAnchorJan1Hint": "今天对应该年 1 月 1 日起算的第几天（例如年中开始会落在表中较后位置）。",
        "pages.read.planDetailBackPlans": "全部计划",
        "pages.read.planDetailDay": "第 {{n}} 天",
        "pages.read.planDetailHint": "链接进入该段的起始章；经节范围为表内参考。",
        "pages.read.planDetailTodayMark": "（今日）",
        "pages.read.planPlayCalendarMonth": "{{y}}年{{m}}月",
        "pages.read.planPlayCalendarNextMonth": "下个月",
        "pages.read.planPlayCalendarPrevMonth": "上个月",
        "pages.read.planPlayConfirmDay": "进度设置为今日",
        "pages.read.planPlayHeaderTitle": "{{name}}",
        "pages.read.planPlayLead": "连续播放今日读经计划。",
        "pages.read.planPlayListenTotalLabel": "累计听 {{duration}}",
        "pages.read.planPlayNextChapter": "下一读经章",
        "pages.read.planPlayNextDay": "明天",
        "pages.read.planPlayNowPlaying": "正在朗读：{{title}}",
        "pages.read.planPlayPlanDayLabel": "计划已进行第 {{n}} 天",
        "pages.read.planPlayPlay": "播放今日读经",
        "pages.read.planPlayPlayChapterAudio": "声音",
        "pages.read.planPlayPoolHeading": "今日播放",
        "pages.read.planPlayPrevChapter": "上一读经章",
        "pages.read.planPlayPrevDay": "昨天",
        "pages.read.planPlayReadChapter": "阅读",
        "pages.read.planPlayRepeatChapter": "单章循环",
        "pages.read.planPlayRepeatOff": "循环关闭",
        "pages.read.planPlayRepeatPool": "播放列表循环",
        "pages.read.planPlayTitle": "读经计划",
        "pages.read.planPlayTrackMeta": "{{current}} / {{total}}",
        "pages.read.plansCta": "读经计划 →",
        "pages.read.plansEmpty": "暂无计划数据。在本机运行 npm run import:reading-plans 可生成计划库。",
        "pages.read.plansFeaturedNtDeepPromo": "推荐 · 7 天连读",
        "pages.read.plansLeadDeepAfter": "——52 阶深读，可选 7 / 14 / 28 天节奏，约 12 个月至 4 年一轮。",
        "pages.read.plansLeadDeepBefore": "若你已在稳定读经、想把新约读进心里，可看",
        "pages.read.plansLeadDefaultAfter": "：旧约、新约、智慧书各读一小段，三条进度互不影响，适合第一次尝试或希望少负担的人。",
        "pages.read.plansLeadDefaultBefore": "默认推荐",
        "pages.read.plansLeadIntro": "AskBible 的读经计划，不是一年通读的打卡表。我们希望帮你建立一种长期、低压力、可持续回到神话语的节奏——不补读、不展示「落后」，停了再回来也可以。",
        "pages.read.plansLeadOther": "以下亦可选用麦琴、一年通读等经典日课表。",
        "pages.read.plansMeta": "{{days}} 天 · 单日至多 {{max}} 段",
        "pages.read.plansMethodLead": "我们整理两条主要路线，供不同季节选用；都不是「必读毕」的 KPI，而是可以长期并行、随时切换节奏的陪伴。",
        "pages.read.plansMethodPath1Badge": "轻松读经",
        "pages.read.plansMethodPath1Lead": "旧约、新约、智慧书三条独立循环，每日各读一小段。完成哪条只推哪条，负担轻，适合第一次建立习惯，或希望低压、可持续地回到神话语。",
        "pages.read.plansMethodPath1Link": "进入三循环计划",
        "pages.read.plansMethodPath1Title": "三循环通读",
        "pages.read.plansMethodPath2ArticleLink": "麦克阿瑟的研经方法",
        "pages.read.plansMethodPath2Badge": "正式研读",
        "pages.read.plansMethodPath2Lead": "参考约翰·麦克阿瑟的新约研读法——同一段经文反复读，直到读进心里——我们整理为 52 阶阶梯，并从每阶 7 天起提供 7 / 14 / 28 三种深度（约 12 个月 / 2 年 / 4 年一轮）；旧约每日一章通读并行。",
        "pages.read.plansMethodPath2Link": "进入深读计划",
        "pages.read.plansMethodPath2Reference": "背景与原理见",
        "pages.read.plansMethodPath2Title": "7 天连读",
        "pages.read.plansMethodTitle": "AskBible 读经方法",
        "pages.read.plansNav": "读经计划",
        "pages.read.plansOpen": "查看",
        "pages.read.plansTitle": "读经计划",
        "pages.read.title": "圣经",
        "pages.read.titleEn": "HOLY BIBLE",
        "pages.read.titleHe": "תנ״ך",
        "pages.read.todayPlanAheadHint": "正在阅读第 {{n}} 天（超前）",
        "pages.read.todayPlanAheadLabel": "超前阅读",
        "pages.read.todayPlanAllPlans": "全部计划",
        "pages.read.todayPlanAnchorEaster": "自 2026 年复活节起",
        "pages.read.todayPlanAnchorJan1": "对齐 1 月 1 日",
        "pages.read.todayPlanAnchorToday": "自选定日起",
        "pages.read.todayPlanBackToToday": "回到今天",
        "pages.read.todayPlanChange": "调整计划",
        "pages.read.todayPlanCompleteCelebrationAria": "今日读经已全部完成",
        "pages.read.todayPlanDayMeta": "第 {{n}} 天",
        "pages.read.todayPlanEmpty": "今日暂无经文段。",
        "pages.read.todayPlanLoading": "正在载入…",
        "pages.read.todayPlanMarkDone": "标记为已读",
        "pages.read.todayPlanMarkUndone": "取消已读",
        "pages.read.todayPlanNone": "尚未选择读经计划。",
        "pages.read.todayPlanReadNextDay": "多读下一天",
        "pages.read.todayPlanSeeHome": "在圣经首页查看今日经文 →",
        "pages.read.todayPlanTitle": "今日读经",
        "pages.read.tripleLoopActivateHint": "设为当前计划后，默认按复活节历元与三轨顺序显示今日读经；你在读经页的调整会保存在本机。",
        "pages.read.tripleLoopAdvanceAria": "推进轻松循环读经",
        "pages.read.tripleLoopAdvanceButton": "本节已读，推进{{track}}",
        "pages.read.tripleLoopAdvanceHint": "若已读完本节，可只推进「{{track}}」的下一处（按我们的书卷顺序）；其它两条不会变。",
        "pages.read.tripleLoopAdvanceSaving": "保存中…",
        "pages.read.tripleLoopChapterUnit": "章",
        "pages.read.tripleLoopDeepReadArticleLink": "麦克阿瑟的研经方法",
        "pages.read.tripleLoopDeepReadLead": "方法一适合无压力通读。若你已稳定读经、想把新约读进心里，可进阶方法二「有效深读」——参考麦克阿瑟研经法，52 阶从 7 天/阶起，可选 14 / 28 天（约 12 个月至 4 年一轮）。",
        "pages.read.tripleLoopDeepReadPlanLink": "进入深读计划（方法二）",
        "pages.read.tripleLoopDeepReadTitle": "进阶到方法二？",
        "pages.read.tripleLoopEpochNote": "默认以 2026 年 4 月 5 日（复活节）为第 1 天，按旧约·新约·智慧书顺序每日各进一章；你可随时在章节页推进或重置为默认位置。",
        "pages.read.tripleLoopPlansMeta": "三条独立循环 · 每日各一段",
        "pages.read.tripleLoopPrinciple1": "三项进度互不绑定；只读新约就只推进新约指针。",
        "pages.read.tripleLoopPrinciple2": "不按中断天数补读，不展示「落后」类文案。",
        "pages.read.tripleLoopPrinciple3": "每环读完末卷末章后回到该环起点。",
        "pages.read.tripleLoopPrinciplesTitle": "节奏说明",
        "pages.read.tripleLoopPsalmUnit": "篇",
        "pages.read.tripleLoopReadingLine": "{{name}} 第 {{chapter}} {{unit}}",
        "pages.read.tripleLoopResetToDefault": "恢复为默认进度",
        "pages.read.tripleLoopTodaySummary": "旧约、新约、智慧书各读一小段；可从任意一条进入，三条进度互不影响。",
        "pages.read.tripleLoopTodayTitle": "今日读经",
        "pages.read.tripleLoopTrackNt": "新约循环",
        "pages.read.tripleLoopTrackOt": "旧约循环",
        "pages.read.tripleLoopTrackWisdom": "智慧书循环",
        "pages.read.tripleLoopWhyArticleLink": "了解为什么要这样读",
        "mobile.plansIntro": "不打卡，别担心漏读。",
        "mobile.plansOtherHeading": "经典日课表",
        "mobile.plansOtherLead": "麦琴、一年通读等常见读经表。",
        "mobile.open": "查看",
        "mobile.activePill": "当前计划",
        "mobile.todayHeading": "今日读经",
        "mobile.todayHint": "点一条就进入那一章",
        "mobile.setupHeading": "开始使用",
        "mobile.howHeading": "怎么读",
        "mobile.moreOpen": "了解更多",
        "mobile.moreClose": "收起",
        "mobile.use": "设为当前计划",
        "mobile.update": "保存设置",
        "mobile.clear": "取消当前计划",
        "mobile.currentDay": "第 {{n}} 天",
        "mobile.paceHeading": "选一种深度",
        "mobile.paceHint": "同一阶新约连读几天再换下一阶",
        "mobile.pace7": "一年 · 读 7 遍",
        "mobile.pace14": "两年 · 读 14 遍",
        "mobile.pace28": "四年 · 读 28 遍",
        "mobile.paceEnd": "首阶到 {{endDate}} 结束",
        "mobile.startDayHeading": "从第几天开始",
        "mobile.startDayHint": "第一次读保持 1；之前读到第 20 天，就设为 20。",
        "mobile.anchorToday": "从今天开始",
        "mobile.anchorTodayHint": "今天算第 1 天",
        "mobile.anchorJan1": "对齐 1 月 1 日",
        "mobile.anchorJan1Hint": "按今年过了几天算",
        "mobile.ladderHeading": "新约 52 阶",
        "mobile.ladderProgress": "第 {{n}} 阶 · 本阶第 {{day}}/{{total}} 天",
        "mobile.ladderOpen": "展开全部 52 阶",
        "mobile.ladderClose": "收起",
        "mobile.stageDone": "已读完",
        "mobile.stageCurrent": "进行中",
        "mobile.toDeepTitle": "想读得更深？",
        "mobile.toDeepLead": "方法二 · 正式研读：同一段新约反复读",
        "mobile.toLightTitle": "刚开始读经？",
        "mobile.toLightLead": "方法一 · 轻松读经：每天三小段，没有压力",
        "mobile.resetDefault": "恢复默认进度",
        "mobile.epochTriple": "默认以 {{date}}（复活节）为第 1 天，三轨每日各进一章。今天是第 {{n}} 天。",
        "mobile.epochNt": "自你选定计划那天起算，今天是第 {{n}} 天。",
        "mobile.seeHome": "在圣经首页查看今日经文",
    ]
    static func t(_ key: String) -> String { strings[key] ?? key }
    static func f(_ key: String, _ args: [String: String]) -> String {
        var s = t(key)
        for (k, v) in args { s = s.replacingOccurrences(of: "{{\(k)}}", with: v) }
        return s
    }
}
