// 由 tools/gen-site-copy.mjs 从 zh-CN.json / en.json / site-copy.ts 回退 / mobile-brief / native-copy-extra 生成，勿手改。
import Foundation

/// 原生两端共用的界面文案：简体真源 + 英文；繁体面运行时 ZhTw 转。`f` 做 {{name}} 占位替换。
/// 不传 locale 用 AppLocale.current（壳在语言变化时更新）。
enum SiteCopy {
    static let strings: [String: (zh: String, en: String)] = [
        "admin.mediaLibrary.kindOther": ("其他", "Other"),
        "auth.continueWithApple": ("使用 Apple 登录", "Continue with Apple"),
        "auth.continueWithGoogle": ("使用 Google 登录", "Continue with Google"),
        "auth.drawerLogout": ("退出登录", "Sign out"),
        "auth.email": ("邮箱", "Email"),
        "auth.errorNetwork": ("网络异常，请重试。", "Network error. Try again."),
        "auth.loginFooterRegister": ("没有账号？去注册", "New here? Create an account"),
        "auth.orDivider": ("或", "or"),
        "auth.pageTitle": ("登录", "Sign in"),
        "auth.password": ("密码", "Password"),
        "auth.registerGoLogin": ("已有账号？去登录", "Already have an account? Sign in"),
        "auth.registerIntro": ("创建账号后，可使用同一邮箱与密码登录。", "Create an account, then sign in with the same email and password."),
        "auth.registerName": ("昵称（可选）", "Display name (optional)"),
        "auth.registerPageTitle": ("注册", "Create account"),
        "auth.registerSubmit": ("注册", "Create account"),
        "auth.submit": ("登录", "Sign in"),
        "mobile.activePill": ("当前计划", "Current plan"),
        "mobile.anchorJan1": ("对齐 1 月 1 日", "Align to January 1"),
        "mobile.anchorJan1Hint": ("按今年过了几天算", "Counted by the days elapsed this year"),
        "mobile.anchorToday": ("从今天开始", "Start today"),
        "mobile.anchorTodayHint": ("今天算第 1 天", "Today counts as day 1"),
        "mobile.clear": ("取消当前计划", "Stop this plan"),
        "mobile.currentDay": ("第 {{n}} 天", "Day {{n}}"),
        "mobile.epochNt": ("自你选定计划那天起算，今天是第 {{n}} 天。", "Counted from the day you chose this plan; today is day {{n}}."),
        "mobile.epochTriple": ("默认以 {{date}}（复活节）为第 1 天，三轨每日各进一章。今天是第 {{n}} 天。", "By default day 1 is {{date}} (Easter); each of the three tracks advances one chapter a day. Today is day {{n}}."),
        "mobile.fetchNatureHint": ("无法连接 {{base}}：请在仓库根目录运行 npm run dev；真机请将 .env 改为电脑局域网 IP（参考 apps/askbible-mobile/env.device.example）", "Cannot connect to {{base}}. Run npm run dev at the repo root; on a device, set your Mac's LAN IP in .env (see apps/askbible-mobile/env.device.example)."),
        "mobile.fetchNotJson": ("站点返回了非 JSON 内容", "The site returned non-JSON content."),
        "mobile.fetchTimeout": ("连接超时：请确认电脑已运行 npm run dev（端口 3450），真机需与电脑同一 Wi‑Fi 并用 npx expo start --lan", "Connection timed out. Confirm npm run dev is running on port 3450; on a physical device use the same Wi‑Fi and npx expo start --lan."),
        "mobile.howHeading": ("怎么读", "How it works"),
        "mobile.ladderClose": ("收起", "Show less"),
        "mobile.ladderHeading": ("新约 52 阶", "52 New Testament stages"),
        "mobile.ladderOpen": ("展开全部 52 阶", "Show all 52 stages"),
        "mobile.ladderProgress": ("第 {{n}} 阶 · 本阶第 {{day}}/{{total}} 天", "Stage {{n}} · day {{day}}/{{total}} of this stage"),
        "mobile.moreClose": ("收起", "Show less"),
        "mobile.moreOpen": ("了解更多", "Learn more"),
        "mobile.open": ("查看", "Open"),
        "mobile.pace14": ("两年 · 读 14 遍", "2 years · 14 readings"),
        "mobile.pace28": ("四年 · 读 28 遍", "4 years · 28 readings"),
        "mobile.pace7": ("一年 · 读 7 遍", "1 year · 7 readings"),
        "mobile.paceEnd": ("首阶到 {{endDate}} 结束", "First stage ends on {{endDate}}"),
        "mobile.paceHeading": ("选一种深度", "Choose a depth"),
        "mobile.paceHint": ("同一阶新约连读几天再换下一阶", "How many days to stay on one New Testament stage before moving on"),
        "mobile.plansIntro": ("不打卡，别担心漏读。", "No check-ins. Never worry about missing a day."),
        "mobile.plansOtherHeading": ("经典日课表", "Classic reading schedules"),
        "mobile.plansOtherLead": ("麦琴、一年通读等常见读经表。", "M'Cheyne, through-the-Bible-in-a-year and other familiar schedules."),
        "mobile.resetDefault": ("恢复默认进度", "Reset to default progress"),
        "mobile.seeHome": ("在圣经首页查看今日经文", "See today's readings on the Bible home page"),
        "mobile.setupHeading": ("开始使用", "Get started"),
        "mobile.stageCurrent": ("进行中", "In progress"),
        "mobile.stageDone": ("已读完", "Completed"),
        "mobile.startDayHeading": ("从第几天开始", "Start from day"),
        "mobile.startDayHint": ("第一次读保持 1；之前读到第 20 天，就设为 20。", "Keep 1 for a first read; if you had reached day 20 before, set 20."),
        "mobile.toDeepLead": ("方法二 · 正式研读：同一段新约反复读", "Path 2 · Formal study: read the same New Testament passage again and again"),
        "mobile.toDeepTitle": ("想读得更深？", "Want to go deeper?"),
        "mobile.toLightLead": ("方法一 · 轻松读经：每天三小段，没有压力", "Path 1 · Easy reading: three short readings a day, no pressure"),
        "mobile.toLightTitle": ("刚开始读经？", "Just starting to read?"),
        "mobile.todayHeading": ("今日读经", "Today's reading"),
        "mobile.todayHint": ("点一条就进入那一章", "Tap a line to open that chapter"),
        "mobile.update": ("保存设置", "Save settings"),
        "mobile.use": ("设为当前计划", "Use this plan"),
        "native.albumAfternoon": ("休闲", "Leisure"),
        "native.albumCalm": ("放松", "Calm"),
        "native.albumHymns": ("圣诗", "Hymns"),
        "native.albumPiano": ("钢琴", "Piano"),
        "native.albumSleep": ("睡眠", "Sleep"),
        "native.albumWork": ("工作", "Focus"),
        "native.ambientNowPlaying": ("AskBible · 环境音", "AskBible · Ambience"),
        "native.articleTapHint": ("点按段落可展开或收起", "Tap a section to expand or collapse"),
        "native.audioLoadFailed": ("音频加载失败", "Audio failed to load"),
        "native.audioSessionFailed": ("音频会话配置失败：{{error}}", "Audio session setup failed: {{error}}"),
        "native.authAppleFailed": ("Apple 登录失败，请重试。", "Apple sign-in failed. Please try again."),
        "native.authAppleNotConfigured": ("Apple 登录尚未配置。请在 Supabase 的 Apple 提供商中登记 Bundle ID：me.askbible.native。", "Apple sign-in is not configured yet. Register the bundle ID me.askbible.native under the Apple provider in Supabase."),
        "native.authDefaultName": ("用户", "friend"),
        "native.authEmailNotConfirmed": ("请先完成邮箱验证后再登录。", "Please verify your email before logging in."),
        "native.authEmailTaken": ("该邮箱已注册。", "This email is already registered."),
        "native.authGreetingGuest": ("请登录，解锁更多", "Log in to unlock more"),
        "native.authGreetingNamed": ("你好，{{name}}", "Hello, {{name}}"),
        "native.authInvalidCredentials": ("邮箱或密码不正确。", "Incorrect email or password."),
        "native.cancel": ("取消", "Cancel"),
        "native.chapterFetching": ("正在获取经文…", "Loading the chapter…"),
        "native.chapterUnit": ("{{bookName}} {{chapter}}章", "{{bookName}} {{chapter}}"),
        "native.dailySegments": ("每日 ≤ {{n}} 段", "≤ {{n}} readings a day"),
        "native.days": ("{{n}} 天", "{{n}} days"),
        "native.downloading": ("下载中", "Downloading"),
        "native.durationDays": ("{{n}} 天", "{{n}} days"),
        "native.durationMonths": ("约 {{n}} 个月", "about {{n}} months"),
        "native.durationYears": ("约 {{n}} 年", "about {{n}} years"),
        "native.followSystem": ("跟随系统", "System"),
        "native.goldenVerseNowPlaying": ("AskBible · 金句", "AskBible · Verse"),
        "native.langEnglish": ("英文", "English"),
        "native.langSimplified": ("简中", "Simp. Chinese"),
        "native.langTraditional": ("繁中", "Trad. Chinese"),
        "native.listenTotal": ("累计听 {{duration}}", "Listened {{duration}}"),
        "native.minutes": ("{{m}} 分钟", "{{m}} min"),
        "native.musicLoadFailed": ("音乐加载失败", "Music failed to load"),
        "native.needDownload": ("需下载", "Download"),
        "native.noReadingRecord": ("还没有阅读记录", "No reading history yet"),
        "native.none": ("无", "None"),
        "native.online": ("在线", "Online"),
        "native.recentReading": ("最近阅读", "Recently read"),
        "native.save": ("保存", "Save"),
        "native.searchFallbackNote": ("当前译本是在线译本，暂不支持搜索；已改用「{{name}}」搜索", "The current translation is online-only and can't be searched; searching {{name}} instead"),
        "native.sleepTimer": ("睡眠定时", "Sleep timer"),
        "native.sleepTimerLeft": ("剩余 {{left}}", "{{left}} left"),
        "native.sleepTimerOff": ("关闭定时", "Turn off"),
        "native.stepDayPrefix": ("第", "Day"),
        "native.stepDaySuffix": ("天", ""),
        "native.syncNoSession": ("未找到登录会话", "No signed-in session found"),
        "native.syncOffline": ("当前无网络", "No network connection"),
        "native.syncPullFailed": ("拉取失败", "Fetch failed"),
        "native.syncPullFailedAfterSwitch": ("帐号切换后拉取失败", "Could not fetch after switching accounts"),
        "native.syncPullFailedFirst": ("未绑定先拉取失败：{{message}}", "Initial fetch failed: {{message}}"),
        "native.syncPushFailed": ("上传失败：{{message}}", "Upload failed: {{message}}"),
        "native.syncPushFailedAfterMerge": ("合并后再次上传失败：{{message}}", "Upload failed again after merging: {{message}}"),
        "native.syncUnauthorized": ("登录已失效，请重新登录", "Your session has expired. Please sign in again."),
        "native.trackNoSource": ("这首曲子没有可用音源", "No audio source for this track"),
        "native.translationDownloading": ("正在下载这个译本…", "Downloading this translation…"),
        "native.translationOfflineHint": ("这个译本要联网获取，暂时拿不到，请检查网络后重试", "This translation is fetched online and isn't available right now. Check your connection and retry."),
        "native.usageTime": ("使用时长", "Time in app"),
        "nav.language": ("语言", "Language"),
        "pages.explore.birthYearModalNamePlaceholder": ("你的名字", "Your name"),
        "pages.explore.greetingEditTitle": ("修改称呼", "Edit name"),
        "pages.read.chapterChromeBack": ("返回", "Back"),
        "pages.read.chapterChromeNext": ("下一章", "Next chapter"),
        "pages.read.chapterEndNavPrev": ("上一章", "Previous chapter"),
        "pages.read.favoritesEmpty": ("还没有收藏的经文", "No bookmarked verses yet"),
        "pages.read.favoritesLead": ("你在读经时双击收藏的经文，会保存在本机。", "Verses you double-tap while reading are saved on this device."),
        "pages.read.favoritesTitle": ("收藏", "Bookmarks"),
        "pages.read.infoEditionDisclaimer": ("以下仅为参考资料，请对照圣经慎思明辨", "Reference material only—read alongside Scripture with discernment."),
        "pages.read.infoEditionLoadFailed": ("暂时无法加载本章讲解", "Could not load the chapter guide"),
        "pages.read.ntDeepRepeatActivateHint": ("设为当前计划后，今天为第 1 天，从第 1 阶《约翰一书》与创世纪第 1 章开始；先选深读节奏（三选一），再点「使用此计划」。", "When you set this plan active, today is day 1—stage 1 (1 John) plus Genesis 1. Choose a deep-reading pace (one of three), then tap Use this plan."),
        "pages.read.ntDeepRepeatAdvanceButtonNt": ("本节已读，推进{{track}}", "Done — advance {{track}}"),
        "pages.read.ntDeepRepeatAdvanceHintNt": ("若已读完本节，可推进「{{track}}」的下一段（本阶共 {{days}} 天，读满再换段）；旧约通读不会变。", "If you’ve finished this segment, advance “{{track}}” to the next day ({{days}} days per stage; new segment after that). OT read-through stays put."),
        "pages.read.ntDeepRepeatLabelSep": (" · ", " · "),
        "pages.read.ntDeepRepeatLadderLead": ("共 {{stages}} 阶，每阶连读 {{days}} 天；约 {{cycle}} 天走完一轮。", "{{stages}} stages, {{days}} days each—about {{cycle}} days per full cycle."),
        "pages.read.ntDeepRepeatLadderTitle": ("新约 52 版块", "52 NT stages"),
        "pages.read.ntDeepRepeatLighterPathLead": ("若你刚开始读经，或希望无压力通读，可先用方法一「三循环」建立节奏，再进阶方法二。", "If you are new to daily reading or want low-pressure read-through, start with Path 1 (triple loop), then step up to Path 2."),
        "pages.read.ntDeepRepeatLighterPathLink": ("试试无压力通读（方法一）", "Try easy read-through (Path 1)"),
        "pages.read.ntDeepRepeatLighterPathTitle": ("更适合方法一？", "Better with Path 1?"),
        "pages.read.ntDeepRepeatPace14Summary": ("二年轻松读14遍新约圣经", "Read through the NT 14 times in about two years"),
        "pages.read.ntDeepRepeatPace14Title": ("14 天 · 两周", "14 days · two weeks"),
        "pages.read.ntDeepRepeatPace28Summary": ("四年轻松读28遍新约圣经", "Read through the NT 28 times in about four years"),
        "pages.read.ntDeepRepeatPace28Title": ("28 天 · 四周", "28 days · four weeks"),
        "pages.read.ntDeepRepeatPace7Summary": ("一年轻松读7遍新约圣经", "Read through the NT 7 times in about one year"),
        "pages.read.ntDeepRepeatPace7Title": ("7 天 · 一周", "7 days · one week"),
        "pages.read.ntDeepRepeatPaceContinuousNote": ("从启用当天开始连续读 {{days}} 天；第 {{nextDay}} 天进入下一段，之后每段都按相同天数推进。", "Start from the activation day and read the same segment for {{days}} straight days; day {{nextDay}} moves to the next segment."),
        "pages.read.ntDeepRepeatPaceFirstSegmentNote": ("若今日开始：首段 {{days}} 天，至 {{endDate}} 结束。", "Starting today: first segment {{days}} days, ending on {{endDate}}."),
        "pages.read.ntDeepRepeatPaceIntro": ("同一段新约反复读，直到熟悉；旧约每天 1 章陪着读。参考麦克阿瑟研经法，从 7 天/段起步。", "Stay with each NT segment until it feels familiar; one OT chapter daily alongside. Based on MacArthur’s method, starting at 7 days per segment."),
        "pages.read.ntDeepRepeatPaceOneCycle": ("{{duration}}", "{{duration}}"),
        "pages.read.ntDeepRepeatPaceOtNote": ("同期旧约每日一章通读；约 {{years}} 年可通读一遍旧约（与新约并行）", "OT: one chapter daily in parallel; ~{{years}} yr for one full OT pass"),
        "pages.read.ntDeepRepeatPacePass14": ("14 遍（每阶 14 天）", "14× (14 days/stage)"),
        "pages.read.ntDeepRepeatPacePass28": ("28 遍（每阶 28 天）", "28× (28 days/stage)"),
        "pages.read.ntDeepRepeatPacePass7": ("7 遍（每阶 7 天）", "7× (7 days/stage)"),
        "pages.read.ntDeepRepeatPaceTimelineDuration": ("大约", "About"),
        "pages.read.ntDeepRepeatPaceTimelineHeader": ("三种深度，大约需要多久", "How long each depth takes (approx.)"),
        "pages.read.ntDeepRepeatPaceTimelinePass": ("深度", "Depth"),
        "pages.read.ntDeepRepeatPaceTitle": ("选一种深度（三选一）", "Choose a depth (pick one)"),
        "pages.read.ntDeepRepeatPlansMeta": ("旧约通读 · 新约 52 阶 · 7 / 14 / 28 天节奏", "OT read-through · NT 52 stages · 7 / 14 / 28-day pace"),
        "pages.read.ntDeepRepeatPrinciple1": ("方法二 · 有效深读：新约 52 阶（每阶通常 4–6 章），参考麦克阿瑟「同段反复读进心里」；「N 遍」= 每阶连读 N 天；旧约每日一章通读。", "Path 2 · Effective deep study: 52 NT stages (usually 4–6 chapters), inspired by MacArthur’s “repeat until it sinks in”; “N passes” = N days per stage; one OT chapter daily."),
        "pages.read.ntDeepRepeatPrinciple2": ("不按中断补读，不展示「落后」；停了再回来即可。", "No catch-up or “behind” messaging—just pick up where you are."),
        "pages.read.ntDeepRepeatPrinciple3": ("从 7 天/阶起步，可选 14 / 28 天加深；走完 52 阶为一轮，约 12 个月 / 2 年 / 4 年。", "Start at 7 days/stage; optional 14 / 28-day depth—one round (52 stages) ≈ 12 mo / 2 yr / 4 yr."),
        "pages.read.ntDeepRepeatPrinciplesTitle": ("AskBible 深读方法", "AskBible deep-reading method"),
        "pages.read.ntDeepRepeatSegmentLabel": ("第 {{day}}/{{total}} 天 · {{segment}}", "Day {{day}}/{{total}} · {{segment}}"),
        "pages.read.ntDeepRepeatSegmentRange": ("第 {{start}}–{{end}} 章", "ch. {{start}}–{{end}}"),
        "pages.read.ntDeepRepeatSegmentSingleChapter": ("第 {{chapter}} 章", "ch. {{chapter}}"),
        "pages.read.ntDeepRepeatSetStageAsTodayBody": ("将第 {{n}} 阶「{{range}}」设为今日新约读经？", "Set stage {{n}} ({{range}}) as today’s New Testament reading?"),
        "pages.read.ntDeepRepeatSetStageAsTodayCancel": ("取消", "Cancel"),
        "pages.read.ntDeepRepeatSetStageAsTodayConfirm": ("设为今日", "Set as today"),
        "pages.read.ntDeepRepeatSetStageAsTodayTitle": ("设为今日读经", "Set as today’s reading"),
        "pages.read.ntDeepRepeatStageBookRange": ("{{name}} 第 {{start}}–{{end}} 章", "{{name}} ch. {{start}}–{{end}}"),
        "pages.read.ntDeepRepeatStageBookSingle": ("{{name}} 第 {{chapter}} 章", "{{name}} ch. {{chapter}}"),
        "pages.read.ntDeepRepeatStageCurrent": ("进行中 · 第 {{day}}/{{total}} 天", "In progress · day {{day}}/{{total}}"),
        "pages.read.ntDeepRepeatStageDone": ("已完成本阶", "Stage complete"),
        "pages.read.ntDeepRepeatStageLabel": ("第 {{n}} 阶", "Stage {{n}}"),
        "pages.read.ntDeepRepeatStagesBelowHint": ("点选某一阶，可设为今日新约读经。", "Tap a stage to make it today’s New Testament reading."),
        "pages.read.ntDeepRepeatStartNote": ("自选定计划日起计；今日为", "Day count from when you chose this plan; today is"),
        "pages.read.ntDeepRepeatTodaySummary": ("先读新约当前阶，再读旧约一章；两条进度互不影响。", "New Testament stage first, then one Old Testament chapter—two independent tracks."),
        "pages.read.ntDeepRepeatTodayTitle": ("今日读经", "Today's reading"),
        "pages.read.ntDeepRepeatTrackNt": ("新约深读", "New Testament deep repeat"),
        "pages.read.ntDeepRepeatTrackOt": ("旧约通读", "Old Testament read-through"),
        "pages.read.ntDeepRepeatWhyArticleLink": ("麦克阿瑟研经法原文与说明", "MacArthur’s method — article"),
        "pages.read.planActivateClear": ("取消当前计划", "Clear active plan"),
        "pages.read.planActivateCurrentDay": ("今日为第 {{n}} 天", "Today is day {{n}}"),
        "pages.read.planActivateHeading": ("使用此计划", "Use this plan"),
        "pages.read.planActivateUpdate": ("更新起始方式", "Update start mode"),
        "pages.read.planActivateUse": ("设为当前计划", "Set as active plan"),
        "pages.read.planAnchorFromToday": ("从今天开始", "Start from today"),
        "pages.read.planAnchorFromTodayHint": ("选定的这一天为第 1 天；之后按自然日推进。", "Today becomes day 1; each calendar day advances one step."),
        "pages.read.planAnchorJan1": ("对齐当年 1 月 1 日", "Align with January 1"),
        "pages.read.planAnchorJan1Hint": ("今天对应该年 1 月 1 日起算的第几天（例如年中开始会落在表中较后位置）。", "Today maps to the day count from Jan 1 this year (starting mid-year lands further in the table)."),
        "pages.read.planDetailBackPlans": ("全部计划", "All plans"),
        "pages.read.planDetailDay": ("第 {{n}} 天", "Day {{n}}"),
        "pages.read.planDetailHint": ("链接进入该段的起始章；经节范围为表内参考。", "Links open the starting chapter; verse spans follow the upstream table."),
        "pages.read.planDetailTodayMark": ("（今日）", "(today)"),
        "pages.read.planPlayCalendarMonth": ("{{y}}年{{m}}月", "{{m}}/{{y}}"),
        "pages.read.planPlayCalendarNextMonth": ("下个月", "Next month"),
        "pages.read.planPlayCalendarPrevMonth": ("上个月", "Previous month"),
        "pages.read.planPlayConfirmDay": ("进度设置为今日", "Set progress as today"),
        "pages.read.planPlayHeaderTitle": ("{{name}}", "{{name}}"),
        "pages.read.planPlayLead": ("连续播放今日读经计划。", "Play today’s reading plan continuously."),
        "pages.read.planPlayListenTotalLabel": ("累计听 {{duration}}", "Total listened {{duration}}"),
        "pages.read.planPlayNextChapter": ("下一读经章", "Next chapter"),
        "pages.read.planPlayNextDay": ("明天", "Tomorrow"),
        "pages.read.planPlayNowPlaying": ("正在朗读：{{title}}", "Now playing: {{title}}"),
        "pages.read.planPlayPlanDayLabel": ("计划已进行第 {{n}} 天", "Day {{n}} of this plan"),
        "pages.read.planPlayPlay": ("播放今日读经", "Play today’s reading"),
        "pages.read.planPlayPlayChapterAudio": ("声音", "Listen"),
        "pages.read.planPlayPoolHeading": ("今日播放", "Today’s queue"),
        "pages.read.planPlayPrevChapter": ("上一读经章", "Previous chapter"),
        "pages.read.planPlayPrevDay": ("昨天", "Yesterday"),
        "pages.read.planPlayReadChapter": ("阅读", "Read"),
        "pages.read.planPlayRepeatChapter": ("单章循环", "Repeat chapter"),
        "pages.read.planPlayRepeatOff": ("循环关闭", "Repeat off"),
        "pages.read.planPlayRepeatPool": ("播放列表循环", "Repeat playlist"),
        "pages.read.planPlayTitle": ("读经计划", "Reading plan"),
        "pages.read.planPlayTrackMeta": ("{{current}} / {{total}}", "{{current}} / {{total}}"),
        "pages.read.plansCta": ("读经计划 →", "Reading plans →"),
        "pages.read.plansEmpty": ("暂无计划数据。在本机运行 npm run import:reading-plans 可生成计划库。", "No plans bundled yet. Run npm run import:reading-plans locally to generate the library."),
        "pages.read.plansFeaturedNtDeepPromo": ("推荐 · 7 天连读", "Recommended · 7-day repeats"),
        "pages.read.plansLeadDeepAfter": ("——52 阶深读，可选 7 / 14 / 28 天节奏，约 12 个月至 4 年一轮。", "—52 stages, 7 / 14 / 28-day depth, about 12 months to 4 years per round."),
        "pages.read.plansLeadDeepBefore": ("若你已在稳定读经、想把新约读进心里，可看", "If you already read steadily and want the NT to sink in, see"),
        "pages.read.plansLeadDefaultAfter": ("：旧约、新约、智慧书各读一小段，三条进度互不影响，适合第一次尝试或希望少负担的人。", ": a short OT, NT, and Wisdom segment each day on three independent tracks—gentle for first tries or lighter daily load."),
        "pages.read.plansLeadDefaultBefore": ("默认推荐", "We recommend starting with"),
        "pages.read.plansLeadIntro": ("AskBible 的读经计划，不是一年通读的打卡表。我们希望帮你建立一种长期、低压力、可持续回到神话语的节奏——不补读、不展示「落后」，停了再回来也可以。", "AskBible reading plans are not one-year checklists. We help you build a long-term, low-pressure rhythm for returning to Scripture—no catch-up, no “behind” messaging; you can always come back."),
        "pages.read.plansLeadOther": ("以下亦可选用麦琴、一年通读等经典日课表。", "You can also pick M'Cheyne, one-year tables, and other classic day-by-day plans below."),
        "pages.read.plansMeta": ("{{days}} 天 · 单日至多 {{max}} 段", "{{days}} days · up to {{max}} readings per day"),
        "pages.read.plansMethodLead": ("我们整理两条主要路线，供不同季节选用；都不是「必读毕」的 KPI，而是可以长期并行、随时切换节奏的陪伴。", "We offer two main paths for different seasons—not KPIs you must finish, but companions you can stay with or switch between."),
        "pages.read.plansMethodPath1Badge": ("轻松读经", "Path 1"),
        "pages.read.plansMethodPath1Lead": ("旧约、新约、智慧书三条独立循环，每日各读一小段。完成哪条只推哪条，负担轻，适合第一次建立习惯，或希望低压、可持续地回到神话语。", "Three independent loops—OT, NT, and Wisdom—one short segment per track each day. Finishing one track only advances that track. Light load for first habits or a sustainable, low-pressure return to Scripture."),
        "pages.read.plansMethodPath1Link": ("进入三循环计划", "Open the triple-loop plan"),
        "pages.read.plansMethodPath1Title": ("三循环通读", "Easy read-through"),
        "pages.read.plansMethodPath2ArticleLink": ("麦克阿瑟的研经方法", "MacArthur’s study method"),
        "pages.read.plansMethodPath2Badge": ("正式研读", "Path 2"),
        "pages.read.plansMethodPath2Lead": ("参考约翰·麦克阿瑟的新约研读法——同一段经文反复读，直到读进心里——我们整理为 52 阶阶梯，并从每阶 7 天起提供 7 / 14 / 28 三种深度（约 12 个月 / 2 年 / 4 年一轮）；旧约每日一章通读并行。", "Inspired by John MacArthur’s NT method—repeat each passage until it sinks in—we shaped a 52-stage ladder starting at 7 days per stage, with 14- and 28-day depths (~12 mo / 2 yr / 4 yr per round); one OT chapter daily in parallel."),
        "pages.read.plansMethodPath2Link": ("进入深读计划", "Open the deep-reading plan"),
        "pages.read.plansMethodPath2Reference": ("背景与原理见", "Background:"),
        "pages.read.plansMethodPath2Title": ("7 天连读", "Effective deep study"),
        "pages.read.plansMethodTitle": ("AskBible 读经方法", "AskBible reading approach"),
        "pages.read.plansNav": ("读经计划", "Plans"),
        "pages.read.plansOpen": ("查看", "Open"),
        "pages.read.plansTitle": ("读经计划", "Reading plans"),
        "pages.read.postReadingBackToTop": ("回到顶部", "Back to top"),
        "pages.read.postReadingEditionsHeading": ("继续阅读与思考", "Read Scripture together, next"),
        "pages.read.postReadingEditionsLead": ("你可以先安静查阅资料，再回到经文里。", "Start with quiet references, then return to the text."),
        "pages.read.postReadingEditionsTapHint": ("点按下方任一卡片进入", "Tap either card below to continue"),
        "pages.read.retry": ("重试", "Retry"),
        "pages.read.scriptureSearchEmpty": ("没有找到匹配的经文", "No matching verses"),
        "pages.read.scriptureSearchLead": ("在当前译本中按关键词查找经文。", "Search verses by keyword in your current translation."),
        "pages.read.scriptureSearchNoChapterHint": ("暂无当前章节，请先打开一章后再搜索本章。", "No current chapter. Open a chapter first to search within it."),
        "pages.read.scriptureSearchPlaceholder": ("输入关键词", "Enter a keyword"),
        "pages.read.scriptureSearchRecentTitle": ("最近搜索", "Recent searches"),
        "pages.read.scriptureSearchScopeAll": ("全本", "Whole Bible"),
        "pages.read.scriptureSearchScopeChapter": ("本章", "This chapter"),
        "pages.read.scriptureSearchScopeNew": ("新约", "New Testament"),
        "pages.read.scriptureSearchScopeOld": ("旧约", "Old Testament"),
        "pages.read.scriptureSearchTitle": ("经文搜索", "Search Scripture"),
        "pages.read.title": ("圣经", "Holy Bible"),
        "pages.read.titleEn": ("HOLY BIBLE", "HOLY BIBLE"),
        "pages.read.titleHe": ("תנ״ך", "תנ״ך"),
        "pages.read.todayPlanAheadHint": ("正在阅读第 {{n}} 天（超前）", "Reading day {{n}} (ahead)"),
        "pages.read.todayPlanAheadLabel": ("超前阅读", "Ahead"),
        "pages.read.todayPlanAllPlans": ("全部计划", "All plans"),
        "pages.read.todayPlanAnchorEaster": ("自 2026 年复活节起", "From Easter 2026"),
        "pages.read.todayPlanAnchorJan1": ("对齐 1 月 1 日", "Jan 1 aligned"),
        "pages.read.todayPlanAnchorToday": ("自选定日起", "From chosen start"),
        "pages.read.todayPlanBackToToday": ("回到今天", "Back to today"),
        "pages.read.todayPlanChange": ("调整计划", "Adjust plan"),
        "pages.read.todayPlanCompleteCelebrationAria": ("今日读经已全部完成", "Today's readings are complete"),
        "pages.read.todayPlanDayMeta": ("第 {{n}} 天", "Day {{n}}"),
        "pages.read.todayPlanEmpty": ("今日暂无经文段。", "No readings for today."),
        "pages.read.todayPlanLoading": ("正在载入…", "Loading…"),
        "pages.read.todayPlanMarkDone": ("标记为已读", "Mark as read"),
        "pages.read.todayPlanMarkUndone": ("取消已读", "Mark as unread"),
        "pages.read.todayPlanNone": ("尚未选择读经计划。", "No reading plan selected yet."),
        "pages.read.todayPlanReadNextDay": ("多读下一天", "Read next day"),
        "pages.read.todayPlanSeeHome": ("在圣经首页查看今日经文 →", "See today’s readings on Scripture home →"),
        "pages.read.todayPlanTitle": ("今日读经", "Today’s readings"),
        "pages.read.todayReadingStatReadLabel": ("读经天", "Days read"),
        "pages.read.todayReadingStatStreakLabel": ("连续天", "Streak"),
        "pages.read.todayReadingStatYearDayLabel": ("今年已过", "Day of year"),
        "pages.read.tripleLoopActivateHint": ("设为当前计划后，默认按复活节历元与三轨顺序显示今日读经；你在读经页的调整会保存在本机。", "When active, today's three segments default to the Easter epoch and our track order. Changes you make while reading are saved on this device."),
        "pages.read.tripleLoopAdvanceAria": ("推进轻松循环读经", "Advance easy cycle reading"),
        "pages.read.tripleLoopAdvanceButton": ("本节已读，推进{{track}}", "Done—advance {{track}}"),
        "pages.read.tripleLoopAdvanceHint": ("若已读完本节，可只推进「{{track}}」的下一处（按我们的书卷顺序）；其它两条不会变。", "Finished this section? Advance only “{{track}}” along our book order; the other two stay unchanged."),
        "pages.read.tripleLoopAdvanceSaving": ("保存中…", "Saving…"),
        "pages.read.tripleLoopChapterUnit": ("章", "ch."),
        "pages.read.tripleLoopDeepReadArticleLink": ("麦克阿瑟的研经方法", "MacArthur’s study method"),
        "pages.read.tripleLoopDeepReadLead": ("方法一适合无压力通读。若你已稳定读经、想把新约读进心里，可进阶方法二「有效深读」——参考麦克阿瑟研经法，52 阶从 7 天/阶起，可选 14 / 28 天（约 12 个月至 4 年一轮）。", "Path 1 is for easy read-through. If you read steadily and want the NT to sink in, try Path 2—MacArthur-inspired deep study: 52 stages from 7 days/stage, optional 14 / 28-day depth (~12 mo to 4 yr per round)."),
        "pages.read.tripleLoopDeepReadPlanLink": ("进入深读计划（方法二）", "Open deep-reading plan (Path 2)"),
        "pages.read.tripleLoopDeepReadTitle": ("进阶到方法二？", "Step up to Path 2?"),
        "pages.read.tripleLoopEpochNote": ("默认以 2026 年 4 月 5 日（复活节）为第 1 天，按旧约·新约·智慧书顺序每日各进一章；你可随时在章节页推进或重置为默认位置。", "By default, day 1 is 5 Apr 2026 (Easter); each track moves one chapter per day in OT · NT · Wisdom order. You can advance or reset to default on the chapter page."),
        "pages.read.tripleLoopPlansMeta": ("三条独立循环 · 每日各一段", "Three independent tracks · one segment each per day"),
        "pages.read.tripleLoopPrinciple1": ("三项进度互不绑定；只读新约就只推进新约指针。", "Tracks do not lock together; reading NT only advances the NT pointer."),
        "pages.read.tripleLoopPrinciple2": ("不按中断天数补读，不展示「落后」类文案。", "No catch-up days or “behind” messaging if you pause."),
        "pages.read.tripleLoopPrinciple3": ("每环读完末卷末章后回到该环起点。", "After the last chapter of a track, that track restarts at the beginning."),
        "pages.read.tripleLoopPrinciplesTitle": ("节奏说明", "How it works"),
        "pages.read.tripleLoopPsalmUnit": ("篇", "Ps."),
        "pages.read.tripleLoopReadingLine": ("{{name}} 第 {{chapter}} {{unit}}", "{{name}} {{chapter}}"),
        "pages.read.tripleLoopResetToDefault": ("恢复为默认进度", "Reset to default progress"),
        "pages.read.tripleLoopTodaySummary": ("旧约、新约、智慧书各读一小段；可从任意一条进入，三条进度互不影响。", "A short reading in Old Testament, New Testament, and Wisdom each; start with any track—progress stays separate."),
        "pages.read.tripleLoopTodayTitle": ("今日读经", "Today's three segments"),
        "pages.read.tripleLoopTrackNt": ("新约循环", "New Testament cycle"),
        "pages.read.tripleLoopTrackOt": ("旧约循环", "Old Testament cycle"),
        "pages.read.tripleLoopTrackWisdom": ("智慧书循环", "Wisdom cycle"),
        "pages.read.tripleLoopWhyArticleLink": ("了解为什么要这样读", "Why read this way"),
        "pages.read.verseActionBookmark": ("双击收藏", "Bookmark"),
        "pages.read.verseActionClose": ("关闭", "Close"),
        "pages.read.verseActionCopy": ("本节复制", "Copy this verse"),
        "pages.read.verseActionShare": ("分享", "Share"),
        "pages.read.verseActionVerseTitle": ("第 {{verse}} 节", "Verse {{verse}}"),
        "pages.read.verseCopied": ("已复制本节经文", "Verse copied"),
        "pages.read.verseXrefEmpty": ("暂无关联经文", "No cross-references for this verse"),
        "pages.read.verseXrefIncoming": ("被引用于", "Quoted in"),
        "pages.read.verseXrefOutgoing": ("相关经文", "Related passages"),
        "pages.read.verseXrefSheetTitle": ("{{bookName}} {{chapter}}:{{verse}} · 经文关联", "{{bookName}} {{chapter}}:{{verse}} · Cross-references"),
    ]

    static func t(_ key: String, _ locale: AppLocale = AppLocale.current) -> String {
        guard let s = strings[key] else { return key }
        return locale == .en ? s.en : locale.zh(s.zh)
    }

    static func f(_ key: String, _ args: [String: String], _ locale: AppLocale = AppLocale.current) -> String {
        var s = t(key, locale)
        for (k, v) in args { s = s.replacingOccurrences(of: "{{\(k)}}", with: v) }
        return s
    }

    /// 模型层产出的简体文案（登录 / 同步错误等，对拍规则要求它们保持简体）→ 按当前语言换成对应文案；不认识的原样返回
    static func localizeKnown(_ text: String, _ locale: AppLocale = AppLocale.current) -> String {
        let key = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let hit = strings.first(where: { $0.value.zh == key }) else { return locale.zh(text) }
        return t(hit.key, locale)
    }
}

/// 旧名：读经计划文案（pages.read.*）也在 SiteCopy 里
typealias PlanCopy = SiteCopy
