import { StyleSheet } from "react-native";
import { parchmentSans } from "../fonts/parchmentType";
import { readParchmentTheme as c } from "./readParchmentTheme";
import { SPLASH_BACKGROUND as LOGO_YELLOW } from "../shell/splash-branding.generated";

export const readChapterCompletionPlanPanelStyles = StyleSheet.create({
  card: {
    marginTop: 50,
    borderWidth: 1,
    borderColor: "rgba(113, 84, 53, 0.34)",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "rgba(249, 240, 222, 0.95)",
    width: "100%",
    maxWidth: 360,
    alignSelf: "center",
    shadowColor: "#3A2718",
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  titleWrap: {
    alignItems: "center",
  },
  titleName: {
    fontSize: 34,
    lineHeight: 40,
    ...parchmentSans(700),
    letterSpacing: 0.1,
    color: "#2A170A",
    textAlign: "center",
  },
  titleMain: {
    marginTop: 2,
    fontSize: 24,
    lineHeight: 30,
    ...parchmentSans(700),
    letterSpacing: 0,
    color: "#2A170A",
    textAlign: "center",
  },
  readingList: {
    marginTop: 10,
    gap: 8,
  },
  readingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 42,
    paddingVertical: 2,
  },
  checkboxBtn: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  readingOpenBtn: {
    flex: 1,
    minHeight: 38,
    justifyContent: "center",
    paddingVertical: 4,
  },
  readingOpenInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  readingText: {
    fontSize: 18,
    color: "#2F2014",
    ...parchmentSans(500),
    lineHeight: 24,
  },
  readingTextDone: {
    textDecorationLine: "line-through",
    color: "#6A5B49",
  },
  actionsWrap: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(113, 84, 53, 0.25)",
  },
  actions: {
    gap: 8,
  },
  actionBtn: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(116, 87, 57, 0.28)",
    backgroundColor: "rgba(255, 251, 242, 0.9)",
    paddingHorizontal: 12,
    paddingVertical: 13,
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
  },
  actionPrimary: {
    backgroundColor: LOGO_YELLOW,
    borderColor: "rgba(181, 124, 0, 0.9)",
  },
  actionText: {
    fontSize: 18,
    ...parchmentSans(600),
    color: "#2C1E12",
  },
  actionPrimaryText: {
    color: "#2C1B0F",
  },
  backHomeLinkWrap: {
    marginTop: 50,
    marginBottom: 30,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  backHomeLinkText: {
    fontSize: 17,
    ...parchmentSans(500),
    color: "#6A543B",
  },
  bottomNavRow: {
    marginTop: 4,
    marginBottom: 2,
    width: "100%",
    maxWidth: 360,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  chapterSideNavBtn: {
    marginTop: 50,
    marginBottom: 30,
    minWidth: 32,
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  chapterSideNavBtnDisabled: {
    opacity: 0.2,
  },
  chapterSideNavText: {
    fontSize: 26,
    lineHeight: 28,
    ...parchmentSans(500),
    color: "#6A543B",
  },
  celebrateMask: {
    flex: 1,
    backgroundColor: "rgba(15, 11, 8, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 22,
  },
  celebrateCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.border,
    backgroundColor: "rgba(255, 252, 245, 0.98)",
    paddingHorizontal: 16,
    paddingVertical: 18,
    alignItems: "center",
  },
  celebrateEmoji: { fontSize: 34 },
  sparkleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 6,
  },
  sparkle: {
    fontSize: 16,
  },
  celebrateTitle: {
    marginTop: 8,
    fontSize: 22,
    ...parchmentSans(600),
    color: c.ink,
    textAlign: "center",
  },
  celebrateBody: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 20,
    color: c.muted,
    textAlign: "center",
  },
  celebrateActions: {
    marginTop: 14,
    width: "100%",
    gap: 8,
  },
  celebrateCtaWrap: {
    borderRadius: 14,
    shadowColor: "#b17200",
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
  },
  pressed: { opacity: 0.88 },
});
