/** Longest-match first: English / abbreviated names → 66-book ids (`scripture-books`). */
export const ENGLISH_BOOK_ALIASES_SORTED: { alias: string; bookId: string }[] = [
  { alias: "1 Corinthians", bookId: "1CO" },
  { alias: "1Corinthians", bookId: "1CO" },
  { alias: "2 Corinthians", bookId: "2CO" },
  { alias: "2Corinthians", bookId: "2CO" },
  { alias: "1 Thessalonians", bookId: "1TH" },
  { alias: "1Thessalonians", bookId: "1TH" },
  { alias: "1 Thes", bookId: "1TH" },
  { alias: "2 Thessalonians", bookId: "2TH" },
  { alias: "2Thessalonians", bookId: "2TH" },
  { alias: "2 Thes", bookId: "2TH" },
  { alias: "1 Timothy", bookId: "1TI" },
  { alias: "1Timothy", bookId: "1TI" },
  { alias: "2 Timothy", bookId: "2TI" },
  { alias: "2Timothy", bookId: "2TI" },
  { alias: "1 Peter", bookId: "1PE" },
  { alias: "1Peter", bookId: "1PE" },
  { alias: "2 Peter", bookId: "2PE" },
  { alias: "2Peter", bookId: "2PE" },
  { alias: "1 John", bookId: "1JN" },
  { alias: "1John", bookId: "1JN" },
  { alias: "2 John", bookId: "2JN" },
  { alias: "2John", bookId: "2JN" },
  /** Upstream typo in some ESV-tagged JSON files. */
  { alias: "2Joh", bookId: "2JN" },
  { alias: "3 John", bookId: "3JN" },
  { alias: "3John", bookId: "3JN" },
  { alias: "3Joh", bookId: "3JN" },
  { alias: "1 Samuel", bookId: "1SA" },
  { alias: "1Samuel", bookId: "1SA" },
  { alias: "2 Samuel", bookId: "2SA" },
  { alias: "2Samuel", bookId: "2SA" },
  { alias: "1 Kings", bookId: "1KI" },
  { alias: "1Kings", bookId: "1KI" },
  { alias: "2 Kings", bookId: "2KI" },
  { alias: "2Kings", bookId: "2KI" },
  { alias: "1 Chronicles", bookId: "1CH" },
  { alias: "1Chronicles", bookId: "1CH" },
  { alias: "2 Chronicles", bookId: "2CH" },
  { alias: "2Chronicles", bookId: "2CH" },
  { alias: "Song of Solomon", bookId: "SNG" },
  { alias: "SongOfSongs", bookId: "SNG" },
  { alias: "Deuteronomy", bookId: "DEU" },
  { alias: "Lamentations", bookId: "LAM" },
  { alias: "Revelation", bookId: "REV" },
  { alias: "Philippians", bookId: "PHP" },
  { alias: "Colossians", bookId: "COL" },
  { alias: "Philemon", bookId: "PHM" },
  { alias: "Ephesians", bookId: "EPH" },
  { alias: "Galatians", bookId: "GAL" },
  { alias: "Hebrews", bookId: "HEB" },
  { alias: "Ecclesiastes", bookId: "ECC" },
  { alias: "Leviticus", bookId: "LEV" },
  { alias: "Numbers", bookId: "NUM" },
  { alias: "Joshua", bookId: "JOS" },
  { alias: "Judges", bookId: "JDG" },
  { alias: "Genesis", bookId: "GEN" },
  { alias: "Exodus", bookId: "EXO" },
  { alias: "Nehemiah", bookId: "NEH" },
  { alias: "Esther", bookId: "EST" },
  { alias: "Proverbs", bookId: "PRO" },
  { alias: "Zechariah", bookId: "ZEC" },
  { alias: "Jeremiah", bookId: "JER" },
  { alias: "Ezekiel", bookId: "EZK" },
  { alias: "Habakkuk", bookId: "HAB" },
  { alias: "Zephaniah", bookId: "ZEP" },
  { alias: "Obadiah", bookId: "OBA" },
  { alias: "Malachi", bookId: "MAL" },
  { alias: "Matthew", bookId: "MAT" },
  { alias: "Romans", bookId: "ROM" },
  { alias: "Acts", bookId: "ACT" },
  { alias: "James", bookId: "JAS" },
  { alias: "Jude", bookId: "JUD" },
  /** Short label used in some upstream tables; keep after `Judges` (longest match). */
  { alias: "Jud", bookId: "JUD" },
  { alias: "Jonah", bookId: "JON" },
  { alias: "Haggai", bookId: "HAG" },
  { alias: "Micah", bookId: "MIC" },
  { alias: "Nahum", bookId: "NAM" },
  { alias: "Isaiah", bookId: "ISA" },
  { alias: "Daniel", bookId: "DAN" },
  { alias: "Hosea", bookId: "HOS" },
  { alias: "Amos", bookId: "AMO" },
  { alias: "Ruth", bookId: "RUT" },
  { alias: "Job", bookId: "JOB" },
  { alias: "Psalms", bookId: "PSA" },
  { alias: "Psalm", bookId: "PSA" },
  { alias: "Titus", bookId: "TIT" },
  { alias: "Mark", bookId: "MRK" },
  { alias: "Luke", bookId: "LUK" },
  { alias: "John", bookId: "JHN" },
  { alias: "Joel", bookId: "JOL" },
  { alias: "Ezra", bookId: "EZR" },
].sort((a, b) => b.alias.length - a.alias.length);
