import type { HistoricalCreedBodyContent } from "./types";

export const chicagoHermeneuticsBody: HistoricalCreedBodyContent = {
  "bodyZh": [
    "芝加哥圣经解释宣言（1982）",
    "本宣言与1978年无误宣言同属国际圣经无误委员会（ICBI）成果，专注释经原则：在承认圣经无误的同时，说明如何正确理解并应用神话语。",
    "肯定与否认条文",
    "第 1 条\n我们确认：圣经的规范权威就是上帝自己的权威，并由基督——教会的主——所见证。\n我们否认：把基督的权威与圣经的权威分离，或彼此对立，是正当的。",
    "第 2 条\n我们确认：正如基督是神人合一的一位，圣经不可分割地是上帝的话，以人类语言表达。\n我们否认：圣经谦卑的人类形式意味着错谬，正如基督在降卑中的人性意味着罪一样。",
    "第 3 条\n我们确认：耶稣基督的位格与工作，是整本圣经的中心焦点。\n我们否认：任何拒绝或模糊圣经以基督为中心的解释方法，都是正确的。",
    "第 4 条\n我们确认：默示圣经的圣灵，今日仍借着圣经动工，使人对其信息产生信心。\n我们否认：圣灵从不教导任何人任何与圣经教导相违的事。",
    "第 5 条\n我们确认：圣灵使信徒能够领受并将圣经应用于生活。\n我们否认：未蒙圣灵重生的人，能在属灵上领悟圣经信息，而不倚赖圣灵。",
    "第 6 条\n我们确认：圣经以命题陈述表达上帝的真理；我们宣告圣经真理既是客观的，也是绝对的。我们进一步确认：陈述若如实代表事态，就是真的；若歪曲事实，就是错的。\n我们否认：虽然圣经能使人有得救的智慧，圣经真理却不应仅按此功能来定义。我们进一步否认，错误应定义为故意欺骗。",
    "第 7 条\n我们确认：每一圣经文本所表达的意义是单一、确定且固定的。\n我们否认：承认这单一意义，并不排除其应用的多样性。",
    "第 8 条\n我们确认：圣经包含适用于一切文化与处境的教导与诫命，也包含圣经自身表明仅适用于特定处境的诫命。\n我们否认：圣经中普遍与特殊诫命的区分，可由文化与处境因素决定。我们进一步否认，普遍诫命可被当作文化或处境相对化。",
    "第 9 条\n我们确认：「释经学」一词历史上指解经规则，可正当延伸为涵盖领悟圣经启示意义及其对我们生命影响的全过程。\n我们否认：圣经信息源自或受制于解释者的理解。因此我们否认，圣经作者与解释者的「视界」可以正当「融合」，以致文本向解释者传达的，最终不受圣经所表达意义的控制。",
    "第 10 条\n我们确认：圣经通过多种文学形式，以言语向我们传达上帝的真理。\n我们否认：人类语言的任何限制，使圣经不足以传达上帝的信息。",
    "第 11 条\n我们确认：圣经文本的翻译能够跨越一切时间与文化界限，传达关于上帝的知识。\n我们否认：圣经文本的意义如此系于其产生的文化，以致在其他文化中无法理解相同意义。",
    "第 12 条\n我们确认：在翻译圣经并在各文化语境中教导时，只应采用忠实于圣经教导内容的功能对等表达。\n我们否认：在跨文化沟通过程中，对文化差异不敏感、或歪曲圣经意义的方法，是正当的。",
    "第 13 条\n我们确认：认识圣经各部分的文学类别、形式与风格，对正确解经至关重要；因此我们重视文体批判作为圣经研究诸学科之一。\n我们否认：可将否定历史性的文体类别强加于自称纪实的圣经叙事。",
    "第 14 条\n我们确认：圣经对事件、论述与言论的记载，虽以多种合宜的文学形式呈现，却与历史事实相符。\n我们否认：圣经作者或其所纳入的传统，曾捏造经中记载的任何事件、论述或言论。",
    "第 15 条\n我们确认：必须按字面或正常意义解释圣经。字面意义即文法—历史意义，即作者所表达的意义。按字面意义解释，将顾及文本中一切修辞与文学形式。\n我们否认：任何将圣经意义归因于字面意义所不支持的解释进路，都是正当的。",
    "第 16 条\n我们确认：应当使用正当的批判技巧来确定正典文本及其意义。\n我们否认：任何圣经批判方法，可质疑作者所表达意义的真实性或完整性，或任何其他圣经教导。",
    "第 17 条\n我们确认：圣经具有统一、和谐与一致性，并宣告圣经是最好的自我解释者。\n我们否认：圣经可被解释为暗示一段经文更正或抵触另一段。我们否认，后来的圣经作者在引用或提及较早经文时，误解了那些经文。",
    "第 18 条\n我们确认：圣经对自身的解释总是正确的，从不偏离受默示文本的单一意义，而是阐明它。先知话语的单一意义包括——但不限于——先知对那些话语的理解，并必然涉及上帝在应验那些话语中所显明的意图。\n我们否认：圣经作者总是完全明白其自己话语的全部含义。",
    "第 19 条\n我们确认：解释者带入圣经的任何前理解，应与圣经教导和谐，并服受其纠正。\n我们否认：要求圣经迁就与之不一致的外来前理解，如自然主义、进化论、科学主义、世俗人文主义与相对主义。",
    "第 20 条\n我们确认：既然上帝是一切真理的作者，一切真理——圣经内外——都一致且连贯；圣经在触及自然、历史或任何事时都言说真理。我们进一步确认：在某些情况下，圣经外资料有助于澄清圣经所教导的，并促使纠正错误的解释。\n我们否认：圣经外观点可推翻圣经教导，或凌驾于圣经之上。",
    "第 21 条\n我们确认：特殊启示与一般启示的和谐，因此圣经教导与自然事实和谐。\n我们否认：任何真正的科学事实，与任何圣经经文的真正意义不一致。",
    "第 22 条\n我们确认：创世记1–11章是事实性的，正如本书其余部分一样。\n我们否认：创世记1–11章的教导是神话性的；关于地球历史或人类起源的科学假说，可用来推翻圣经关于创造的教导。",
    "第 23 条\n我们确认：圣经具有清晰性，尤其是关于从罪得救的信息。\n我们否认：圣经所有经文都同样清晰，或对救赎信息有同等分量。",
    "第 24 条\n我们确认：人理解圣经，并不倚赖圣经学者的专业知识。\n我们否认：人应忽视圣经学者技术性研究的成果。",
    "第 25 条\n我们确认：唯一足以传达神圣启示及其对生命正当应用的讲道，是忠实讲解圣经文本、视其为上帝话语的讲道。\n我们否认：传道人除圣经文本外，另有来自上帝的信息。"
  ],
  "bodyZhTw": [
    "芝加哥聖經解釋宣言（1982）",
    "本宣言與1978年無誤宣言同屬國際聖經無誤委員會（ICBI）成果，專注釋經原則：在承認聖經無誤的同時，說明如何正確理解並應用神話語。",
    "肯定與否認條文",
    "第 1 條\n我們確認：圣经的规范权威就是上帝自己的权威，并由基督——教会的主——所见证。\n我們否認：把基督的权威与圣经的权威分离，或彼此对立，是正当的。",
    "第 2 條\n我們確認：正如基督是神人合一的一位，圣经不可分割地是上帝的话，以人类语言表达。\n我們否認：圣经谦卑的人类形式意味着错谬，正如基督在降卑中的人性意味着罪一样。",
    "第 3 條\n我們確認：耶稣基督的位格与工作，是整本圣经的中心焦点。\n我們否認：任何拒绝或模糊圣经以基督为中心的解释方法，都是正确的。",
    "第 4 條\n我們確認：默示圣经的圣灵，今日仍借着圣经动工，使人对其信息产生信心。\n我們否認：圣灵从不教导任何人任何与圣经教导相违的事。",
    "第 5 條\n我們確認：圣灵使信徒能够领受并将圣经应用于生活。\n我們否認：未蒙圣灵重生的人，能在属灵上领悟圣经信息，而不倚赖圣灵。",
    "第 6 條\n我們確認：圣经以命题陈述表达上帝的真理；我們宣告圣经真理既是客观的，也是绝对的。我們进一步確認：陈述若如实代表事态，就是真的；若歪曲事实，就是错的。\n我們否認：虽然圣经能使人有得救的智慧，圣经真理却不应仅按此功能来定义。我們进一步否认，错误应定义为故意欺骗。",
    "第 7 條\n我們確認：每一圣经文本所表达的意义是单一、确定且固定的。\n我們否認：承认这单一意义，并不排除其应用的多样性。",
    "第 8 條\n我們確認：圣经包含适用于一切文化与处境的教导与诫命，也包含圣经自身表明仅适用于特定处境的诫命。\n我們否認：圣经中普遍与特殊诫命的区分，可由文化与处境因素决定。我們进一步否认，普遍诫命可被当作文化或处境相对化。",
    "第 9 條\n我們確認：「释经学」一词历史上指解经规则，可正当延伸为涵盖领悟圣经启示意义及其对我們生命影响的全过程。\n我們否認：圣经信息源自或受制于解释者的理解。因此我們否认，圣经作者与解释者的「视界」可以正当「融合」，以致文本向解释者传达的，最终不受圣经所表达意义的控制。",
    "第 10 條\n我們確認：圣经通过多种文学形式，以言语向我們传达上帝的真理。\n我們否認：人类语言的任何限制，使圣经不足以传达上帝的信息。",
    "第 11 條\n我們確認：圣经文本的翻译能够跨越一切时间与文化界限，传达关于上帝的知识。\n我們否認：圣经文本的意义如此系于其产生的文化，以致在其他文化中无法理解相同意义。",
    "第 12 條\n我們確認：在翻译圣经并在各文化语境中教导时，只应采用忠实于圣经教导内容的功能对等表达。\n我們否認：在跨文化沟通过程中，对文化差异不敏感、或歪曲圣经意义的方法，是正当的。",
    "第 13 條\n我們確認：认识圣经各部分的文学类别、形式与风格，对正确解经至关重要；因此我們重视文体批判作为圣经研究诸学科之一。\n我們否認：可将否定历史性的文体类别强加于自称纪实的圣经叙事。",
    "第 14 條\n我們確認：圣经对事件、论述与言论的记载，虽以多种合宜的文学形式呈现，却与历史事实相符。\n我們否認：圣经作者或其所纳入的传统，曾捏造经中记载的任何事件、论述或言论。",
    "第 15 條\n我們確認：必须按字面或正常意义解释圣经。字面意义即文法—历史意义，即作者所表达的意义。按字面意义解释，将顾及文本中一切修辞与文学形式。\n我們否認：任何将圣经意义归因于字面意义所不支持的解释进路，都是正当的。",
    "第 16 條\n我們確認：应当使用正当的批判技巧来确定正典文本及其意义。\n我們否認：任何圣经批判方法，可质疑作者所表达意义的真实性或完整性，或任何其他圣经教导。",
    "第 17 條\n我們確認：圣经具有统一、和谐与一致性，并宣告圣经是最好的自我解释者。\n我們否認：圣经可被解释为暗示一段经文更正或抵触另一段。我們否认，后来的圣经作者在引用或提及较早经文时，误解了那些经文。",
    "第 18 條\n我們確認：圣经对自身的解释总是正确的，从不偏离受默示文本的单一意义，而是阐明它。先知话语的单一意义包括——但不限于——先知对那些话语的理解，并必然涉及上帝在应验那些话语中所显明的意图。\n我們否認：圣经作者总是完全明白其自己话语的全部含义。",
    "第 19 條\n我們確認：解释者带入圣经的任何前理解，应与圣经教导和谐，并服受其纠正。\n我們否認：要求圣经迁就与之不一致的外来前理解，如自然主义、进化论、科学主义、世俗人文主义与相对主义。",
    "第 20 條\n我們確認：既然上帝是一切真理的作者，一切真理——圣经内外——都一致且连贯；圣经在触及自然、历史或任何事时都言说真理。我們进一步確認：在某些情况下，圣经外资料有助于澄清圣经所教导的，并促使纠正错误的解释。\n我們否認：圣经外观点可推翻圣经教导，或凌驾于圣经之上。",
    "第 21 條\n我們確認：特殊啟示與一般啟示的和諧，因此聖經教導與自然事實和諧。\n我們否認：任何真正的科學事實，與任何聖經經文的真正意義不一致。",
    "第 22 條\n我們確認：创世记1–11章是事实性的，正如本书其余部分一样。\n我們否認：创世记1–11章的教导是神话性的；关于地球历史或人类起源的科学假说，可用来推翻圣经关于创造的教导。",
    "第 23 條\n我們確認：圣经具有清晰性，尤其是关于从罪得救的信息。\n我們否認：圣经所有经文都同样清晰，或对救赎信息有同等分量。",
    "第 24 條\n我們確認：人理解圣经，并不倚赖圣经学者的专业知识。\n我們否認：人应忽视圣经学者技术性研究的成果。",
    "第 25 條\n我們確認：唯一足以传达神圣启示及其对生命正当应用的讲道，是忠实讲解圣经文本、视其为上帝话语的讲道。\n我們否認：传道人除圣经文本外，另有来自上帝的信息。"
  ],
  "bodyEn": [
    "Chicago Statement on Biblical Hermeneutics (1982)",
    "Companion to the 1978 Inerrancy Statement from the International Council on Biblical Inerrancy (ICBI), addressing principles for interpreting and applying Scripture faithfully.",
    "Articles of Affirmation and Denial",
    "Article 1\nWE AFFIRM that the normative authority of Holy Scripture is the authority of God Himself, and is attested by Jesus Christ, the Lord of the Church.\nWE DENY that the legitimacy of separating the authority of Christ from the authority of Scripture, or of opposing the one to the other.",
    "Article 2\nWE AFFIRM that as Christ is God and Man in One Person, so Scripture is, indivisibly, God's Word in human language.\nWE DENY that that the humble, human form of Scripture entails errancy any more than the humanity of Christ, even in His humiliation, entails sin.",
    "Article 3\nWE AFFIRM that the Person and work of Jesus Christ are the central focus of the entire Bible.\nWE DENY that that any method of interpretation which rejects or obscures the Christ-centeredness of Scripture is correct.",
    "Article 4\nWE AFFIRM that the Holy Spirit who inspired Scripture acts through it today to work faith in its message.\nWE DENY that that the Holy Spirit ever teaches to any one anything which is contrary to the teaching of Scripture.",
    "Article 5\nWE AFFIRM that the Holy Spirit enables believers to appropriate and apply Scripture to their lives.\nWE DENY that that the natural man is able to discern spiritually the biblical message apart from the Holy Spirit.",
    "Article 6\nWE AFFIRM that the Bible expresses God's truth in propositional statements, and we declare that biblical truth is both objective and absolute. We further affirm that a statement is true if it represents matters as they actually are, but is an error if it misrepresents the facts.\nWE DENY that that, while Scripture is able to make us wise unto salvation, biblical truth should be defined in terms of this function. We further deny that error should be defined as that which willfully deceives.",
    "Article 7\nWE AFFIRM that the meaning expressed in each biblical text is single, definite and fixed.\nWE DENY that that the recognition of this single meaning eliminates the variety of its application.",
    "Article 8\nWE AFFIRM that the Bible contains teachings and mandates which apply to all cultural and situational contexts and other mandates which the Bible itself shows apply only to particular situations.\nWE DENY that that the distinctions between the universal and particular mandates of Scripture can be determined by cultural and situational factors. We further deny that universal mandates may ever be treated as culturally or situationally relative.",
    "Article 9\nWE AFFIRM that the term hermeneutics, which historically signified the rules of exegesis, may properly be extended to cover all that is involved in the process of perceiving what the biblical revelation means and how it bears on our lives.\nWE DENY that that the message of Scripture derives from, or is dictated by, the interpreter's understanding. Thus we deny that the \"horizons\" of the biblical writer and the interpreter may rightly \"fuse\" in such a way that what the text communicates to the interpreter is not ultimately controlled by the expressed meaning of the Scripture.",
    "Article 10\nWE AFFIRM that Scripture communicates God's truth to us verbally through a wide variety of literary forms.\nWE DENY that that any of the limits of human language render Scripture inadequate to convey God's message.",
    "Article 11\nWE AFFIRM that translations of the text of Scripture can communicate knowledge of God across all temporal and cultural boundaries.\nWE DENY that that the meaning of biblical texts is so tied to the culture out of which they came that understanding of the same meaning in other cultures is impossible.",
    "Article 12\nWE AFFIRM that in the task of translating the Bible and teaching it in the context of each culture, only those functional equivalents which are faithful to the content of biblical teaching should be employed.\nWE DENY that the legitimacy of methods which either are insensitive to the demands of cross-cultural communication or distort biblical meaning in the process.",
    "Article 13\nWE AFFIRM that awareness of the literary categories, formal and stylistic, of the various parts of Scripture is essential for proper exegesis, and hence we value genre criticism as one of the many disciplines of biblical study.\nWE DENY that that generic categories which negate historicity may rightly be imposed on biblical narratives which present themselves as factual.",
    "Article 14\nWE AFFIRM that the biblical record of events, discourses and sayings, though presented in a variety of appropriate literary forms, corresponds to historical fact.\nWE DENY that that any event, discourse or saying reported in Scripture was invented by the biblical writers or by the traditions they incorporated.",
    "Article 15\nWE AFFIRM that the necessity of interpreting the Bible according to its literal, or normal, sense. The literal sense is the grammatical-historical sense, that is, the meaning which the writer expressed. Interpretation according to the literal sense will take account of all figures of speech and literary forms found in the text.\nWE DENY that the legitimacy of any approach to Scripture that attributes to it meaning which the literal sense does not support.",
    "Article 16\nWE AFFIRM that legitimate critical techniques should be used in determining the canonical text and its meaning.\nWE DENY that the legitimacy of allowing any method of biblical criticism to question the truth or integrity of the writer's expressed meaning, or of any other scriptural teaching.",
    "Article 17\nWE AFFIRM that the unity, harmony and consistency of Scripture and declare that it is its own best interpreter.\nWE DENY that that Scripture may be interpreted in such a way as to suggest that one passage corrects or militates against another. We deny that later writers of Scripture misinterpreted earlier passages of Scripture when quoting from or referring to them.",
    "Article 18\nWE AFFIRM that the Bible's own interpretation of itself is always correct, never deviating from, but rather elucidating, the single meaning of the inspired text. The single meaning of a prophet's words includes, but is not restricted to, the understanding of those words by the prophet and necessarily involves the intention of God evidenced in the fulfillment of those words.\nWE DENY that that the writers of Scripture always understood the full implications of their own words.",
    "Article 19\nWE AFFIRM that any preunderstandings which the interpreter brings to Scripture should be in harmony with scriptural teaching and subject to correction by it.\nWE DENY that that Scripture should be required to fit alien preunderstandings, inconsistent with itself, such as naturalism, evolutionism, scientism, secular humanism, and relativism.",
    "Article 20\nWE AFFIRM that since God is the author of all truth, all truths, biblical and extrabiblical, are consistent and cohere, and that the Bible speaks truth when it touches on matters pertaining to nature, history, or anything else. We further affirm that in some cases extra-biblical data have value for clarifying what Scripture teaches, and for prompting correction of faulty interpretations.\nWE DENY that that extrabiblical views ever disprove the teaching of Scripture or hold priority over it.",
    "Article 21\nWE AFFIRM that the harmony of special with general revelation and therefore of biblical teaching with the facts of nature.\nWE DENY that that any genuine scientific facts are inconsistent with the true meaning of any passage of Scripture.",
    "Article 22\nWE AFFIRM that that Genesis 1-11 is factual, as is the rest of the book.\nWE DENY that that the teachings of Genesis 1-11 are mythical and that scientific hypotheses about earth history or the origin of humanity may be invoked to overthrow what Scripture teaches about creation.",
    "Article 23\nWE AFFIRM that the clarity of Scripture and specifically of its message about salvation from sin.\nWE DENY that that all passages of Scripture are equally clear or have equal bearing on the message of redemption.",
    "Article 24\nWE AFFIRM that a person is not dependent for understanding of Scripture on the expertise of biblical scholars.\nWE DENY that that a person should ignore the fruits of the technical study of Scripture by biblical scholars.",
    "Article 25\nWE AFFIRM that the only type of preaching which sufficiently conveys the divine revelation and its proper application to life is that which faithfully expounds the text of Scripture as the Word of God.\nWE DENY that that the preacher has any message from God apart from the text of Scripture."
  ]
};
