import type { HistoricalCreedBodyContent } from "./types";

export const chicagoInerrancyBody: HistoricalCreedBodyContent = {
  "bodyZh": [
    "芝加哥圣经无误宣言（1978）",
    "简短声明",
    "一、上帝本身是真理，只说真理；祂默示圣经，借此向失丧的人类借着耶稣基督启示自己——祂是创造主、主、救赎主与审判者。圣经是上帝对自己的见证。",
    "二、圣经是上帝自己的话，由祂预备并照管、借着圣灵写成的；在一切所触及的事上，具有无误的神圣权威：其中所肯定的，当作上帝的教导而相信；其中所要求的，当作上帝的命令而顺从；其中所应许的，当作上帝的保证而倚靠。",
    "三、圣灵是圣经的神圣作者，既以内住的见证向我们确证圣经，也开启我们的心思明白其意义。",
    "四、圣经全然、逐字由上帝赐下，在其一切教导中毫无错误或瑕疵——无论论及上帝在创造中的作为、世界历史的事件、其在上帝默示下文学起源的见证，或论及个人生命中上帝拯救恩典的见证，都是如此。",
    "五、若这种全然的神圣无误在任何方面受到限制、忽视，或相对于与圣经自身相违的真理观而被相对化，圣经的权威就不可避免地受损；这样的退步对个人与教会都带来严重损失。",
    "肯定与否认条文",
    "第 1 条\n我们确认：圣经当作为上帝权威的话语而接受。\n我们否认：圣经的权威来自教会、传统或任何其他人本来源。",
    "第 2 条\n我们确认：圣经是上帝捆绑良心的最高书面准则；教会的权威次于圣经。\n我们否认：教会的信经、会议或宣言具有与圣经同等或更高的权威。",
    "第 3 条\n我们确认：写下来的话语整体都是上帝所赐的启示。\n我们否认：圣经仅仅是启示的见证，或只在相遇中才成为启示，或倚赖人的回应才有效。",
    "第 4 条\n我们确认：按祂形象造人的上帝，使用语言作为启示的手段。\n我们否认：人类语言因受造性的限制，不足以作为神圣启示的载体。我们进一步否认，罪对人类文化与语言的败坏挫败了上帝的默示工作。",
    "第 5 条\n我们确认：上帝在圣经中的启示是渐进的。\n我们否认：后来的启示——虽可应验先前的启示——从不更正或与之矛盾。我们进一步否认，自新约著作完成以后，还有任何规范性的启示。",
    "第 6 条\n我们确认：圣经整体及其各部分，直至原文的每一个字，都是神圣默示所赐。\n我们否认：不能正确地说整部受默示，却不包括部分；或只有部分受默示，而非整体。",
    "第 7 条\n我们确认：默示是上帝借着圣灵、通过人类作者，赐给我们祂话语的工作。圣经的起源是神圣的。神圣默示的方式对我们而言仍是奥秘。\n我们否认：默示可简化为人类的洞见，或任何种类的高度意识状态。",
    "第 8 条\n我们确认：上帝在默示工作中，运用祂所拣选并预备的作者各自独特的个性与文学风格。\n我们否认：上帝在使这些作者使用祂所拣选的字词时，并未压制他们的个性。",
    "第 9 条\n我们确认：默示虽不致全知，却保证圣经作者在受感动所说所写的一切事上，说出真实可信的话语。\n我们否认：这些作者因有限或堕落，必然或偶然地在上帝的话语中引入扭曲或虚假。",
    "第 10 条\n我们确认：严格说来，默示只适用于圣经的亲笔原文；在上帝护理下，可从现存抄本以极高准确度确定。我们进一步确认，抄本与译本在忠实代表原文的范围内，就是上帝的话语。\n我们否认：基督信仰的任何基本要素因亲笔原文的缺失而受影响。我们进一步否认，这种缺失使主张圣经无误无效或不相关。",
    "第 11 条\n我们确认：圣经既由神圣默示所赐，是无谬的；远非误导我们，在其所论及的一切事上都是真实可靠的。\n我们否认：圣经不可能同时在其断言上既无谬又有错。无谬与无误可以区分，但不可分离。",
    "第 12 条\n我们确认：圣经整体是无误的，摆脱一切虚假、欺诈或欺骗。\n我们否认：圣经的无谬与无误不限于属灵、宗教或救赎主题，而排除历史与科学领域的断言。我们进一步否认，可用关于地球历史的科学假说来推翻圣经关于创造与洪水的教导。",
    "第 13 条\n我们确认：使用「无误」作为指称圣经完全真实性的神学术语，是合宜的。\n我们否认：按照与圣经用法或目的相异的真假标准来评判圣经，是合宜的。我们进一步否认，缺乏现代技术精确性、语法或拼写不规则、对自然的观察性描述、虚假陈述的报导、夸张与约数的使用、材料的主题编排、平行记述中的不同选材，或自由引述等圣经现象，会否定无误。",
    "第 14 条\n我们确认：圣经具有统一性与内在一致性。\n我们否认：尚未解决的可疑错误或矛盾，并不损害圣经真理主张的有效性。",
    "第 15 条\n我们确认：无误教义植根于圣经关于默示的教导。\n我们否认：耶稣关于圣经的教导，可藉迁就论或对其人性的任何自然限制而被驳回。",
    "第 16 条\n我们确认：无误教义历来是教会信仰不可分割的一部分。\n我们否认：无误是宗教改革经院主义发明的教义，或是为回应负面高等批判而提出的反应性立场。",
    "第 17 条\n我们确认：圣灵为圣经作见证，使信徒确信上帝书面话语的真实性。\n我们否认：圣灵的这种见证脱离圣经、或违背圣经而单独运作。",
    "第 18 条\n我们确认：圣经文本当以文法—历史解经法解释，顾及文学形式与手法，且以经解经。\n我们否认：任何对文本的处理，或对文本背后来源的追寻，若导致相对化、去历史化、贬低其教导，或拒绝其作者主张，都是不正当的。",
    "第 19 条\n我们确认：承认圣经完全权威、无谬与无误，对正确理解全部基督教信仰至关重要。我们进一步确认，这样的承认应当导致越来越与基督形象一致。\n我们否认：这样的承认是得救所必需的。然而，我们进一步否认，拒绝无误不会带来严重后果——对个人与教会都是如此。"
  ],
  "bodyZhTw": [
    "芝加哥聖經無誤宣言（1978）",
    "簡短声明",
    "一、上帝本身是真理，只说真理；祂默示聖經，借此向失喪的人类借着耶稣基督启示自己——祂是創造主、主、救贖主与審判者。聖經是上帝对自己的見證。",
    "二、聖經是上帝自己的话，由祂预备并照管、借着圣灵写成的；在一切所触及的事上，具有無誤的神圣權威：其中所肯定的，当作上帝的教導而相信；其中所要求的，当作上帝的命令而顺从；其中所應許的，当作上帝的保證而倚靠。",
    "三、圣灵是聖經的神圣作者，既以内住的見證向我們确证聖經，也開啟我們的心思明白其意义。",
    "四、聖經全然、逐字由上帝赐下，在其一切教導中毫無错误或瑕疵——无论論及上帝在創造中的作为、世界歷史的事件、其在上帝默示下文學起源的見證，或論及个人生命中上帝拯救恩典的見證，都是如此。",
    "五、若这种全然的神圣無誤在任何方面受到限制、忽視，或相對于与聖經自身相违的真理觀而被相對化，聖經的權威就不可避免地受损；这样的退步对个人与教會都带来严重损失。",
    "肯定与否認條文",
    "第 1 條\n我們確認：圣经当作为上帝权威的话语而接受。\n我們否認：圣经的权威来自教会、传统或任何其他人本来源。",
    "第 2 條\n我們確認：圣经是上帝捆绑良心的最高书面准则；教会的权威次于圣经。\n我們否認：教会的信经、会议或宣言具有与圣经同等或更高的权威。",
    "第 3 條\n我們確認：写下来的话语整体都是上帝所赐的启示。\n我們否認：圣经仅仅是启示的见证，或只在相遇中才成为启示，或倚赖人的回应才有效。",
    "第 4 條\n我們確認：按祂形象造人的上帝，使用語言作為啟示的手段。\n我們否認：人類語言因受造性的限制，不足以作為神聖啟示的載體。我們進一步否認，罪對人類文化與語言的敗壞挫敗了上帝的默示工作。",
    "第 5 條\n我們確認：上帝在聖經中的啟示是漸進的。\n我們否認：後來的啟示——雖可應驗先前的啟示——從不更正或與之矛盾。我們進一步否認，自新約著作完成以後，還有任何規範性的啟示。",
    "第 6 條\n我們確認：聖經整體及其各部分，直至原文的每一個字，都是神聖默示所賜。\n我們否認：不能正確地說整部受默示，卻不包括部分；或只有部分受默示，而非整體。",
    "第 7 條\n我們確認：默示是上帝藉著聖靈、通過人類作者，賜給我們祂話語的工作。聖經的起源是神聖的。神聖默示的方式對我們而言仍是奧秘。\n我們否認：默示可簡化為人類的洞見，或任何種類的高度意識狀態。",
    "第 8 條\n我們確認：上帝在默示工作中，运用祂所拣选并预备的作者各自独特的个性与文学风格。\n我們否認：上帝在使这些作者使用祂所拣选的字词时，并未压制他们的个性。",
    "第 9 條\n我們確認：默示虽不致全知，却保证圣经作者在受感动所说所写的一切事上，说出真实可信的话语。\n我們否認：这些作者因有限或堕落，必然或偶然地在上帝的话语中引入扭曲或虚假。",
    "第 10 條\n我們確認：严格说来，默示只适用于圣经的亲笔原文；在上帝护理下，可从现存抄本以极高准确度确定。我們进一步確認，抄本与译本在忠实代表原文的范围内，就是上帝的话语。\n我們否認：基督信仰的任何基本要素因亲笔原文的缺失而受影响。我們进一步否认，这种缺失使主张圣经无误无效或不相关。",
    "第 11 條\n我們確認：圣经既由神圣默示所赐，是无谬的；远非误导我們，在其所论及的一切事上都是真实可靠的。\n我們否認：圣经不可能同时在其断言上既无谬又有错。无谬与无误可以区分，但不可分离。",
    "第 12 條\n我們確認：圣经整体是无误的，摆脱一切虚假、欺诈或欺骗。\n我們否認：圣经的无谬与无误不限于属灵、宗教或救赎主题，而排除历史与科学领域的断言。我們进一步否认，可用关于地球历史的科学假说来推翻圣经关于创造与洪水的教导。",
    "第 13 條\n我們確認：使用「无误」作为指称圣经完全真实性的神学术语，是合宜的。\n我們否認：按照与圣经用法或目的相异的真假标准来评判圣经，是合宜的。我們进一步否认，缺乏现代技术精确性、语法或拼写不规则、对自然的观察性描述、虚假陈述的报导、夸张与约数的使用、材料的主题编排、平行记述中的不同选材，或自由引述等圣经现象，会否定无误。",
    "第 14 條\n我們確認：圣经具有统一性与内在一致性。\n我們否認：尚未解决的可疑错误或矛盾，并不损害圣经真理主张的有效性。",
    "第 15 條\n我們確認：无误教义植根于圣经关于默示的教导。\n我們否認：耶稣关于圣经的教导，可藉迁就论或对其人性的任何自然限制而被驳回。",
    "第 16 條\n我們確認：无误教义历来是教会信仰不可分割的一部分。\n我們否認：无误是宗教改革经院主义发明的教义，或是为回应负面高等批判而提出的反应性立场。",
    "第 17 條\n我們確認：圣灵为圣经作见证，使信徒确信上帝书面话语的真实性。\n我們否認：圣灵的这种见证脱离圣经、或违背圣经而单独运作。",
    "第 18 條\n我們確認：圣经文本当以文法—历史解经法解释，顾及文学形式与手法，且以经解经。\n我們否認：任何对文本的处理，或对文本背后来源的追寻，若导致相对化、去历史化、贬低其教导，或拒绝其作者主张，都是不正当的。",
    "第 19 條\n我們確認：承认圣经完全权威、无谬与无误，对正确理解全部基督教信仰至关重要。我們进一步確認，这样的承认应当导致越来越与基督形象一致。\n我們否認：这样的承认是得救所必需的。然而，我們进一步否认，拒绝无误不会带来严重后果——对个人与教会都是如此。"
  ],
  "bodyEn": [
    "Chicago Statement on Biblical Inerrancy (1978)",
    "A Short Statement",
    "1. God, who is Himself Truth and speaks truth only, has inspired Holy Scripture in order thereby to reveal Himself to lost mankind through Jesus Christ as Creator and Lord, Redeemer and Judge. Holy Scripture is God's witness to Himself.",
    "2. Holy Scripture, being God's own Word, written by men prepared and superintended by His Spirit, is of infallible divine authority in all matters upon which it touches: it is to be believed, as God's instruction, in all that it affirms: obeyed, as God's command, in all that it requires; embraced, as God's pledge, in all that it promises.",
    "3. The Holy Spirit, Scripture's divine Author, both authenticates it to us by His inward witness and opens our minds to understand its meaning.",
    "4. Being wholly and verbally God-given, Scripture is without error or fault in all its teaching, no less in what it states about God's acts in creation, about the events of world history, and about its own literary origins under God, than in its witness to God's saving grace in individual lives.",
    "5. The authority of Scripture is inescapably impaired if this total divine inerrancy is in any way limited or disregarded, or made relative to a view of truth contrary to the Bible's own; and such lapses bring serious loss to both the individual and the Church.",
    "Articles of Affirmation and Denial",
    "Article 1\nWE AFFIRM that the Holy Scriptures are to be received as the authoritative Word of God.\nWE DENY that the Scriptures receive their authority from the Church, tradition, or any other human source.",
    "Article 2\nWE AFFIRM that the Scriptures are the supreme written norm by which God binds the conscience, and that the authority of the Church is subordinate to that of Scripture.\nWE DENY that Church creeds, councils, or declarations have authority greater than or equal to the authority of the Bible.",
    "Article 3\nWE AFFIRM that the written Word in its entirety is revelation given by God.\nWE DENY that the Bible is merely a witness to revelation, or only becomes revelation in encounter, or depends on the responses of men for its validity.",
    "Article 4\nWE AFFIRM that God who made mankind in His image has used language as a means of revelation.\nWE DENY that human language is so limited by our creatureliness that it is rendered inadequate as a vehicle for divine revelation. We further deny that the corruption of human culture and language through sin has thwarted God's work of inspiration.",
    "Article 5\nWE AFFIRM that God's revelation within the Holy Scriptures was progressive.\nWE DENY that later revelation, which may fulfill earlier revelation, ever corrects or contradicts it. We further deny that any normative revelation has been given since the completion of the New Testament writings.",
    "Article 6\nWE AFFIRM that the whole of Scripture and all its parts, down to the very words of the original, were given by divine inspiration.\nWE DENY that the inspiration of Scripture can rightly be affirmed of the whole without the parts, or of some parts but not the whole.",
    "Article 7\nWE AFFIRM that inspiration was the work in which God by His Spirit, through human writers, gave us His Word. The origin of Scripture is divine. The mode of divine inspiration remains largely a mystery to us.\nWE DENY that inspiration can be reduced to human insight, or to heightened states of consciousness of any kind.",
    "Article 8\nWE AFFIRM that God in His work of inspiration utilized the distinctive personalities and literary styles of the writers whom He had chosen and prepared.\nWE DENY that God, in causing these writers to use the very words that He chose, overrode their personalities.",
    "Article 9\nWE AFFIRM that inspiration, though not conferring omniscience, guaranteed true and trustworthy utterance on all matters of which the Biblical authors were moved to speak and write.\nWE DENY that the finitude or fallenness of these writers, by necessity or otherwise, introduced distortion or falsehood into God's Word.",
    "Article 10\nWE AFFIRM that inspiration, strictly speaking, applies only to the autographic text of Scripture, which in the providence of God can be ascertained from available manuscripts with great accuracy. We further affirm that copies and translations of Scripture are the Word of God to the extent that they faithfully represent the original.\nWE DENY that any essential element of the Christian faith is affected by the absence of the autographs. We further deny that this absence renders the assertion of Biblical inerrancy invalid or irrelevant.",
    "Article 11\nWE AFFIRM that Scripture, having been given by divine inspiration, is infallible, so that, far from misleading us, it is true and reliable in all the matters it addresses.\nWE DENY that it is possible for the Bible to be at the same time infallible and errant in its assertions. Infallibility and inerrancy may be distinguished, but not separated.",
    "Article 12\nWE AFFIRM that Scripture in its entirety is inerrant, being free from all falsehood, fraud, or deceit.\nWE DENY that Biblical infallibility and inerrancy are limited to spiritual, religious, or redemptive themes, exclusive of assertions in the fields of history and science. We further deny that scientific hypotheses about earth history may properly be used to overturn the teaching of Scripture on creation and the flood.",
    "Article 13\nWE AFFIRM that the propriety of using inerrancy as a theological term with reference to the complete truthfulness of Scripture.\nWE DENY that it is proper to evaluate Scripture according to standards of truth and error that are alien to its usage or purpose. We further deny that inerrancy is negated by Biblical phenomena such as a lack of modern technical precision, irregularities of grammar or spelling, observational descriptions of nature, the reporting of falsehoods, the use of hyperbole and round numbers, the topical arrangement of material, variant selections of material in parallel accounts, or the use of free citations.",
    "Article 14\nWE AFFIRM that the unity and internal consistency of Scripture.\nWE DENY that alleged errors and discrepancies that have not yet been resolved vitiate the truth claims of the Bible.",
    "Article 15\nWE AFFIRM that the doctrine of inerrancy is grounded in the teaching of the Bible about inspiration.\nWE DENY that Jesus' teaching about Scripture may be dismissed by appeals to accommodation or to any natural limitation of His humanity.",
    "Article 16\nWE AFFIRM that the doctrine of inerrancy has been integral to the Church's faith throughout its history.\nWE DENY that inerrancy is a doctrine invented by scholastic Protestantism, or is a reactionary position postulated in response to negative higher criticism.",
    "Article 17\nWE AFFIRM that the Holy Spirit bears witness to the Scriptures, assuring believers of the truthfulness of God's written Word.\nWE DENY that this witness of the Holy Spirit operates in isolation from or against Scripture.",
    "Article 18\nWE AFFIRM that the text of Scripture is to be interpreted by grammatico-historical exegesis, taking account of its literary forms and devices, and that Scripture is to interpret Scripture.\nWE DENY that the legitimacy of any treatment of the text or quest for sources lying behind it that leads to relativizing, dehistoricizing, or discounting its teaching, or rejecting its claims to authorship.",
    "Article 19\nWE AFFIRM that a confession of the full authority, infallibility, and inerrancy of Scripture is vital to a sound understanding of the whole of the Christian faith. We further affirm that such confession should lead to increasing conformity to the image of Christ.\nWE DENY that such confession is necessary for salvation. However, we further deny that inerrancy can be rejected without grave consequences, both to the individual and to the Church."
  ]
};
