import { isAutoGeneratedMusicTrackTitle } from "./track-naming";

const LEGACY_NUMERIC_TITLE_RE = /^\d{1,2}$/;

type LocalizedTitle = string | { "zh-CN"?: string; en?: string };

export type MusicCompanionTrackMergeInput = {
  id: string;
  title: LocalizedTitle;
  artist?: LocalizedTitle;
  analysisSrc?: string;
};

export type MusicCompanionStoreMergeInput = {
  audioTracks: MusicCompanionTrackMergeInput[];
};

function primaryTrackTitle(title: LocalizedTitle): string {
  if (typeof title === "string") return title.trim();
  return (title["zh-CN"] || title.en || "").trim();
}

export function isStaleMusicTrackDisplayTitle(title: string): boolean {
  const t = title.trim();
  if (!t) return true;
  if (LEGACY_NUMERIC_TITLE_RE.test(t)) return true;
  if (isAutoGeneratedMusicTrackTitle(t)) return true;
  return false;
}

/** 用随包曲库覆盖陈旧展示名；保留运行时 `src` / `analysisSrc` 等。 */
export function mergeMusicCompanionTrackDisplay<T extends MusicCompanionStoreMergeInput>(
  runtime: T,
  shipped: T,
): T {
  const shippedById = new Map(shipped.audioTracks.map((t) => [t.id, t]));
  return {
    ...runtime,
    audioTracks: runtime.audioTracks.map((t) => {
      const canon = shippedById.get(t.id);
      if (!canon) return t;
      if (!isStaleMusicTrackDisplayTitle(primaryTrackTitle(t.title))) return t;
      return {
        ...t,
        title: canon.title,
        artist: canon.artist ?? t.artist,
        analysisSrc: t.analysisSrc ?? canon.analysisSrc,
      };
    }),
  };
}
