import type { AudioTrack, MusicCompanionStore } from "./types";
import { isAutoGeneratedMusicTrackTitle } from "./track-naming";

/** 旧后台编号曲名（如 `03` / `04`），线上磁盘未同步时仍会出现 */
const LEGACY_NUMERIC_TITLE_RE = /^\d{1,2}$/;

function primaryTrackTitle(title: AudioTrack["title"]): string {
  if (typeof title === "string") return title.trim();
  return (title["zh-CN"] || title.en || "").trim();
}

/** API / 磁盘曲库标题是否应被构建时随包的展示元数据覆盖 */
export function isStaleMusicTrackDisplayTitle(title: string): boolean {
  const t = title.trim();
  if (!t) return true;
  if (LEGACY_NUMERIC_TITLE_RE.test(t)) return true;
  if (isAutoGeneratedMusicTrackTitle(t)) return true;
  return false;
}

/**
 * 用随仓库发布的曲库（`data/music-companion.json`）覆盖陈旧展示名。
 * 保留运行时曲库的 `src` / `analysisSrc` 等（Render 磁盘可能更新过路径）。
 */
export function mergeMusicCompanionTrackDisplay(
  runtime: MusicCompanionStore,
  shipped: MusicCompanionStore,
): MusicCompanionStore {
  const shippedById = new Map(shipped.audioTracks.map((t) => [t.id, t]));
  return {
    ...runtime,
    audioTracks: runtime.audioTracks.map((t) => {
      const canon = shippedById.get(t.id);
      if (!canon) return t;
      if (!isStaleMusicTrackDisplayTitle(primaryTrackTitle(t.title))) return t;
      return {
        ...t,
        title: canon.title,
        artist: canon.artist ?? t.artist,
        analysisSrc: t.analysisSrc ?? canon.analysisSrc,
      };
    }),
  };
}
