const MAX_TITLE_LEN = 200;

function pad2(n: number): string {
  return String(Math.max(0, Math.min(99, n))).padStart(2, "0");
}

function localYmd(d: Date): string {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}

/**
 * 上传音频默认标题：静默祷告主题英文名（按系列顺序自动代入）。
 */
export function nextDateNumberedMusicUploadTitle(
  existingTitles: readonly string[],
  now: Date = new Date(),
): string {
  void now;
  return nextWorshipSeriesTitle(existingTitles);
}

/**
 * 上传图片背景在后台列表中的名称：`背景 YYYY-MM-DD · 01`。
 */
export function nextDateNumberedImageUploadTitle(
  existingTitles: readonly string[],
  now: Date = new Date(),
): string {
  return nextDateNumberedLabel("背景", existingTitles, now);
}

/**
 * 上传自然页背景视频的列表标题：`自然影像 YYYY-MM-DD · 01`。
 */
export function nextDateNumberedNatureVideoTitle(
  existingTitles: readonly string[],
  now: Date = new Date(),
): string {
  return nextDateNumberedLabel("自然影像", existingTitles, now);
}

/** 自然页环境声素材默认标题：`环境声 YYYY-MM-DD · 01`。 */
export function nextDateNumberedNatureAmbientTitle(
  existingTitles: readonly string[],
  now: Date = new Date(),
): string {
  return nextDateNumberedLabel("环境声", existingTitles, now);
}


function nextDateNumberedLabel(
  prefix: string,
  existingTitles: readonly string[],
  now: Date,
): string {
  const ymd = localYmd(now);
  const escaped = prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`^${escaped} ${ymd.replace(/-/g, "\\-")} · (\\d{2})$`);
  let max = 0;
  for (const raw of existingTitles) {
    const t = (raw ?? "").trim();
    const m = t.match(re);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  const next = Math.min(99, max + 1);
  return `${prefix} ${ymd} · ${pad2(next)}`.slice(0, MAX_TITLE_LEN);
}

/** 上传自动生成的音乐标题（播放页不展示，避免机器感） */
const AUTO_MUSIC_TITLE_PATTERNS = [
  /^音乐 \d{4}-\d{2}-\d{2} · \d{2}$/,
  /^安静敬拜 · \d{2}$/,
];

export function isAutoGeneratedMusicTrackTitle(title: string): boolean {
  const normalized = title.trim();
  return AUTO_MUSIC_TITLE_PATTERNS.some((re) => re.test(normalized));
}

const UNIQUE_WORSHIP_TITLES = [
  "Silent Prayer",
  "Still in His Presence",
  "Quiet Heartbeat",
  "Grace in the Silence",
  "Resting Before the Lord",
  "Peace at His Feet",
  "Whispered Devotion",
  "Soft Light of Mercy",
  "Calm Beneath His Wings",
  "Morning Stillness",
  "Shelter of Grace",
  "Hushed Alleluia",
  "Gentle Faith",
  "Quiet Streams of Hope",
  "Near to Your Heart",
  "Sacred Quiet",
  "Tender Reverence",
  "Mercy at Dawn",
  "Breath of Prayer",
  "Still Waters Within",
  "Unhurried Worship",
  "Light in the Quiet",
  "Peaceful Surrender",
  "Holy Rest",
  "Waiting in Grace",
  "Calm of Heaven",
  "Prayer in the Morning Mist",
  "Silent Trust",
  "Lowly and Beloved",
  "Grace Upon Grace",
  "Quiet Flame",
  "Hope in the Stillness",
  "Gentle Hallelujah",
  "Rest for the Soul",
  "Softly Before You",
  "Nearness and Peace",
  "Stillness of Mercy",
  "Quiet Joy",
  "Sacred Breath",
  "Grace in Every Silence",
  "At Rest in Your Presence",
  "Peaceful Reverence",
  "Morning Prayer Light",
  "Humble Adoration",
  "Tranquil Praise",
  "Quiet Refuge",
  "Merciful Calm",
  "Still and Faithful",
  "Tender Grace Song",
  "Holy Quietude",
  "Gentle Presence",
  "Soft Prayer Echo",
  "Serene Devotion",
  "Comfort in Silence",
] as const;

function nextWorshipSeriesTitle(existingTitles: readonly string[]): string {
  const used = new Set(existingTitles.map((x) => (x ?? "").trim()).filter(Boolean));
  for (const candidate of UNIQUE_WORSHIP_TITLES) {
    if (!used.has(candidate)) return candidate.slice(0, MAX_TITLE_LEN);
  }
  for (let n = 0; n < 5000; n++) {
    const candidate = generatedWorshipTitleAt(n);
    if (!used.has(candidate)) return candidate.slice(0, MAX_TITLE_LEN);
  }
  return `Silent Prayer · ${Date.now()}`.slice(0, MAX_TITLE_LEN);
}

function generatedWorshipTitleAt(position: number): string {
  const OPENERS = [
    "Quiet",
    "Gentle",
    "Still",
    "Sacred",
    "Tender",
    "Holy",
    "Soft",
    "Calm",
    "Hushed",
    "Peaceful",
  ] as const;
  const CENTERS = [
    "Mercy",
    "Grace",
    "Prayer",
    "Faith",
    "Hope",
    "Presence",
    "Devotion",
    "Refuge",
    "Comfort",
    "Adoration",
  ] as const;
  const ENDINGS = [
    "at Dawn",
    "in Stillness",
    "Before the Lord",
    "for the Soul",
    "in the Morning",
    "of the Heart",
    "in Quiet Light",
    "at Rest",
    "in Silence",
    "in Peace",
  ] as const;

  const opener = OPENERS[position % OPENERS.length];
  const center = CENTERS[Math.floor(position / OPENERS.length) % CENTERS.length];
  const ending = ENDINGS[Math.floor(position / (OPENERS.length * CENTERS.length)) % ENDINGS.length];
  return `${opener} ${center} ${ending}`;
}

const AUDIO_EXT_RE = /\.(m4a|mp3|wav|flac|aac|ogg|opus|webm)$/i;

/** 播放主文案：自动编号标题或疑似原始文件名时不展示，统一为「音乐陪伴」。 */
export function playbackHeroTitle(title: string | null | undefined): string {
  const t = title?.trim() ?? "";
  if (!t) return "音乐陪伴";
  if (isAutoGeneratedMusicTrackTitle(t)) return "音乐陪伴";
  if (AUDIO_EXT_RE.test(t)) return "音乐陪伴";
  return t.slice(0, MAX_TITLE_LEN);
}

/**
 * 从上传文件名生成展示标题（去扩展名、整理空白）。
 */
export function titleFromUploadFileName(fileName: string): string {
  let base = fileName.trim() || "未命名音频";
  const slash = Math.max(base.lastIndexOf("/"), base.lastIndexOf("\\"));
  if (slash >= 0) base = base.slice(slash + 1);
  const lastDot = base.lastIndexOf(".");
  if (lastDot > 0) base = base.slice(0, lastDot);
  base = base.replace(/[_]+/g, " ").replace(/\s+/g, " ").trim();
  if (!base) base = "未命名音频";
  return base.slice(0, MAX_TITLE_LEN);
}

/** 曲库内唯一 id */
export function newTrackId(): string {
  return `track-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
}

/** 背景图条目 id（须符合 store id 规则） */
export function newBackgroundId(): string {
  return `bg-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
}
