const MAX_TITLE_LEN = 200;

function pad2(n: number): string {
  return String(Math.max(0, Math.min(99, n))).padStart(2, "0");
}

function localYmd(d: Date): string {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}

/**
 * 上传音频默认标题：`音乐 YYYY-MM-DD · 01`（同日自动递增，与曲库已有标题比较）。
 */
export function nextDateNumberedMusicUploadTitle(
  existingTitles: readonly string[],
  now: Date = new Date(),
): string {
  return nextDateNumberedLabel("音乐", existingTitles, now);
}

/**
 * 上传图片背景在后台列表中的名称：`背景 YYYY-MM-DD · 01`。
 */
export function nextDateNumberedImageUploadTitle(
  existingTitles: readonly string[],
  now: Date = new Date(),
): string {
  return nextDateNumberedLabel("背景", existingTitles, now);
}

/**
 * 上传自然页背景视频的列表标题：`自然影像 YYYY-MM-DD · 01`。
 */
export function nextDateNumberedNatureVideoTitle(
  existingTitles: readonly string[],
  now: Date = new Date(),
): string {
  return nextDateNumberedLabel("自然影像", existingTitles, now);
}

/** 自然页环境声素材默认标题：`环境声 YYYY-MM-DD · 01`。 */
export function nextDateNumberedNatureAmbientTitle(
  existingTitles: readonly string[],
  now: Date = new Date(),
): string {
  return nextDateNumberedLabel("环境声", existingTitles, now);
}


function nextDateNumberedLabel(
  prefix: string,
  existingTitles: readonly string[],
  now: Date,
): string {
  const ymd = localYmd(now);
  const escaped = prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`^${escaped} ${ymd.replace(/-/g, "\\-")} · (\\d{2})$`);
  let max = 0;
  for (const raw of existingTitles) {
    const t = (raw ?? "").trim();
    const m = t.match(re);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  const next = Math.min(99, max + 1);
  return `${prefix} ${ymd} · ${pad2(next)}`.slice(0, MAX_TITLE_LEN);
}

/** 上传自动生成的音乐标题（播放页不展示，避免机器感） */
const AUTO_MUSIC_TITLE_RE = /^音乐 \d{4}-\d{2}-\d{2} · \d{2}$/;

export function isAutoGeneratedMusicTrackTitle(title: string): boolean {
  return AUTO_MUSIC_TITLE_RE.test(title.trim());
}

const AUDIO_EXT_RE = /\.(m4a|mp3|wav|flac|aac|ogg|opus|webm)$/i;

/** 播放主文案：自动编号标题或疑似原始文件名时不展示，统一为「音乐陪伴」。 */
export function playbackHeroTitle(title: string | null | undefined): string {
  const t = title?.trim() ?? "";
  if (!t) return "音乐陪伴";
  if (isAutoGeneratedMusicTrackTitle(t)) return "音乐陪伴";
  if (AUDIO_EXT_RE.test(t)) return "音乐陪伴";
  return t.slice(0, MAX_TITLE_LEN);
}

/**
 * 从上传文件名生成展示标题（去扩展名、整理空白）。
 */
export function titleFromUploadFileName(fileName: string): string {
  let base = fileName.trim() || "未命名音频";
  const slash = Math.max(base.lastIndexOf("/"), base.lastIndexOf("\\"));
  if (slash >= 0) base = base.slice(slash + 1);
  const lastDot = base.lastIndexOf(".");
  if (lastDot > 0) base = base.slice(0, lastDot);
  base = base.replace(/[_]+/g, " ").replace(/\s+/g, " ").trim();
  if (!base) base = "未命名音频";
  return base.slice(0, MAX_TITLE_LEN);
}

/** 曲库内唯一 id */
export function newTrackId(): string {
  return `track-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
}

/** 背景图条目 id（须符合 store id 规则） */
export function newBackgroundId(): string {
  return `bg-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
}
