/** AUTO-GENERATED by scripts/generate-home-verse-chunk-registry.mjs — do not edit */
import type { HomePrayerChunkV1 } from "./types";

export const HOME_VERSE_POOL_SCOPE_ID = "explore-curated-700" as const;

export const HOME_VERSE_POOL_CHUNKS: Record<number, HomePrayerChunkV1> = {
  0: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-0.json"),
  1: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-1.json"),
  2: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-2.json"),
  3: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-3.json"),
  4: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-4.json"),
  5: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-5.json"),
  6: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-6.json"),
  7: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-7.json"),
  8: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-8.json"),
  9: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-9.json"),
  10: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-10.json"),
  11: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-11.json"),
  12: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-12.json"),
  13: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-13.json"),
  14: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-14.json"),
  15: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-15.json"),
  16: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-16.json"),
  17: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-17.json"),
  18: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-18.json"),
  19: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-19.json"),
  20: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-20.json"),
  21: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-21.json"),
  22: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-22.json"),
  23: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-23.json"),
  24: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-24.json"),
  25: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-25.json"),
  26: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-26.json"),
  27: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-27.json"),
  28: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-28.json"),
  29: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-29.json"),
  30: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-30.json"),
  31: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-31.json"),
  32: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-32.json"),
  33: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-33.json"),
  34: require("../../../assets/content/home-prayer-pools/explore-curated-700/chunk-34.json"),
};

