import { StyleSheet } from "react-native";
import { parchmentSans } from "../fonts/parchmentType";

export const natureHomeSettingsPanelStyles = StyleSheet.create({
  overlayRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 80,
  },
  backdrop: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "flex-start",
  },
  sheet: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#c9a875",
    backgroundColor: "transparent",
  },
  sheetBody: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 12,
  },
  translationSection: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    width: "100%",
    paddingTop: 0,
  },
  translationIcon: {
    width: 22,
    paddingTop: 6,
    alignItems: "center",
  },
  translationBody: {
    flex: 1,
    minWidth: 0,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  rowAlignTop: {
    alignItems: "flex-start",
  },
  rowIcon: {
    width: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  rowBody: {
    flex: 1,
    minWidth: 0,
  },
  segment: {
    flexDirection: "row",
    backgroundColor: "transparent",
    borderRadius: 7,
    padding: 2,
  },
  segBtn: {
    flex: 1,
    minHeight: 30,
    borderRadius: 5,
    backgroundColor: "rgba(255, 248, 235, 0.52)",
    alignItems: "center",
    justifyContent: "center",
  },
  segBtnOn: {
    backgroundColor: "rgba(255, 177, 1, 0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255, 177, 1, 0.74)",
  },
  scaleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  scaleBtn: {
    flex: 1,
    minHeight: 30,
    borderRadius: 5,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#c9a875",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 248, 235, 0.52)",
  },
  scaleBtnDisabled: { opacity: 0.35 },
  scaleBtnDefaultOn: {
    backgroundColor: "rgba(255, 177, 1, 0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255, 177, 1, 0.74)",
  },
  scaleSuperText: {
    fontSize: 18,
    ...parchmentSans(700),
    color: "#4a3425",
    letterSpacing: 0.1,
  },
  scaleDefaultText: {
    fontSize: 15,
    lineHeight: 17,
    ...parchmentSans(600),
    color: "#4a3425",
    letterSpacing: 0.05,
  },
  scaleOpText: {
    fontSize: 20,
    lineHeight: 20,
    ...parchmentSans(600),
    color: "#4a3425",
  },
  rotationChoicesWrap: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 6,
  },
  rotationChoicesRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rotationLabel: {
    width: 28,
    fontSize: 12,
    lineHeight: 16,
    ...parchmentSans(600),
    color: "#5b4330",
  },
  rotationChoice: {
    minHeight: 30,
    minWidth: 52,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#c9a875",
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 248, 235, 0.52)",
  },
  rotationChoiceOn: {
    backgroundColor: "rgba(255, 177, 1, 0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255, 177, 1, 0.74)",
  },
  rotationChoiceText: {
    fontSize: 12,
    lineHeight: 15,
    ...parchmentSans(600),
    color: "#4a3425",
    fontVariant: ["tabular-nums"],
  },
  rotationValueWrap: {
    flex: 1.4,
    minHeight: 30,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 248, 235, 0.52)",
    paddingHorizontal: 6,
  },
  rotationValueText: {
    fontSize: 11,
    ...parchmentSans(600),
    fontVariant: ["tabular-nums"],
    color: "#5b4330",
  },
  voiceScroll: {
    width: "100%",
  },
  voiceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingRight: 6,
  },
  voiceChip: {
    borderRadius: 7,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#c9a875",
    backgroundColor: "rgba(255, 248, 235, 0.52)",
    paddingHorizontal: 9,
    minHeight: 30,
    minWidth: 72,
    alignItems: "center",
    justifyContent: "center",
  },
  voiceChipOn: {
    backgroundColor: "#d2a85c",
    borderColor: "#b8893f",
  },
  voiceAddChip: {
    minWidth: 32,
    width: 32,
    paddingHorizontal: 0,
  },
  voiceChipText: {
    fontSize: 12,
    lineHeight: 15,
    ...parchmentSans(500),
    color: "#6b513b",
  },
  voiceChipTextOn: {
    ...parchmentSans(600),
    color: "#3f2b1d",
  },
  voiceChipInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  voiceGenderText: {
    fontSize: 12,
    lineHeight: 14,
    ...parchmentSans(700),
    color: "#6b513b",
  },
  voiceGenderTextOn: {
    color: "#3f2b1d",
  },
  voiceHint: {
    fontSize: 12,
    lineHeight: 16,
    color: "#765b42",
    ...parchmentSans(500),
  },
  ttsSliderWrap: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
    width: "100%",
  },
  ttsSliderCell: {
    flex: 1,
    minWidth: 0,
  },
  ttsSliderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    width: "auto",
  },
  ttsSliderIcon: {
    width: 18,
    alignItems: "center",
  },
  ttsSlider: {
    flex: 1,
    height: 30,
  },
});
