/** AUTO-GENERATED by scripts/generate-home-verse-chunk-registry.mjs — do not edit */
import type { HomePrayerChunkV1, HomePrayerManifestV1 } from "@/lib/home-prayer-pools/types";

export const HOME_PRAYER_POOL_MANIFEST = require("../../public/data/home-prayer-pools/explore-curated-700/manifest.json") as HomePrayerManifestV1;

export const HOME_PRAYER_POOL_SCOPE_ID = "explore-curated-700" as const;

export const HOME_PRAYER_POOL_CHUNKS: Record<number, HomePrayerChunkV1> = {
  0: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-0.json") as HomePrayerChunkV1,
  1: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-1.json") as HomePrayerChunkV1,
  2: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-2.json") as HomePrayerChunkV1,
  3: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-3.json") as HomePrayerChunkV1,
  4: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-4.json") as HomePrayerChunkV1,
  5: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-5.json") as HomePrayerChunkV1,
  6: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-6.json") as HomePrayerChunkV1,
  7: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-7.json") as HomePrayerChunkV1,
  8: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-8.json") as HomePrayerChunkV1,
  9: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-9.json") as HomePrayerChunkV1,
  10: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-10.json") as HomePrayerChunkV1,
  11: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-11.json") as HomePrayerChunkV1,
  12: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-12.json") as HomePrayerChunkV1,
  13: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-13.json") as HomePrayerChunkV1,
  14: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-14.json") as HomePrayerChunkV1,
  15: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-15.json") as HomePrayerChunkV1,
  16: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-16.json") as HomePrayerChunkV1,
  17: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-17.json") as HomePrayerChunkV1,
  18: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-18.json") as HomePrayerChunkV1,
  19: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-19.json") as HomePrayerChunkV1,
  20: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-20.json") as HomePrayerChunkV1,
  21: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-21.json") as HomePrayerChunkV1,
  22: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-22.json") as HomePrayerChunkV1,
  23: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-23.json") as HomePrayerChunkV1,
  24: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-24.json") as HomePrayerChunkV1,
  25: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-25.json") as HomePrayerChunkV1,
  26: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-26.json") as HomePrayerChunkV1,
  27: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-27.json") as HomePrayerChunkV1,
  28: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-28.json") as HomePrayerChunkV1,
  29: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-29.json") as HomePrayerChunkV1,
  30: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-30.json") as HomePrayerChunkV1,
  31: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-31.json") as HomePrayerChunkV1,
  32: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-32.json") as HomePrayerChunkV1,
  33: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-33.json") as HomePrayerChunkV1,
  34: require("../../public/data/home-prayer-pools/explore-curated-700/chunk-34.json") as HomePrayerChunkV1,
};

