/** AUTO-GENERATED by scripts/generate-home-verse-pool-menu-counts.mjs — do not edit */

export type HomeVersePoolMenuCounts = {
  curated700: number;
  repeatGe5All: number;
  repeatGe5Old: number;
  repeatGe5New: number;
  books: Record<string, number>;
};

export const HOME_VERSE_POOL_MENU_COUNTS: HomeVersePoolMenuCounts = 
{
  "curated700": 700,
  "repeatGe5All": 4291,
  "repeatGe5Old": 2095,
  "repeatGe5New": 2196,
  "books": {
    "GEN": 39,
    "EXO": 56,
    "LEV": 17,
    "NUM": 3,
    "DEU": 70,
    "JOS": 4,
    "1SA": 10,
    "2SA": 7,
    "1KI": 9,
    "2KI": 1,
    "1CH": 18,
    "2CH": 14,
    "EZR": 1,
    "NEH": 3,
    "JOB": 34,
    "PSA": 968,
    "PRO": 445,
    "ECC": 39,
    "SNG": 17,
    "ISA": 220,
    "JER": 35,
    "LAM": 10,
    "EZK": 14,
    "DAN": 14,
    "HOS": 2,
    "JOL": 4,
    "AMO": 2,
    "JON": 3,
    "MIC": 10,
    "NAM": 2,
    "HAB": 4,
    "ZEP": 2,
    "ZEC": 12,
    "MAL": 6,
    "MAT": 334,
    "MRK": 43,
    "LUK": 193,
    "JHN": 123,
    "ACT": 99,
    "ROM": 207,
    "1CO": 170,
    "2CO": 83,
    "GAL": 55,
    "EPH": 112,
    "PHP": 56,
    "COL": 62,
    "1TH": 47,
    "2TH": 21,
    "1TI": 63,
    "2TI": 40,
    "TIT": 19,
    "HEB": 117,
    "JAS": 77,
    "1PE": 75,
    "2PE": 31,
    "1JN": 76,
    "2JN": 1,
    "3JN": 2,
    "JUD": 7,
    "REV": 83
  }
}
;

