/** AUTO-GENERATED by scripts/generate-home-verse-pool-menu-counts.mjs — do not edit */

export type HomeVersePoolMenuCounts = {
  curated700: number;
  repeatGe5All: number;
  repeatGe5Old: number;
  repeatGe5New: number;
  books: Record<string, number>;
};

export const HOME_VERSE_POOL_MENU_COUNTS: HomeVersePoolMenuCounts = 
{
  "curated700": 700,
  "repeatGe5All": 4242,
  "repeatGe5Old": 2076,
  "repeatGe5New": 2166,
  "books": {
    "GEN": 39,
    "EXO": 52,
    "JHN": 121,
    "REV": 82,
    "PSA": 966,
    "ACT": 99,
    "LEV": 14,
    "JOB": 34,
    "NUM": 3,
    "DEU": 68,
    "MAT": 328,
    "PRO": 439,
    "ECC": 39,
    "SNG": 16,
    "ISA": 219,
    "ROM": 204,
    "2CH": 14,
    "JOS": 4,
    "1SA": 10,
    "2SA": 7,
    "JER": 35,
    "EZR": 1,
    "NEH": 3,
    "MRK": 42,
    "1KI": 9,
    "2KI": 1,
    "1CH": 18,
    "LUK": 191,
    "LAM": 10,
    "1CO": 167,
    "2CO": 82,
    "EZK": 14,
    "DAN": 14,
    "GAL": 54,
    "EPH": 110,
    "HOS": 2,
    "JOL": 4,
    "AMO": 2,
    "JON": 3,
    "MIC": 10,
    "PHP": 56,
    "COL": 62,
    "NAM": 2,
    "HAB": 4,
    "ZEP": 2,
    "ZEC": 12,
    "1TH": 47,
    "2TH": 19,
    "1TI": 61,
    "2TI": 40,
    "MAL": 6,
    "TIT": 18,
    "HEB": 115,
    "JAS": 77,
    "1PE": 74,
    "2PE": 31,
    "1JN": 76,
    "2JN": 1,
    "3JN": 2,
    "JUD": 7
  }
}
;

