/**
 * OpenBible 英文主题 → 简短中文（后台阅读用；未覆盖项见 `openbible-topic-zh.json`）。
 */
export function normalizeOpenbibleTopicKey(topic: string): string {
  return topic.trim().replace(/\s+/g, " ").toLowerCase();
}

/** 拆词翻译：仅当每个词都有对应译法时才拼接 */
export const OPENBIBLE_TOPIC_ZH_WORD_PARTS: Record<string, string> = Object.fromEntries(
  (
    [
      ["a", ""],
      ["an", ""],
      ["the", ""],
      ["and", "与"],
      ["or", "或"],
      ["of", "之"],
      ["in", "于"],
      ["to", "向"],
      ["for", "为"],
      ["with", "与"],
      ["without", "无"],
      ["being", "处于"],
      ["your", "你的"],
      ["my", "我的"],
      ["our", "我们的"],
      ["god", "神"],
      ["gods", "神"],
      ["jesus", "耶稣"],
      ["christ", "基督"],
      ["christian", "基督徒"],
      ["church", "教会"],
      ["bible", "圣经"],
      ["marriage", "婚姻"],
      ["married", "已婚"],
      ["divorce", "离婚"],
      ["wedding", "婚礼"],
      ["husband", "丈夫"],
      ["wife", "妻子"],
      ["spouse", "配偶"],
      ["child", "孩子"],
      ["children", "儿女"],
      ["parent", "父母"],
      ["parents", "父母"],
      ["family", "家庭"],
      ["love", "爱"],
      ["faith", "信心"],
      ["hope", "盼望"],
      ["peace", "平安"],
      ["joy", "喜乐"],
      ["fear", "惧怕"],
      ["anxiety", "焦虑"],
      ["worry", "忧虑"],
      ["anger", "愤怒"],
      ["forgiveness", "饶恕"],
      ["forgive", "饶恕"],
      ["healing", "医治"],
      ["prayer", "祷告"],
      ["worship", "敬拜"],
      ["salvation", "救恩"],
      ["sin", "罪"],
      ["evil", "恶"],
      ["death", "死亡"],
      ["life", "生命"],
      ["work", "工作"],
      ["money", "金钱"],
      ["debt", "债务"],
      ["poor", "贫穷"],
      ["rich", "富有"],
      ["greed", "贪婪"],
      ["lust", "情欲"],
      ["sex", "性"],
      ["adultery", "奸淫"],
      ["abuse", "虐待"],
      ["violence", "暴力"],
      ["alcohol", "酒精"],
      ["drugs", "药物"],
      ["smoking", "吸烟"],
      ["addiction", "成瘾"],
      ["addictions", "成瘾"],
      ["depression", "抑郁"],
      ["grief", "哀伤"],
      ["comfort", "安慰"],
      ["loneliness", "孤独"],
      ["patience", "忍耐"],
      ["humility", "谦卑"],
      ["pride", "骄傲"],
      ["obedience", "顺服"],
      ["trust", "信靠"],
      ["doubt", "疑惑"],
      ["wisdom", "智慧"],
      ["truth", "真理"],
      ["lies", "谎言"],
      ["lying", "说谎"],
      ["gossip", "闲话"],
      ["mercy", "怜悯"],
      ["grace", "恩典"],
      ["holy", "圣洁"],
      ["holiness", "圣洁"],
      ["spirit", "灵"],
      ["body", "身体"],
      ["mind", "心思"],
      ["heart", "心"],
      ["soul", "灵魂"],
      ["heaven", "天堂"],
      ["hell", "地狱"],
      ["angels", "天使"],
      ["demons", "邪灵"],
      ["satan", "撒但"],
      ["devil", "魔鬼"],
      ["end", "末日"],
      ["times", "时期"],
      ["second", "再"],
      ["coming", "来临"],
      ["resurrection", "复活"],
      ["baptism", "洗礼"],
      ["communion", "圣餐"],
      ["tithe", "十分之一"],
      ["offering", "奉献"],
      ["pastor", "牧师"],
      ["elders", "长老"],
      ["deacons", "执事"],
      ["women", "妇女"],
      ["men", "男人"],
      ["man", "男人"],
      ["woman", "女人"],
      ["young", "年轻"],
      ["old", "年长"],
      ["adult", "成年"],
      ["dating", "约会"],
      ["homosexuality", "同性恋"],
      ["abortion", "堕胎"],
      ["suicide", "自杀"],
      ["war", "战争"],
      ["government", "政府"],
      ["politics", "政治"],
      ["justice", "公义"],
      ["poverty", "贫穷"],
      ["wealth", "财富"],
      ["stewardship", "管家"],
      ["fasting", "禁食"],
      ["suffering", "苦难"],
      ["persecution", "逼迫"],
      ["missions", "宣教"],
      ["evangelism", "传福音"],
      ["discipleship", "门徒训练"],
      ["sabbath", "安息日"],
      ["idols", "偶像"],
      ["witchcraft", "巫术"],
      ["astrology", "占星"],
      ["dreams", "梦"],
      ["sleep", "睡眠"],
      ["food", "食物"],
      ["health", "健康"],
      ["disease", "疾病"],
      ["cancer", "癌症"],
      ["mental", "心理"],
      ["illness", "疾病"],
      ["repentance", "悔改"],
      ["sanctification", "成圣"],
      ["temptation", "试探"],
      ["trials", "试炼"],
      ["kindness", "恩慈"],
      ["jealousy", "嫉妒"],
      ["envy", "嫉妒"],
      ["bitterness", "苦毒"],
      ["judgment", "审判"],
      ["gospel", "福音"],
      ["unity", "合一"],
      ["giving", "施舍"],
      ["thanksgiving", "感恩"],
      ["praise", "赞美"],
      ["rest", "安息"],
      ["time", "时间"],
      ["quiet", "安静"],
      ["silence", "静默"],
      ["reading", "阅读"],
      ["study", "学习"],
      ["helping", "帮助"],
      ["serving", "服事"],
      ["poor", "贫穷"],
      ["rich", "富有"],
      ["sexual", "性方面"],
      ["physical", "身体"],
      ["emotional", "情感"],
      ["mental", "心理"],
      ["healthy", "健康"],
      ["bad", "不好"],
      ["good", "好"],
      ["living", "生活"],
      ["going", "去"],
      ["getting", "得到"],
      ["taking", "拿取"],
      ["making", "做"],
      ["doing", "做"],
      ["being", "作为"],
      ["having", "拥有"],
      ["keeping", "持守"],
      ["breaking", "违背"],
      ["speaking", "说话"],
      ["hearing", "听见"],
      ["seeing", "看见"],
      ["knowing", "知道"],
      ["believing", "相信"],
      ["waiting", "等候"],
      ["walking", "行走"],
      ["standing", "站立"],
      ["falling", "跌倒"],
      ["rising", "起来"],
      ["calling", "呼召"],
      ["named", "名为"],
      ["spiritual", "属灵"],
      ["holy", "圣洁"],
      ["word", "话语"],
      ["will", "旨意"],
      ["kingdom", "国度"],
      ["earth", "地"],
      ["world", "世界"],
      ["nations", "列国"],
      ["israel", "以色列"],
      ["jerusalem", "耶路撒冷"],
      ["temple", "圣殿"],
      ["law", "律法"],
      ["covenant", "约"],
      ["promise", "应许"],
      ["blessing", "祝福"],
      ["curse", "咒诅"],
      ["commandments", "诫命"],
      ["sinners", "罪人"],
      ["saints", "圣徒"],
      ["believers", "信徒"],
      ["disciples", "门徒"],
      ["apostles", "使徒"],
      ["prophets", "先知"],
      ["priests", "祭司"],
      ["kings", "君王"],
      ["servants", "仆人"],
      ["masters", "主人"],
      ["slaves", "奴仆"],
      ["workers", "工人"],
      ["employers", "雇主"],
      ["employees", "雇员"],
      ["money", "金钱"],
      ["taxes", "税"],
      ["debts", "债"],
      ["loans", "借贷"],
      ["interest", "利息"],
      ["gambling", "赌博"],
      ["games", "游戏"],
      ["music", "音乐"],
      ["songs", "诗歌"],
      ["dance", "舞蹈"],
      ["art", "艺术"],
      ["science", "科学"],
      ["history", "历史"],
      ["future", "未来"],
      ["past", "过去"],
      ["present", "现在"],
      ["today", "今天"],
      ["tomorrow", "明天"],
      ["eternity", "永恒"],
    ] as [string, string][]
  ).filter(([k], i, arr) => arr.findIndex(([x]) => x === k) === i),
);

const HANDBOOK_ENTRIES: [string, string][] = [
  ["anxiety", "焦虑"],
  ["anxiety and depression", "焦虑与抑郁"],
  ["comfort", "安慰"],
  ["comforting", "安慰人"],
  ["comfort the dying", "安慰临终者"],
  ["encourage", "鼓励"],
  ["encouragement", "鼓励"],
  ["encouragement to others", "鼓励他人"],
  ["grief", "哀伤"],
  ["hope", "盼望"],
  ["peace", "平安"],
  ["worry", "忧虑"],
  ["worries", "忧虑"],
  ["worry and anxiety", "忧虑与焦虑"],
  ["worry and stress", "忧虑与压力"],
  ["loneliness", "孤独"],
  ["depression", "抑郁"],
  ["anger", "愤怒"],
  ["anger and forgiveness", "愤怒与饶恕"],
  ["forgiveness", "饶恕"],
  ["forgiving yourself", "饶恕自己"],
  ["faith", "信心"],
  ["love", "爱"],
  ["prayer", "祷告"],
  ["worship", "敬拜"],
  ["marriage", "婚姻"],
  ["a healthy marriage", "健康婚姻"],
  ["a man", "男人"],
  ["a man working", "工作与男人"],
  ["a mans character", "人的品格"],
  ["a man's character", "人的品格"],
  ["a mans reputation", "人的名声"],
  ["a man's reputation", "人的名声"],
  ["a new creation", "新造的人"],
  ["a tenth", "十分之一"],
  ["13th generation", "第十三代"],
  ["christian marriage", "基督徒婚姻"],
  ["young marriage", "早婚"],
  ["2nd marriage", "再婚"],
  ["divorce", "离婚"],
  ["marriage separation", "分居"],
  ["abuse from a spouse", "配偶虐待"],
  ["abusive marriages", "虐待性婚姻"],
  ["adultery", "奸淫"],
  ["parenting", "养育子女"],
  ["adult children", "成年子女"],
  ["bad children", "悖逆的儿女"],
  ["taking care of children", "照顾孩童"],
  ["child training", "教养孩童"],
  ["adoption", "收养"],
  ["widows", "寡妇"],
  ["orphans", "孤儿"],
  ["work", "工作"],
  ["hard work", "辛勤劳作"],
  ["work ethic", "工作伦理"],
  ["money", "金钱"],
  ["getting out of debt", "脱离债务"],
  ["being poor", "贫穷"],
  ["healing", "医治"],
  ["healing prayer", "医治祷告"],
  ["salvation", "救恩"],
  ["eternal salvation", "永生的救恩"],
  ["born again", "重生"],
  ["sin", "罪"],
  ["10 commandments", "十诫"],
  ["the ten commandments", "十诫"],
  ["commandments", "诫命"],
  ["bible study", "查经"],
  ["reading the bible", "阅读圣经"],
  ["memorizing scripture", "背诵经文"],
  ["quiet time", "灵修安静时间"],
  ["quiet", "安静"],
  ["calm", "平静"],
  ["silence", "静默"],
  ["speaking gods word", "传讲神的话"],
  ["the holy spirit", "圣灵"],
  ["holy spirit", "圣灵"],
  ["trinity", "三位一体"],
  ["second coming", "第二次降临"],
  ["end times", "末世"],
  ["what happens after death", "死后如何"],
  ["death", "死亡"],
  ["suffering", "苦难"],
  ["persecution", "逼迫"],
  ["islam", "伊斯兰教"],
  ["mixing religion and politics", "宗教与政治混杂"],
  ["politics and religion", "政治与宗教"],
  ["alcohol abuse", "酗酒"],
  ["social drinking", "社交饮酒"],
  ["underage drinking", "未成年饮酒"],
  ["marijuana", "大麻"],
  ["cannabis", "大麻"],
  ["addictions", "成瘾"],
  ["gambling", "赌博"],
  ["poker", "扑克"],
  ["poker playing", "打扑克"],
  ["is gambling a sin gambling", "赌博是否犯罪"],
  ["obesity", "肥胖"],
  ["weight loss", "减重"],
  ["mental illness", "精神疾病"],
  ["self esteem", "自尊"],
  ["fear", "惧怕"],
  ["living in fear", "活在惧怕中"],
  ["overcoming fear", "胜过惧怕"],
  ["sexual abuse", "性侵犯"],
  ["sexual assault", "性侵犯"],
  ["homosexuality", "同性恋"],
  ["gayness", "同性恋倾向"],
  ["polygamy", "一夫多妻"],
  ["pornography", "色情"],
  ["abortion", "堕胎"],
  ["suicide", "自杀"],
  ["euthanasia", "安乐死"],
  ["war", "战争"],
  ["capital punishment", "死刑"],
  ["justice", "公义"],
  ["mercy", "怜悯"],
  ["grace", "恩典"],
  ["humility", "谦卑"],
  ["patience", "忍耐"],
  ["kindness", "恩慈"],
  ["jealousy", "嫉妒"],
  ["envy", "嫉妒"],
  ["gossip", "闲话"],
  ["lying", "说谎"],
  ["honesty", "诚实"],
  ["integrity", "正直"],
  ["wisdom", "智慧"],
  ["decision making", "做决定"],
  ["will of god", "神的旨意"],
  ["obeying the will of god", "遵行神的旨意"],
  ["baptism", "洗礼"],
  ["baptism of babies", "婴儿洗礼"],
  ["communion", "圣餐"],
  ["church attendance", "参加聚会"],
  ["gathering at church", "在教会聚集"],
  ["women as pastors", "女性作牧师"],
  ["body piercings and tattoos", "穿洞与纹身"],
  ["dating while separated", "分居期间约会"],
  ["courtship", "交往择偶"],
  ["choosing a mate", "选择配偶"],
  ["praying for a mate", "为配偶祷告"],
  ["kissing before marriage", "婚前接吻"],
  ["marriage vows", "婚誓"],
  ["marriage troubles", "婚姻难处"],
  ["step parents", "继父母"],
  ["stepfamilies", "重组家庭"],
  ["being a stepmom", "作继母"],
  ["fertility", "生育力"],
  ["ectopic pregnancy", "宫外孕"],
  ["childbearing", "怀孕分娩"],
  ["breastfeeding", "母乳喂养"],
  ["foster care", "寄养照顾"],
  ["taking care of poor", "照顾穷人"],
  ["giving time to jesus", "把时间给耶稣"],
  ["walking with jesus", "与耶稣同行"],
  ["best friends", "挚友"],
  ["being a friend", "作朋友"],
  ["friendship", "友谊"],
  ["bad days", "不顺的日子"],
  ["boredom", "无聊"],
  ["self doubt", "自我怀疑"],
  ["doubt", "疑惑"],
  ["cynicism", "冷嘲热讽"],
  ["gratitude", "感恩"],
  ["contentment", "知足"],
  ["significance", "意义感"],
  ["calling", "呼召"],
  ["miracles today", "今日神迹"],
  ["supernatural", "超自然"],
  ["fortune telling", "算命"],
  ["tarot cards", "塔罗牌"],
  ["astrology", "占星术"],
  ["familiar spirits", "邪灵／熟悉灵"],
  ["soothsayers", "占卜者"],
  ["witchcraft", "巫术"],
  ["the spirit of witchcraft", "巫术之灵"],
  ["psychology", "心理学"],
  ["journaling", "写日记"],
  ["imagination", "想象"],
  ["adventure", "冒险"],
  ["pets", "宠物"],
  ["animals", "动物"],
  ["zebra", "斑马"],
  ["housekeeping", "家务"],
  ["clutter", "杂乱"],
  ["smart", "聪明"],
  ["sanity", "心智健全"],
  ["walk", "行走"],
  ["sandals", "凉鞋"],
  ["midnight", "半夜"],
  ["the mouth", "口舌"],
  ["idle words", "闲言"],
  ["the human mind", "人的心思"],
  ["battlefield of the mind", "心思的战场"],
  ["letting go of hurt", "放下伤害"],
  ["fits of anger", "易怒发作"],
  ["quick temper", "暴躁"],
  ["quarrelsome", "好争辩"],
  ["irreverence", "不敬"],
  ["dont question gods word", "不要质疑神的话"],
  ["evidence", "证据"],
  ["enthusiasm", "热心"],
  ["evil people", "恶人"],
  ["fairness", "公平"],
  ["believers", "信徒"],
  ["uncommitted christians", "不冷不热的基督徒"],
  ["backsliders", "退后冷淡者"],
  ["living holy", "过圣洁生活"],
  ["baby jesus", "圣婴耶稣"],
  ["being a man of god", "作神的男人"],
  ["being upset", "心烦意乱"],
  ["being lucky", "运气（议题）"],
  ["caleb", "迦勒"],
  ["andrew", "安得烈"],
  ["jezebel", "耶洗别"],
  ["ishtar", "伊师塔"],
  ["the virtuous woman", "才德妇人"],
  ["the way", "道路（信仰用语）"],
  ["philippians", "腓立比书"],
  ["footprints", "脚印（灵修小品）"],
  ["the da vinci code", "《达·芬奇密码》（流行文化议题）"],
  ["the twin towers", "双子塔（事件议题）"],
  ["the tsunami", "海啸（灾难议题）"],
  ["labor day", "劳动节"],
  ["the weather", "天气"],
  ["the nile river", "尼罗河"],
  ["the star of david", "大卫之星"],
  ["the day of pentecost", "五旬节"],
  ["pentecost", "五旬节"],
  ["the first resurrection", "第一次复活"],
  ["the end of days", "末日"],
  ["ezekiel", "以西结"],
  ["daniel", "但以理"],
  ["revelation", "启示录"],
  ["genesis", "创世记"],
  ["exodus", "出埃及记"],
  ["leviticus", "利未记"],
  ["numbers", "民数记"],
  ["deuteronomy", "申命记"],
  ["joshua", "约书亚记"],
  ["judges", "士师记"],
  ["ruth", "路得记"],
  ["job", "约伯"],
  ["psalms", "诗篇"],
  ["proverbs", "箴言"],
  ["ecclesiastes", "传道书"],
  ["isaiah", "以赛亚书"],
  ["jeremiah", "耶利米书"],
  ["matthew", "马太福音"],
  ["mark", "马可福音"],
  ["luke", "路加福音"],
  ["john", "约翰福音"],
  ["acts", "使徒行传"],
  ["romans", "罗马书"],
];

export const OPENBIBLE_TOPIC_ZH_HANDBOOK: Record<string, string> = Object.fromEntries(
  HANDBOOK_ENTRIES.filter(([k], i, arr) => arr.findIndex(([x]) => x === k) === i),
);

export function composeOpenbibleTopicZhFromParts(topic: string): string | null {
  const k = normalizeOpenbibleTopicKey(topic);
  const words = k.split(" ").filter(Boolean);
  if (words.length < 1 || words.length > 14) return null;
  const parts: string[] = [];
  for (const w of words) {
    const piece = OPENBIBLE_TOPIC_ZH_WORD_PARTS[w];
    if (piece === undefined) continue;
    if (piece) parts.push(piece);
  }
  if (parts.length === 0) return null;
  return parts.join("·");
}
