import { StyleSheet } from "react-native";
import { parchmentSans } from "../fonts/parchmentType";
import { readParchmentTheme as c } from "../read/readParchmentTheme";

export const legacyFigureScreenStyles = StyleSheet.create({
  pageTitle: {
    marginTop: 10,
    fontSize: 32,
    lineHeight: 36,
    letterSpacing: -0.5,
    ...parchmentSans(700),
    color: c.ink,
    textAlign: "center",
  },
  subtitle: {
    marginTop: 14,
    fontSize: 15,
    lineHeight: 24,
    ...parchmentSans(500),
    color: c.inkSoft,
    textAlign: "center",
  },
  timeline: {
    marginTop: 22,
    gap: 0,
  },
  testamentRow: {
    flexDirection: "row",
    gap: 14,
    paddingBottom: 8,
  },
  bookRow: {
    flexDirection: "row",
    gap: 14,
    paddingBottom: 24,
  },
  markerCol: {
    width: 18,
    alignItems: "center",
  },
  dot: {
    width: 10,
    height: 10,
    marginTop: 6,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "rgba(120, 53, 15, 0.42)",
    backgroundColor: "rgba(255, 252, 245, 0.92)",
  },
  dotTestament: {
    width: 12,
    height: 12,
    marginTop: 4,
    backgroundColor: "rgba(120, 53, 15, 0.18)",
  },
  line: {
    flex: 1,
    width: 2,
    marginTop: 4,
    backgroundColor: "rgba(120, 53, 15, 0.28)",
  },
  bodyCol: {
    flex: 1,
    minWidth: 0,
  },
  testamentLabel: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    ...parchmentSans(600),
    color: c.faint,
    textTransform: "uppercase",
  },
  bookHeading: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    flexWrap: "wrap",
  },
  bookOrder: {
    fontSize: 22,
    lineHeight: 28,
    ...parchmentSans(700),
    color: c.ink,
    fontVariant: ["tabular-nums"],
  },
  bookName: {
    fontSize: 22,
    lineHeight: 28,
    ...parchmentSans(700),
    color: c.ink,
  },
  bookEra: {
    marginTop: 2,
    fontSize: 13,
    lineHeight: 18,
    ...parchmentSans(500),
    color: c.faint,
  },
  figuresWrap: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(120, 53, 15, 0.14)",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  figureLink: {
    paddingVertical: 2,
  },
  figureNamePrimary: {
    fontSize: 15,
    lineHeight: 22,
    ...parchmentSans(600),
    color: c.ink,
  },
  figureNameSecondary: {
    fontSize: 15,
    lineHeight: 22,
    ...parchmentSans(500),
    color: c.faint,
  },
  figureFlag: {
    color: "#a56a2d",
    fontWeight: "700",
  },
  detailPeriod: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.8,
    ...parchmentSans(600),
    color: c.faint,
    textAlign: "center",
  },
  metaWrap: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
  },
  metaChip: {
    fontSize: 12,
    lineHeight: 16,
    ...parchmentSans(600),
    color: c.faint,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(120, 53, 15, 0.2)",
  },
  articleBody: {
    marginTop: 18,
  },
  missingBody: {
    marginTop: 18,
    fontSize: 15,
    lineHeight: 24,
    ...parchmentSans(500),
    color: c.faint,
    textAlign: "center",
  },
});
