import { StyleSheet } from "react-native";
import { parchmentSans } from "../fonts/parchmentType";
import { readParchmentTheme as c } from "../read/readParchmentTheme";

export const biblicalFeastsScreenStyles = StyleSheet.create({
  pageTitle: {
    marginTop: 10,
    fontSize: 30,
    lineHeight: 38,
    letterSpacing: -0.45,
    ...parchmentSans(600),
    color: c.ink,
    textAlign: "center",
  },
  subtitle: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.1,
    ...parchmentSans(500),
    color: c.inkSoft,
    textAlign: "center",
  },
  lead: {
    marginTop: 14,
    fontSize: 14,
    lineHeight: 22,
    ...parchmentSans(500),
    color: c.muted,
    textAlign: "center",
  },
  timelineHeader: {
    marginTop: 20,
    paddingTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.border,
    gap: 10,
  },
  timelineHeading: {
    textAlign: "center",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.35,
    ...parchmentSans(600),
    color: c.faint,
  },
  timelineHeaderSecondary: {
    marginTop: 22,
    paddingTop: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.border,
    gap: 8,
  },
  timelineSubLead: {
    textAlign: "center",
    fontSize: 13,
    lineHeight: 20,
    ...parchmentSans(500),
    color: c.muted,
  },
  timelineList: {
    marginTop: 12,
    gap: 2,
  },
  seasonLabel: {
    marginTop: 12,
    marginBottom: 6,
    alignSelf: "center",
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.border,
    backgroundColor: c.surface,
    paddingHorizontal: 12,
    paddingVertical: 4,
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 0.3,
    ...parchmentSans(600),
    color: c.faint,
  },
  timelineItem: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
  },
  timelineLeft: {
    width: 68,
    paddingTop: 10,
    alignItems: "flex-end",
    gap: 1,
  },
  timelineMonth: {
    fontSize: 11,
    lineHeight: 14,
    ...parchmentSans(600),
    color: c.faint,
  },
  timelineDay: {
    fontSize: 13,
    lineHeight: 17,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  timelineRailWrap: {
    width: 24,
    alignItems: "center",
    position: "relative",
  },
  timelineRail: {
    position: "absolute",
    top: 18,
    bottom: -16,
    width: 2,
    borderRadius: 1,
    backgroundColor: c.border,
  },
  timelineDotWrap: {
    marginTop: 12,
    width: 16,
    height: 16,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: c.surfaceSolid,
  },
  timelineDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: c.parchmentAccent,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderStrong,
  },
  timelineOrder: {
    marginTop: 4,
    fontSize: 9,
    lineHeight: 12,
    ...parchmentSans(700),
    color: c.faint,
  },
  feastCard: {
    flex: 1,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.chapterCellBorder,
    backgroundColor: c.chapterCell,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 0,
  },
  feastHeaderPressable: {
    gap: 5,
  },
  feastHeaderPressed: {
    opacity: 0.82,
  },
  feastHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  feastTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 18,
    lineHeight: 24,
    ...parchmentSans(700),
    color: c.ink,
  },
  feastExpandMark: {
    marginTop: 1,
    width: 18,
    textAlign: "center",
    fontSize: 20,
    lineHeight: 20,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  feastScripture: {
    fontSize: 12,
    lineHeight: 17,
    ...parchmentSans(600),
    color: c.faint,
  },
  feastDetails: {
    marginTop: 8,
    gap: 6,
  },
  sectionLabel: {
    marginTop: 4,
    fontSize: 11,
    lineHeight: 15,
    letterSpacing: 0.25,
    ...parchmentSans(600),
    color: c.parchmentAccent,
  },
  feastSummary: {
    fontSize: 14,
    lineHeight: 21,
    ...parchmentSans(500),
    color: c.inkSoft,
  },
  feastSecondary: {
    fontSize: 13,
    lineHeight: 20,
    ...parchmentSans(500),
    color: c.inkSoft,
  },
  feastPractice: {
    fontSize: 13,
    lineHeight: 20,
    ...parchmentSans(500),
    color: c.muted,
  },
  readTargetsWrap: {
    marginTop: 2,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  readTargetButton: {
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.borderStrong,
    backgroundColor: c.surface,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  readTargetButtonPressed: {
    opacity: 0.82,
  },
  readTargetButtonText: {
    fontSize: 12,
    lineHeight: 16,
    ...parchmentSans(600),
    color: c.inkSoft,
  },
  readNowButton: {
    marginTop: 6,
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.parchmentAccent,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: c.chapterCellPressed,
  },
  readNowButtonPressed: {
    opacity: 0.82,
  },
  readNowButtonText: {
    fontSize: 12,
    lineHeight: 16,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
});
