import { StyleSheet } from "react-native";
import { parchmentSans } from "../fonts/parchmentType";
import { readParchmentTheme as c } from "../read/readParchmentTheme";

export const yearsDaysEternitySectionStyles = StyleSheet.create({
  section: {
    marginTop: 8,
  },
  eyebrow: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 23,
    letterSpacing: 0.1,
    ...parchmentSans(500),
    color: c.inkSoft,
    textAlign: "center",
  },
  pageTitle: {
    fontSize: 22,
    ...parchmentSans(600),
    letterSpacing: -0.3,
    lineHeight: 28,
    color: c.ink,
    textAlign: "center",
    marginTop: 24,
  },
  closing: {
    marginTop: 20,
    paddingTop: 2,
  },
  finale: {
    marginTop: 24,
    paddingTop: 4,
    paddingBottom: 4,
    alignItems: "center",
  },
  finaleRule: {
    marginBottom: 22,
    height: StyleSheet.hairlineWidth,
    width: 56,
    backgroundColor: c.borderStrong,
    alignSelf: "center",
  },
  finaleInner: {
    width: "100%",
    maxWidth: 360,
    paddingHorizontal: 6,
    gap: 18,
  },
  finaleLead: {
    gap: 4,
    alignItems: "center",
  },
  finaleLeadLine: {
    fontSize: 16,
    lineHeight: 26,
    ...parchmentSans(600),
    color: c.ink,
    textAlign: "center",
    letterSpacing: 0.05,
  },
  finaleScripture: {
    gap: 6,
    paddingTop: 2,
  },
  finaleVerseLine: {
    fontSize: 16,
    lineHeight: 28,
    ...parchmentSans(500),
    color: c.inkSoft,
    textAlign: "center",
    letterSpacing: 0.02,
  },
  finaleRefLine: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    ...parchmentSans(500),
    color: c.faint,
    textAlign: "center",
    letterSpacing: 0.08,
  },
  proseBlock: {
    marginTop: 10,
    gap: 6,
  },
  proseBlockCenter: {
    alignItems: "center",
  },
  proseLine: {
    fontSize: 15,
    lineHeight: 24,
    ...parchmentSans(500),
    color: c.muted,
  },
  proseLineCenter: {
    textAlign: "center",
  },
  accordionList: {
    marginTop: 36,
    gap: 10,
  },
  accordionItem: {
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.chapterCellBorder,
    backgroundColor: c.chapterCell,
    overflow: "hidden",
  },
  accordionHeader: {
    minHeight: 56,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  accordionHeaderPressed: {
    backgroundColor: c.hover,
  },
  headerTextWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  sectionIndexText: {
    fontSize: 16,
    lineHeight: 22,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  sectionTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 17,
    lineHeight: 24,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  sectionChevron: {
    fontSize: 22,
    lineHeight: 24,
    ...parchmentSans(700),
    color: c.parchmentAccent,
    width: 18,
    textAlign: "center",
  },
  accordionBody: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    paddingTop: 4,
  },
  scriptureFlowCol: {
    gap: 12,
  },
  scripturePassage: {
    gap: 2,
  },
  scriptureFlow: {
    fontSize: 16,
    lineHeight: 24,
    ...parchmentSans(500),
    color: c.inkSoft,
    textAlign: "left",
  },
  scriptureRefLine: {
    fontSize: 12,
    lineHeight: 17,
    ...parchmentSans(500),
    color: c.faint,
    textAlign: "right",
    letterSpacing: 0.06,
  },
  encouragement: {
    marginTop: 32,
    paddingTop: 8,
    paddingBottom: 12,
    alignItems: "center",
  },
  encouragementRule: {
    marginBottom: 20,
    height: StyleSheet.hairlineWidth,
    width: 56,
    backgroundColor: c.borderStrong,
    alignSelf: "center",
  },
  encouragementScripture: {
    width: "100%",
    maxWidth: 360,
    paddingHorizontal: 6,
    gap: 6,
    alignItems: "center",
  },
  encouragementVerseLine: {
    fontSize: 16,
    lineHeight: 28,
    ...parchmentSans(500),
    color: c.inkSoft,
    textAlign: "center",
    letterSpacing: 0.02,
  },
  encouragementRefLine: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    ...parchmentSans(500),
    color: c.faint,
    textAlign: "center",
    letterSpacing: 0.08,
  },
});
