import { StyleSheet } from "react-native";
import { parchmentSans } from "../fonts/parchmentType";
import { readParchmentTheme as c } from "../read/readParchmentTheme";

export const historicalCreedsScreenStyles = StyleSheet.create({
  pageTitle: {
    marginTop: 10,
    fontSize: 30,
    lineHeight: 38,
    letterSpacing: -0.45,
    ...parchmentSans(600),
    color: c.ink,
    textAlign: "center",
  },
  lead: {
    marginTop: 14,
    fontSize: 14,
    lineHeight: 22,
    ...parchmentSans(500),
    color: c.muted,
    textAlign: "center",
  },
  backLink: {
    marginBottom: 6,
  },
  timelineList: {
    marginTop: 16,
    gap: 10,
  },
  groupLabel: {
    marginTop: 20,
    marginBottom: 10,
    marginLeft: 34,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.2,
    ...parchmentSans(700),
    color: c.ink,
  },
  timelineItem: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
  },
  timelineContent: {
    flex: 1,
    gap: 8,
  },
  creedYearRow: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    gap: 6,
    paddingTop: 10,
    minHeight: 28,
  },
  timelineYearPrimary: {
    fontSize: 12,
    lineHeight: 16,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  timelineYearFeatured: {
    fontSize: 13,
    ...parchmentSans(700),
  },
  timelineRailWrap: {
    width: 24,
    alignItems: "center",
    position: "relative",
  },
  timelineRail: {
    position: "absolute",
    top: 18,
    bottom: -16,
    width: 4,
    borderRadius: 2,
    backgroundColor: c.accentOt,
  },
  timelineDotWrap: {
    marginTop: 12,
    width: 11,
    height: 11,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineDotWrapFeatured: {
    marginTop: 10,
    width: 13,
    height: 13,
  },
  timelineDot: {
    width: 11,
    height: 11,
    borderRadius: 999,
    backgroundColor: c.accentOt,
  },
  timelineDotFeatured: {
    width: 13,
    height: 13,
  },
  timelineOrder: {
    marginTop: 4,
    fontSize: 9,
    lineHeight: 12,
    ...parchmentSans(700),
    color: c.faint,
  },
  creedCard: {
    flex: 1,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.chapterCellBorder,
    backgroundColor: c.chapterCell,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 0,
    overflow: "hidden",
  },
  creedCardFeatured: {
    borderWidth: 2,
    borderColor: c.parchmentAccent,
    backgroundColor: c.chapterCellPressed,
  },
  creedFeaturedStripe: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: c.accentOt,
  },
  creedFeaturedBadge: {
    alignSelf: "flex-start",
    marginBottom: 10,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: "rgba(217, 119, 7, 0.45)",
    backgroundColor: "rgba(217, 119, 7, 0.14)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 0.45,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  groupLead: {
    marginTop: -4,
    marginBottom: 12,
    marginLeft: 34,
    marginRight: 8,
    fontSize: 14,
    lineHeight: 22,
    ...parchmentSans(500),
    color: c.muted,
  },
  creedHeaderPressable: {
    gap: 5,
  },
  creedHeaderPressed: {
    opacity: 0.82,
  },
  creedHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  creedHeaderRight: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    flexShrink: 0,
  },
  creedTitleRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap",
  },
  creedOrder: {
    fontSize: 19,
    lineHeight: 26,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedOrderFeatured: {
    fontSize: 20,
    lineHeight: 27,
  },
  creedTitle: {
    flexShrink: 1,
    fontSize: 19,
    lineHeight: 26,
    ...parchmentSans(700),
    color: c.ink,
  },
  creedTitleFeatured: {
    fontSize: 20,
    lineHeight: 27,
    ...parchmentSans(700),
    color: c.ink,
  },
  creedExpandMark: {
    marginTop: 1,
    width: 18,
    textAlign: "center",
    fontSize: 20,
    lineHeight: 20,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedYear: {
    fontSize: 12,
    lineHeight: 17,
    ...parchmentSans(600),
    color: c.faint,
  },
  creedYearInline: {
    marginTop: 2,
    maxWidth: 88,
    fontSize: 11,
    lineHeight: 15,
    textAlign: "right",
    ...parchmentSans(600),
    color: c.faint,
  },
  creedDetails: {
    marginTop: 14,
    gap: 8,
  },
  creedProblemBlock: {
    marginTop: 14,
    gap: 8,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth * 2,
    borderTopColor: c.border,
  },
  sectionLabel: {
    marginBottom: 4,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.35,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedBody: {
    fontSize: 15,
    lineHeight: 24,
    ...parchmentSans(400),
    color: c.inkSoft,
  },
  readFullButton: {
    marginTop: 12,
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.parchmentAccent,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: c.chapterCellPressed,
  },
  readFullButtonPressed: {
    opacity: 0.82,
  },
  readFullButtonText: {
    fontSize: 12,
    lineHeight: 16,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedFullTextBlock: {
    marginTop: 16,
    gap: 10,
    paddingTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth * 2,
    borderTopColor: c.border,
  },
  creedBodyLoadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
  },
  creedBodyLoadingText: {
    fontSize: 14,
    lineHeight: 20,
    ...parchmentSans(400),
    color: c.muted,
  },
  creedBodySectionsWrap: {
    gap: 10,
  },
  creedBodySectionBlock: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.chapterCellBorder,
    backgroundColor: c.chapterCell,
    overflow: "hidden",
  },
  creedBodySectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  creedBodySectionHeaderPressed: {
    opacity: 0.84,
  },
  creedBodySectionTitle: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    ...parchmentSans(700),
    color: c.ink,
  },
  creedBodySectionMark: {
    fontSize: 18,
    lineHeight: 20,
    ...parchmentSans(600),
    color: c.parchmentAccent,
  },
  creedBodySectionContent: {
    gap: 12,
    borderTopWidth: StyleSheet.hairlineWidth * 2,
    borderTopColor: c.border,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
  },
  creedBodyTopicSectionsWrap: {
    gap: 10,
  },
  creedBodyPartGroup: {
    gap: 10,
    marginTop: 6,
  },
  creedBodyPartHeading: {
    fontSize: 16,
    lineHeight: 23,
    ...parchmentSans(700),
    color: c.parchmentAccent,
    marginTop: 8,
    marginBottom: 2,
  },
  creedFullTextDocumentWrap: {
    marginTop: 6,
    marginBottom: 12,
    gap: 8,
  },
  creedFullTextSectionWrap: {
    marginTop: 22,
    marginBottom: 8,
    gap: 8,
  },
  creedFullTextLordsDayWrap: {
    marginTop: 26,
    marginBottom: 10,
    paddingTop: 4,
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: "rgba(139, 94, 52, 0.18)",
  },
  creedFullTextArticleWrap: {
    marginTop: 4,
    marginBottom: 6,
    gap: 6,
  },
  creedFullTextArticleHeadingWrap: {
    marginTop: 40,
    marginBottom: 14,
    paddingBottom: 2,
    gap: 0,
  },
  creedChicagoArticleBlock: {
    marginTop: 160,
    marginBottom: 0,
    paddingTop: 0,
    gap: 0,
  },
  creedChicagoArticleBlockLead: {
    marginTop: 72,
    marginBottom: 0,
  },
  creedChicagoArticleTitle: {
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.45,
    ...parchmentSans(700),
    color: c.parchmentAccent,
    marginBottom: 4,
  },
  creedChicagoArticleTitleLead: {
    marginBottom: 2,
  },
  creedChicagoAffirmLabel: {
    fontSize: 16,
    lineHeight: 24,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedChicagoDenyLabel: {
    fontSize: 16,
    lineHeight: 24,
    ...parchmentSans(700),
    color: c.muted,
  },
  creedChicagoBody: {
    fontSize: 15,
    lineHeight: 26,
    ...parchmentSans(400),
    color: c.ink,
  },
  creedFullTextArticleLabelWrap: {
    marginTop: 20,
    marginBottom: 0,
    gap: 0,
  },
  creedFullTextSubsectionWrap: {
    marginTop: 18,
    marginBottom: 6,
    gap: 6,
  },
  creedFullTextSubarticleWrap: {
    marginTop: 12,
    marginLeft: 10,
    paddingLeft: 12,
    borderLeftWidth: 5,
    borderLeftColor: c.accentOt,
    gap: 5,
  },
  creedFullTextProofItemWrap: {
    marginTop: 6,
    marginLeft: 4,
    flexDirection: "row",
    gap: 6,
  },
  creedFullTextProofItem: {
    fontSize: 14,
    lineHeight: 22,
    ...parchmentSans(400),
    color: c.ink,
    opacity: 0.9,
    flex: 1,
  },
  creedFullTextProofItemLabel: {
    fontSize: 14,
    lineHeight: 22,
    ...parchmentSans(700),
    color: c.parchmentAccent,
    minWidth: 22,
  },
  creedFullTextAffirmWrap: {
    marginTop: 6,
  },
  creedFullTextDenyWrap: {
    marginTop: 10,
  },
  creedFullTextQuestionWrap: {
    marginTop: 4,
    gap: 6,
  },
  creedFullTextQuestionWrapFollows: {
    marginTop: 26,
    paddingTop: 20,
    borderTopWidth: StyleSheet.hairlineWidth * 2,
    borderTopColor: "rgba(139, 94, 52, 0.14)",
  },
  creedFullTextAnswerWrap: {
    marginTop: 10,
    gap: 8,
    paddingLeft: 12,
    borderLeftWidth: 3,
    borderLeftColor: "rgba(139, 94, 52, 0.22)",
  },
  creedFullTextAnswerWrapSpacing: {
    marginBottom: 16,
  },
  creedFullTextQuestionLabel: {
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.6,
    ...parchmentSans(700),
    color: c.parchmentAccent,
    textTransform: "none",
  },
  creedFullTextAnswerLabel: {
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.4,
    ...parchmentSans(700),
    color: c.muted,
  },
  creedFullTextQuestionBody: {
    fontSize: 16,
    lineHeight: 26,
    ...parchmentSans(600),
    color: c.ink,
  },
  creedFullTextAnswerBody: {
    fontSize: 15,
    lineHeight: 26,
    ...parchmentSans(400),
    color: c.inkSoft,
  },
  creedFullTextAffirmLabel: {
    fontSize: 15,
    lineHeight: 22,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedFullTextDenyLabel: {
    fontSize: 15,
    lineHeight: 22,
    ...parchmentSans(700),
    color: c.ink,
    opacity: 0.72,
  },
  creedFullTextDocumentTitle: {
    fontSize: 19,
    lineHeight: 27,
    ...parchmentSans(700),
    color: c.ink,
  },
  creedFullTextSectionTitle: {
    fontSize: 16,
    lineHeight: 23,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedFullTextLordsDayTitle: {
    fontSize: 17,
    lineHeight: 24,
    letterSpacing: 0.4,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedFullTextArticleTitle: {
    fontSize: 17,
    lineHeight: 24,
    letterSpacing: 0.3,
    ...parchmentSans(700),
    color: c.ink,
  },
  creedFullTextArticleLabelTitle: {
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.2,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedFullTextSubsectionTitle: {
    fontSize: 14,
    lineHeight: 20,
    ...parchmentSans(700),
    color: c.parchmentAccent,
  },
  creedFullTextSubarticleTitle: {
    fontSize: 14,
    lineHeight: 20,
    ...parchmentSans(600),
    color: c.ink,
    opacity: 0.94,
  },
  creedFullTextBody: {
    fontSize: 15,
    lineHeight: 25,
    ...parchmentSans(400),
    color: c.ink,
    opacity: 0.92,
  },
  creedScriptureLink: {
    fontSize: 15,
    lineHeight: 25,
    ...parchmentSans(600),
    color: c.parchmentAccent,
    textDecorationLine: "underline",
  },
  creedFullTextParagraph: {
    fontSize: 15,
    lineHeight: 25,
    ...parchmentSans(400),
    color: c.ink,
    marginTop: 4,
  },
});
