import type { AppLocale } from "../i18n/config";
import { toZhTwText } from "../i18n/site-copy";

/** English divine-role labels for canon catalog (zh from scripture-book-notes). */
export const scriptureBookDivineEn: Record<string, string> = {
  GEN: "Creator",
  EXO: "Deliverer",
  LEV: "Holy God",
  NUM: "Guide in the wilderness",
  DEU: "Covenant-keeping God",
  JOS: "Commander who gives victory",
  JDG: "God who keeps showing mercy",
  RUT: "God of provision and redemption",
  "1SA": "God who searches the heart",
  "2SA": "God of grace who builds a kingdom",
  "1KI": "King who rules",
  "2KI": "God who judges and calls back",
  "1CH": "God who remembers his covenant",
  "2CH": "God worthy of worship",
  EZR: "God who restores worship",
  NEH: "God who rebuilds what is broken",
  EST: "God who rules though hidden",
  JOB: "God who reigns beyond understanding",
  PSA: "Shepherd, rock, refuge",
  PRO: "Source of wisdom",
  ECC: "Lord of eternity",
  SNG: "Source of love",
  ISA: "Holy One and Redeemer",
  JER: "God who still calls people home",
  LAM: "Hope in the ruins",
  EZK: "Glory still present",
  DAN: "God over the nations",
  HOS: "Love that does not give up",
  JOL: "God who gives the Spirit",
  AMO: "God of righteousness",
  OBA: "God who humbles pride",
  JON: "God merciful to nations",
  MIC: "God who delights in mercy",
  NAM: "God who judges evil",
  HAB: "God the righteous trust",
  ZEP: "God who still delights to love",
  HAG: "God who calls people back to center",
  ZEC: "God who gives vision and hope",
  MAL: "God who does not change",
  MAT: "King in promise",
  MRK: "Servant King",
  LUK: "Compassionate Savior",
  JHN: "Light of life",
  ACT: "God at work by the Spirit",
  ROM: "God who justifies",
  "1CO": "God who unifies the church",
  "2CO": "God whose power shows in weakness",
  GAL: "God who sets free",
  EPH: "God who builds Christ's body",
  PHP: "God of joy and peace",
  COL: "Lord above all",
  "1TH": "Lord who is coming",
  "2TH": "Lord of the end",
  "1TI": "God who entrusts truth",
  "2TI": "God worth faithfulness to the end",
  TIT: "God who renews life",
  PHM: "God who reconciles",
  HEB: "Great high priest of a better covenant",
  JAS: "God who makes faith live",
  "1PE": "Hope in suffering",
  "2PE": "Lord who is faithful and true",
  "1JN": "God is love",
  "2JN": "God of truth",
  "3JN": "God present in true fellowship",
  JUD: "God who keeps to the end",
  REV: "Alpha and Omega, Beginning and End",
};

export function divineLabelForLocale(
  bookId: string,
  zhDivine: string,
  locale: AppLocale,
): string {
  if (locale === "zh-TW") return toZhTwText(zhDivine);
  if (locale !== "en") return zhDivine;
  const en = scriptureBookDivineEn[bookId.trim().toUpperCase()];
  return en?.trim() || zhDivine;
}
