import type { ScriptureBookNote } from './scriptureBookNoteTypes';

export const scriptureBookNotesNt: ScriptureBookNote[] = [
  {
    bookId: "MAT",
    stageId: "christ-advent",
    groupId: "gospels",
    spiritualFrame: {
      divine: "应许中的君王",
      human: "迎接神真正的国度来到。",
      invitation: "迎接应许中的君王，进入天国临近的新现实。",
    },
    summary: "证明耶稣是应许中的弥赛亚君王。",
    keywords: ["君王", "天国", "马太", "应许", "弥赛亚"],
  },
  {
    bookId: "MRK",
    stageId: "christ-advent",
    groupId: "gospels",
    spiritualFrame: {
      divine: "服事人的仆人君王",
      human: "学习跟随耶稣走舍己服事的道路。",
      invitation: "跟随舍己服事的主，在行动中认识神儿子的权柄与爱。",
    },
    summary: "描写耶稣以行动服事、受苦并复活。",
    keywords: ["仆人", "舍己", "马可", "服事", "跟随"],
  },
  {
    bookId: "LUK",
    stageId: "christ-advent",
    groupId: "gospels",
    spiritualFrame: {
      divine: "充满怜悯的救主",
      human: "在软弱中经历神的怜悯。",
      invitation: "让耶稣走近你的软弱，在祂怜悯里重新被看见。",
    },
    summary: "强调耶稣是怜悯罪人和万民的救主。",
    keywords: ["怜悯", "救主", "路加", "软弱", "福音"],
  },
  {
    bookId: "JHN",
    stageId: "christ-advent",
    groupId: "gospels",
    spiritualFrame: {
      divine: "生命的光",
      human: "在黑暗中走向真正的生命。",
      invitation: "走向那位道成肉身的生命之光，在祂里面得生命。",
    },
    summary: "宣告耶稣是神的儿子，使信祂的人得生命。",
    keywords: ["生命", "光", "道成肉身", "约翰", "相信"],
  },
  {
    bookId: "ACT",
    stageId: "church-spirit-epistles",
    groupId: "church-history",
    spiritualFrame: {
      divine: "借着圣灵运行的神",
      human: "顺着圣灵，把福音带向世界。",
      invitation: "顺服圣灵的推动，让福音从近处走向万民。",
    },
    summary: "圣灵降临，教会建立，福音传向外邦。",
    keywords: ["圣灵", "教会", "宣教", "使徒", "福音"],
  },
  {
    bookId: "ROM",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "使人称义的神",
      human: "因信重新与神和好。",
      invitation: "离开自义与定罪，凭信进入与神和好的恩典。",
    },
    summary: "说明人因信耶稣被神称义。",
    keywords: ["称义", "信心", "恩典", "罗马书", "和好"],
  },
  {
    bookId: "1CO",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "使教会合一的神",
      human: "在混乱中重新学习爱。",
      invitation: "在分裂与混乱中回到十字架，重新学习爱与合一。",
    },
    summary: "处理教会分裂、道德和属灵恩赐等问题。",
    keywords: ["教会", "合一", "爱", "恩赐", "十字架"],
  },
  {
    bookId: "2CO",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "在软弱中显出能力的神",
      human: "在软弱里经历神真正的能力。",
      invitation: "不再逃避软弱，让基督的能力在瓦器里显明。",
    },
    summary: "保罗说明真正的使徒服事是在软弱中显出神能力。",
    keywords: ["软弱", "能力", "安慰", "和好", "瓦器"],
  },
  {
    bookId: "GAL",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "使人得自由的神",
      human: "离开捆绑，活在恩典中。",
      invitation: "从靠行为证明自己中出来，活在基督释放的自由里。",
    },
    summary: "强调得救靠信基督，不靠守律法。",
    keywords: ["自由", "恩典", "律法", "圣灵", "加拉太"],
  },
  {
    bookId: "EPH",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "建立基督身体的神",
      human: "学习彼此连接，成为一个身体。",
      invitation: "在基督里认识新的身份，与众圣徒一同被建造。",
    },
    summary: "说明教会在基督里的合一和新生命。",
    keywords: ["基督身体", "教会", "身份", "合一", "建造"],
  },
  {
    bookId: "PHP",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "赐人喜乐与平安的神",
      human: "即使在困境中，仍然喜乐。",
      invitation: "在困境中以基督为至宝，学习不被环境夺去喜乐。",
    },
    summary: "教导信徒在基督里喜乐并效法祂。",
    keywords: ["喜乐", "平安", "基督", "困境", "腓立比"],
  },
  {
    bookId: "COL",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "超越万有的主",
      human: "让基督成为生命真正的中心。",
      invitation: "让超越万有的基督成为思想、生活与关系的中心。",
    },
    summary: "高举基督超越万有、完全充足。",
    keywords: ["基督", "万有", "中心", "新人", "歌罗西"],
  },
  {
    bookId: "1TH",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "将再来的主",
      human: "在等待中持守盼望。",
      invitation: "在等候主再来时，以信心、爱心与盼望生活。",
    },
    summary: "鼓励信徒圣洁生活，等候主再来。",
    keywords: ["再来", "盼望", "等候", "圣洁", "帖撒罗尼迦"],
  },
  {
    bookId: "2TH",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "掌管末后的主",
      human: "在混乱中仍坚定信心。",
      invitation: "在末世混乱与误解中安静持守，忠心生活。",
    },
    summary: "澄清主再来的误解，劝信徒忠心生活。",
    keywords: ["末后", "坚定", "混乱", "信心", "忍耐"],
  },
  {
    bookId: "1TI",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "托付真道的神",
      human: "忠心牧养并守护真理。",
      invitation: "在教会生活中守护真道，以忠心牧养神的群羊。",
    },
    summary: "教导教会治理、领袖资格和敬虔生活。",
    keywords: ["真道", "牧养", "教会", "忠心", "提摩太"],
  },
  {
    bookId: "2TI",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "值得人忠心到底的神",
      human: "即使走到尽头，也持守所信。",
      invitation: "在疲惫与临别中继续守住所信，忠心到底。",
    },
    summary: "保罗临终前劝提摩太忠心传道。",
    keywords: ["忠心到底", "圣经", "苦难", "传道", "持守"],
  },
  {
    bookId: "TIT",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "更新生命的神",
      human: "活出被福音更新后的生命。",
      invitation: "让福音不止停在口中，而是更新品格与生活。",
    },
    summary: "教导设立长老，并以善行见证信仰。",
    keywords: ["更新", "善行", "教会秩序", "生命", "提多"],
  },
  {
    bookId: "PHM",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "使人和好的神",
      human: "在关系中学习饶恕与和好。",
      invitation: "让福音进入具体关系，学习接纳、饶恕与和好。",
    },
    summary: "请求腓利门接纳悔改归主的阿尼西母。",
    keywords: ["和好", "饶恕", "关系", "阿尼西母", "腓利门"],
  },
  {
    bookId: "HEB",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "更美之约的大祭司",
      human: "定睛仰望基督，不再后退。",
      invitation: "在疲惫与试探中定睛基督，进入更美之约的稳固盼望。",
    },
    summary: "说明耶稣超越旧约一切，是更美之约的中保。",
    keywords: ["大祭司", "更美之约", "信心", "忍耐", "基督"],
  },
  {
    bookId: "JAS",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "使信心活出来的神",
      human: "让信心真实进入生活。",
      invitation: "让信心从言语进入行动，在生活里显出真实生命。",
    },
    summary: "强调真实信心会表现为行为。",
    keywords: ["信心", "行为", "试炼", "言语", "智慧"],
  },
  {
    bookId: "1PE",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "苦难中的盼望",
      human: "在苦难中仍持守盼望。",
      invitation: "在寄居与苦难中持守圣洁，活在复活带来的盼望里。",
    },
    summary: "鼓励受苦信徒持守盼望和圣洁。",
    keywords: ["苦难", "盼望", "寄居", "圣洁", "彼得"],
  },
  {
    bookId: "2PE",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "真实可信的主",
      human: "在混乱中持守真理。",
      invitation: "在谎言与混乱中扎根真理，等候主真实可信的应许。",
    },
    summary: "警告假教师，提醒信徒等候主再来。",
    keywords: ["真理", "假教师", "应许", "等候", "警醒"],
  },
  {
    bookId: "1JN",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "爱",
      human: "学习住在爱里，也彼此相爱。",
      invitation: "住在神的爱与光中，让彼此相爱成为真实生命的记号。",
    },
    summary: "教导信徒住在真理和爱中。",
    keywords: ["爱", "光", "相交", "确据", "约翰"],
  },
  {
    bookId: "2JN",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "真理中的神",
      human: "在真理与爱中同行。",
      invitation: "不把爱和真理拆开，在真理中彼此相爱。",
    },
    summary: "劝信徒持守真理并防备假教导。",
    keywords: ["真理", "爱", "同行", "持守", "接待"],
  },
  {
    bookId: "3JN",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "在真实关系中同在的神",
      human: "在平凡关系里活出真理。",
      invitation: "在接待、同工与真实关系中，让真理成为可见的生命。",
    },
    summary: "称赞接待真传道人，批评骄傲的领袖。",
    keywords: ["接待", "真理", "同工", "关系", "忠心"],
  },
  {
    bookId: "JUD",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "保守人到底的神",
      human: "竭力持守已经领受的信仰。",
      invitation: "在混乱中持守所托付的信仰，也相信神能保守到底。",
    },
    summary: "劝信徒为真道竭力争辩。",
    keywords: ["持守", "信仰", "保守", "警醒", "犹大"],
  },
  {
    bookId: "REV",
    stageId: "new-creation",
    groupId: "revelation",
    spiritualFrame: {
      divine: "阿拉法与俄梅戛，开始与末后",
      human: "在等待中持守盼望，直到神更新万有。",
      invitation: "在患难与等待中持守盼望，仰望神最终更新万有。",
    },
    summary: "显明基督最终得胜，神更新天地。",
    keywords: ["启示", "新天新地", "羔羊", "盼望", "更新万有"],
  },
];
