import type { ScriptureBookNote } from './scriptureBookNoteTypes';

export const scriptureBookNotesOtHistory: ScriptureBookNote[] = [
{
    bookId: "GEN",
    stageId: "history-promise-kingdom",
    groupId: "beginnings-patriarchs",
    spiritualFrame: {
      divine: "创造主",
      human: "在被创造与自由中，开始认识神，也渐渐远离神。",
      invitation: "在起初、破碎与应许中，重新听见神主动寻找人的声音。",
    },
    summary: "神创造世界，人犯罪堕落，神开始拣选亚伯拉罕一家。",
    keywords: ["创造", "起初", "伊甸园", "亚伯拉罕", "约"],
  },
{
    bookId: "EXO",
    stageId: "history-promise-kingdom",
    groupId: "exodus-wilderness",
    spiritualFrame: {
      divine: "拯救者",
      human: "从奴役中被带领出来，学习信靠与跟随神。",
      invitation: "从捆绑走向敬拜，在旷野中学习跟随拯救你的神。",
    },
    summary: "神借摩西带领以色列人出埃及，并与他们立约。",
    keywords: ["拯救", "逾越节", "旷野", "西奈", "会幕"],
  },
{
    bookId: "LEV",
    stageId: "history-promise-kingdom",
    groupId: "exodus-wilderness",
    spiritualFrame: {
      divine: "圣洁的神",
      human: "学习如何分别为圣，亲近神。",
      invitation: "在圣洁与献祭中，学习以敬畏的心亲近神。",
    },
    summary: "神教导以色列人如何敬拜祂、过圣洁生活。",
    keywords: ["圣洁", "献祭", "洁净", "祭司", "亲近神"],
  },
{
    bookId: "NUM",
    stageId: "history-promise-kingdom",
    groupId: "exodus-wilderness",
    spiritualFrame: {
      divine: "旷野中的带领者",
      human: "在漂流、抱怨与软弱中，仍被神带领。",
      invitation: "在漫长绕行中学习信靠，不让软弱切断与神同行的路。",
    },
    summary: "以色列人在旷野漂流，显出人的不信和神的信实。",
    keywords: ["旷野", "漂流", "抱怨", "云柱", "信靠"],
  },
{
    bookId: "DEU",
    stageId: "history-promise-kingdom",
    groupId: "exodus-wilderness",
    spiritualFrame: {
      divine: "守约的神",
      human: "在进入应许之前，再次学习记念与顺服。",
      invitation: "在进入新的土地前，重新记念神的信实并选择顺服。",
    },
    summary: "摩西重申律法，劝百姓进入迦南后要顺服神。",
    keywords: ["守约", "记念", "顺服", "律法", "应许"],
  },
{
    bookId: "JOS",
    stageId: "history-promise-kingdom",
    groupId: "promised-land",
    spiritualFrame: {
      divine: "争战得胜的元帅",
      human: "学习依靠神进入应许之地。",
      invitation: "在应许面前刚强壮胆，凭信心进入神所赐的产业。",
    },
    summary: "以色列人进入迦南，得着神应许之地。",
    keywords: ["应许之地", "刚强壮胆", "约书亚", "争战", "产业"],
  },
{
    bookId: "JDG",
    stageId: "history-promise-kingdom",
    groupId: "promised-land",
    spiritualFrame: {
      divine: "不断施怜悯的拯救者",
      human: "一次次跌倒远离，又一次次被神挽回。",
      invitation: "在反复失败中承认需要拯救，回到施怜悯的神面前。",
    },
    summary: "以色列反复犯罪，神兴起士师拯救他们。",
    keywords: ["士师", "循环", "跌倒", "怜悯", "拯救"],
  },
{
    bookId: "RUT",
    stageId: "history-promise-kingdom",
    groupId: "promised-land",
    spiritualFrame: {
      divine: "预备与救赎的神",
      human: "在平凡、失落与等待中，经历神隐藏的恩典。",
      invitation: "在失落与平凡中留心神隐藏的预备，学习忠诚与等待。",
    },
    summary: "路得忠心跟随神，进入大卫和耶稣的家谱。",
    keywords: ["路得", "拿俄米", "波阿斯", "救赎", "恩典"],
  },
{
    bookId: "1SA",
    stageId: "history-promise-kingdom",
    groupId: "united-kingdom",
    spiritualFrame: {
      divine: "鉴察人心的神",
      human: "在人看外貌时，学习被神改变内心。",
      invitation: "把外在成败交给神，让祂塑造一颗愿意顺服的心。",
    },
    summary: "以色列开始有王，扫罗失败，大卫兴起。",
    keywords: ["撒母耳", "扫罗", "大卫", "人心", "顺服"],
  },
{
    bookId: "2SA",
    stageId: "history-promise-kingdom",
    groupId: "united-kingdom",
    spiritualFrame: {
      divine: "施恩与建立国度的神",
      human: "即使跌倒失败，仍能经历神的赦免与恢复。",
      invitation: "在失败后真实回转，重新领受神恢复生命的恩典。",
    },
    summary: "大卫作王，但他的犯罪也带来家庭和国家危机。",
    keywords: ["大卫", "国度", "恩典", "赦免", "恢复"],
  },
{
    bookId: "1KI",
    stageId: "history-promise-kingdom",
    groupId: "kingdom-history",
    spiritualFrame: {
      divine: "掌权的王",
      human: "在荣耀与丰富中，人的心开始渐渐偏离神。",
      invitation: "在荣耀与丰富里守住心，不让成功把人带离神。",
    },
    summary: "所罗门建圣殿，后来国家分裂。",
    keywords: ["所罗门", "圣殿", "王国", "偏离", "先知"],
  },
{
    bookId: "2KI",
    stageId: "history-promise-kingdom",
    groupId: "kingdom-history",
    spiritualFrame: {
      divine: "审判与呼唤回转的神",
      human: "在败坏与黑暗中，仍不断听见神的呼唤。",
      invitation: "在败坏走向尽头前，认真听见神呼唤回转的声音。",
    },
    summary: "以色列和犹大因悖逆神最终被掳。",
    keywords: ["列王", "以利亚", "以利沙", "审判", "回转"],
  },
{
    bookId: "1CH",
    stageId: "history-promise-kingdom",
    groupId: "kingdom-history",
    spiritualFrame: {
      divine: "记念祂约的神",
      human: "重新学习记念神的同在与应许。",
      invitation: "在历史回望中重新找回神的约、同在与身份。",
    },
    summary: "回顾大卫王朝，强调圣殿敬拜。",
    keywords: ["家谱", "大卫之约", "记念", "敬拜", "同在"],
  },
{
    bookId: "2CH",
    stageId: "history-promise-kingdom",
    groupId: "kingdom-history",
    spiritualFrame: {
      divine: "配得敬拜的神",
      human: "在复兴与荒凉之间，学习真实敬拜。",
      invitation: "在兴衰之间重新学习敬拜，让圣殿指向真实归向神的心。",
    },
    summary: "回顾犹大诸王，呼吁百姓归向神。",
    keywords: ["圣殿", "敬拜", "复兴", "荒凉", "归向"],
  },
{
    bookId: "EZR",
    stageId: "history-promise-kingdom",
    groupId: "return-rebuilding",
    spiritualFrame: {
      divine: "恢复敬拜的神",
      human: "重新回到神的话语与敬拜中。",
      invitation: "从荒凉中重新回到神的话语，让敬拜再次被恢复。",
    },
    summary: "被掳归回的犹太人重建圣殿。",
    keywords: ["归回", "以斯拉", "律法", "恢复", "敬拜"],
  },
{
    bookId: "NEH",
    stageId: "history-promise-kingdom",
    groupId: "return-rebuilding",
    spiritualFrame: {
      divine: "重建破碎的神",
      human: "在荒凉中重新站立起来。",
      invitation: "面对破口不再停留在哀伤里，与神同工重建。",
    },
    summary: "尼希米带领百姓重建耶路撒冷城墙。",
    keywords: ["尼希米", "城墙", "重建", "破碎", "祷告"],
  },
{
    bookId: "EST",
    stageId: "history-promise-kingdom",
    groupId: "return-rebuilding",
    spiritualFrame: {
      divine: "隐藏却仍掌权的神",
      human: "即使看不见神，仍学习信靠祂。",
      invitation: "在看不见神名字的处境里，仍相信祂暗中掌权。",
    },
    summary: "神暗中保护犹太人免于灭族。",
    keywords: ["以斯帖", "隐藏", "掌权", "拯救", "勇气"],
  },
{
    bookId: "JOB",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "在人无法理解中仍掌权的神",
      human: "在痛苦与困惑中，仍然寻找神。",
      invitation: "把无法解释的痛苦带到神面前，在困惑中仍继续寻找祂。",
    },
    summary: "探讨义人受苦，并教导人在苦难中信靠神。",
    keywords: ["痛苦", "约伯", "困惑", "掌权", "寻找"],
  }
];
