import type { AppLocale } from "../i18n/config";
import { toZhTwText } from "../i18n/site-copy";

/** English one-line summaries for canon catalog (zh source in scripture-book-notes). */
export const scriptureBookSummaryEn: Record<string, string> = {
  GEN: "God creates the world, humanity falls, and God begins His covenant through Abraham's family.",
  EXO: "Through Moses, God delivers Israel from Egypt and makes a covenant with them.",
  LEV: "God teaches Israel how to worship Him and live a holy life.",
  NUM: "In the wilderness journey, human unbelief is exposed and God's faithfulness endures.",
  DEU: "Moses restates the law and calls the people to obey God in the promised land.",
  JOS: "Israel enters Canaan and receives the land God promised.",
  JDG: "Israel repeatedly falls, and God repeatedly raises judges to rescue them.",
  RUT: "Ruth faithfully follows God and is woven into the line of David and Jesus.",
  "1SA": "Israel begins its monarchy: Saul fails and David rises.",
  "2SA": "David reigns as king, yet his sin brings deep family and national crisis.",
  "1KI": "Solomon builds the temple, and later the kingdom divides.",
  "2KI": "Because of rebellion, Israel and Judah are eventually taken into exile.",
  "1CH": "The history of David's line is retold with an emphasis on temple worship.",
  "2CH": "The kings of Judah are reviewed with a call for the people to return to God.",
  EZR: "The exiles return and rebuild the temple.",
  NEH: "Nehemiah leads the people to rebuild Jerusalem's walls.",
  EST: "God quietly protects the Jewish people from destruction.",
  JOB: "The book wrestles with righteous suffering and teaches trust in God through pain.",
  PSA: "Psalms of praise, prayer, lament, and trust are offered before God.",
  PRO: "Wisdom for fearing God and living skillfully in everyday life.",
  ECC: "Life apart from God is shown to be empty and fleeting.",
  SNG: "A poetic celebration of love and covenant marriage.",
  ISA: "Judgment and salvation are proclaimed, including promises of the Messiah.",
  JER: "Judah is warned of exile, yet God also promises a new covenant.",
  LAM: "Jerusalem's ruin is mourned while hope in God's mercy remains.",
  EZK: "In exile, God's judgment is declared alongside promises of restoration.",
  DAN: "God's rule over nations is revealed, and faithfulness under pressure is upheld.",
  HOS: "Marriage imagery shows God's unchanging love for a wayward people.",
  JOL: "The people are called to repent, and God's Spirit is promised to be poured out.",
  AMO: "Social injustice and empty worship are confronted.",
  OBA: "Edom is judged for pride and hostility toward God's people.",
  JON: "God shows mercy to the nations and teaches Jonah His compassion.",
  MIC: "Sin is rebuked and the Messiah from Bethlehem is foretold.",
  NAM: "Nineveh is warned that evil will face God's judgment.",
  HAB: "The prophet learns to live by faith amid unresolved questions.",
  ZEP: "The day of judgment is proclaimed, yet hope of restoration is given.",
  HAG: "The returned exiles are encouraged to rebuild the temple.",
  ZEC: "Temple rebuilding is encouraged, with visions of Messiah and God's kingdom.",
  MAL: "The people are rebuked for spiritual coldness, and the Lord's messenger is foretold.",
  MAT: "Jesus is presented as the promised Messiah-King.",
  MRK: "Jesus is portrayed in action as the suffering servant who rises again.",
  LUK: "Jesus is shown as the merciful Savior for sinners and all peoples.",
  JHN: "Jesus is proclaimed as the Son of God so that believers may have life.",
  ACT: "The Spirit comes, the church is born, and the gospel moves to the nations.",
  ROM: "People are justified before God through faith in Jesus.",
  "1CO": "Church division, morality, and spiritual gifts are addressed.",
  "2CO": "Paul shows that true ministry displays God's power through weakness.",
  GAL: "Salvation and freedom come through faith in Christ, not law-keeping.",
  EPH: "The church's unity and new life in Christ are unfolded.",
  PHP: "Believers are taught to rejoice in Christ and follow His example.",
  COL: "Christ is exalted as supreme and fully sufficient over all things.",
  "1TH": "Believers are encouraged toward holy living while waiting for the Lord's return.",
  "2TH": "Misunderstandings about the Lord's return are corrected with a call to faithful living.",
  "1TI": "Instructions are given for church order, leadership, and godly life.",
  "2TI": "Paul's final charge calls Timothy to endure and preach faithfully.",
  TIT: "Church elders are appointed and good works are urged as gospel witness.",
  PHM: "Philemon is asked to welcome Onesimus in gospel-shaped reconciliation.",
  HEB: "Jesus is shown as greater than all old-covenant shadows and mediator of a better covenant.",
  JAS: "Real faith is shown through obedient action.",
  "1PE": "Suffering believers are encouraged to hold fast to hope and holiness.",
  "2PE": "False teachers are warned against while believers await the Lord's return.",
  "1JN": "Believers are taught to abide in truth and love.",
  "2JN": "Believers are urged to walk in truth and guard against false teaching.",
  "3JN": "Faithful hospitality is commended while proud leadership is confronted.",
  JUD: "Believers are urged to contend for the faith once delivered.",
  REV: "Christ's final victory is revealed, and God renews heaven and earth.",
};

export function summaryLabelForLocale(
  bookId: string,
  zhSummary: string,
  locale: AppLocale,
): string {
  if (locale === "zh-TW") return toZhTwText(zhSummary);
  if (locale !== "en") return zhSummary;
  const en = scriptureBookSummaryEn[bookId.trim().toUpperCase()];
  return en?.trim() || zhSummary;
}
