export type ScriptureBookSpiritualFrame = {
  divine: string;
  human: string;
  invitation: string;
};

export type ScriptureBookNote = {
  bookId: string;
  stageId: string;
  groupId: string;
  spiritualFrame: ScriptureBookSpiritualFrame;
  summary: string;
  keywords?: string[];
  imageHint?: string;
};

export const scriptureBookNotes: ScriptureBookNote[] = [
  {
    bookId: "GEN",
    stageId: "history-promise-kingdom",
    groupId: "beginnings-patriarchs",
    spiritualFrame: {
      divine: "创造主",
      human: "在被创造与自由中，开始认识神，也渐渐远离神。",
      invitation: "在起初、破碎与应许中，重新听见神主动寻找人的声音。",
    },
    summary: "神创造世界，人犯罪堕落，神开始拣选亚伯拉罕一家。",
    keywords: ["创造", "起初", "伊甸园", "亚伯拉罕", "约"],
  },
  {
    bookId: "EXO",
    stageId: "history-promise-kingdom",
    groupId: "exodus-wilderness",
    spiritualFrame: {
      divine: "拯救者",
      human: "从奴役中被带领出来，学习信靠与跟随神。",
      invitation: "从捆绑走向敬拜，在旷野中学习跟随拯救你的神。",
    },
    summary: "神借摩西带领以色列人出埃及，并与他们立约。",
    keywords: ["拯救", "逾越节", "旷野", "西奈", "会幕"],
  },
  {
    bookId: "LEV",
    stageId: "history-promise-kingdom",
    groupId: "exodus-wilderness",
    spiritualFrame: {
      divine: "圣洁的神",
      human: "学习如何分别为圣，亲近神。",
      invitation: "在圣洁与献祭中，学习以敬畏的心亲近神。",
    },
    summary: "神教导以色列人如何敬拜祂、过圣洁生活。",
    keywords: ["圣洁", "献祭", "洁净", "祭司", "亲近神"],
  },
  {
    bookId: "NUM",
    stageId: "history-promise-kingdom",
    groupId: "exodus-wilderness",
    spiritualFrame: {
      divine: "旷野中的带领者",
      human: "在漂流、抱怨与软弱中，仍被神带领。",
      invitation: "在漫长绕行中学习信靠，不让软弱切断与神同行的路。",
    },
    summary: "以色列人在旷野漂流，显出人的不信和神的信实。",
    keywords: ["旷野", "漂流", "抱怨", "云柱", "信靠"],
  },
  {
    bookId: "DEU",
    stageId: "history-promise-kingdom",
    groupId: "exodus-wilderness",
    spiritualFrame: {
      divine: "守约的神",
      human: "在进入应许之前，再次学习记念与顺服。",
      invitation: "在进入新的土地前，重新记念神的信实并选择顺服。",
    },
    summary: "摩西重申律法，劝百姓进入迦南后要顺服神。",
    keywords: ["守约", "记念", "顺服", "律法", "应许"],
  },
  {
    bookId: "JOS",
    stageId: "history-promise-kingdom",
    groupId: "promised-land",
    spiritualFrame: {
      divine: "争战得胜的元帅",
      human: "学习依靠神进入应许之地。",
      invitation: "在应许面前刚强壮胆，凭信心进入神所赐的产业。",
    },
    summary: "以色列人进入迦南，得着神应许之地。",
    keywords: ["应许之地", "刚强壮胆", "约书亚", "争战", "产业"],
  },
  {
    bookId: "JDG",
    stageId: "history-promise-kingdom",
    groupId: "promised-land",
    spiritualFrame: {
      divine: "不断施怜悯的拯救者",
      human: "一次次跌倒远离，又一次次被神挽回。",
      invitation: "在反复失败中承认需要拯救，回到施怜悯的神面前。",
    },
    summary: "以色列反复犯罪，神兴起士师拯救他们。",
    keywords: ["士师", "循环", "跌倒", "怜悯", "拯救"],
  },
  {
    bookId: "RUT",
    stageId: "history-promise-kingdom",
    groupId: "promised-land",
    spiritualFrame: {
      divine: "预备与救赎的神",
      human: "在平凡、失落与等待中，经历神隐藏的恩典。",
      invitation: "在失落与平凡中留心神隐藏的预备，学习忠诚与等待。",
    },
    summary: "路得忠心跟随神，进入大卫和耶稣的家谱。",
    keywords: ["路得", "拿俄米", "波阿斯", "救赎", "恩典"],
  },
  {
    bookId: "1SA",
    stageId: "history-promise-kingdom",
    groupId: "united-kingdom",
    spiritualFrame: {
      divine: "鉴察人心的神",
      human: "在人看外貌时，学习被神改变内心。",
      invitation: "把外在成败交给神，让祂塑造一颗愿意顺服的心。",
    },
    summary: "以色列开始有王，扫罗失败，大卫兴起。",
    keywords: ["撒母耳", "扫罗", "大卫", "人心", "顺服"],
  },
  {
    bookId: "2SA",
    stageId: "history-promise-kingdom",
    groupId: "united-kingdom",
    spiritualFrame: {
      divine: "施恩与建立国度的神",
      human: "即使跌倒失败，仍能经历神的赦免与恢复。",
      invitation: "在失败后真实回转，重新领受神恢复生命的恩典。",
    },
    summary: "大卫作王，但他的犯罪也带来家庭和国家危机。",
    keywords: ["大卫", "国度", "恩典", "赦免", "恢复"],
  },
  {
    bookId: "1KI",
    stageId: "history-promise-kingdom",
    groupId: "kingdom-history",
    spiritualFrame: {
      divine: "掌权的王",
      human: "在荣耀与丰富中，人的心开始渐渐偏离神。",
      invitation: "在荣耀与丰富里守住心，不让成功把人带离神。",
    },
    summary: "所罗门建圣殿，后来国家分裂。",
    keywords: ["所罗门", "圣殿", "王国", "偏离", "先知"],
  },
  {
    bookId: "2KI",
    stageId: "history-promise-kingdom",
    groupId: "kingdom-history",
    spiritualFrame: {
      divine: "审判与呼唤回转的神",
      human: "在败坏与黑暗中，仍不断听见神的呼唤。",
      invitation: "在败坏走向尽头前，认真听见神呼唤回转的声音。",
    },
    summary: "以色列和犹大因悖逆神最终被掳。",
    keywords: ["列王", "以利亚", "以利沙", "审判", "回转"],
  },
  {
    bookId: "1CH",
    stageId: "history-promise-kingdom",
    groupId: "kingdom-history",
    spiritualFrame: {
      divine: "记念祂约的神",
      human: "重新学习记念神的同在与应许。",
      invitation: "在历史回望中重新找回神的约、同在与身份。",
    },
    summary: "回顾大卫王朝，强调圣殿敬拜。",
    keywords: ["家谱", "大卫之约", "记念", "敬拜", "同在"],
  },
  {
    bookId: "2CH",
    stageId: "history-promise-kingdom",
    groupId: "kingdom-history",
    spiritualFrame: {
      divine: "配得敬拜的神",
      human: "在复兴与荒凉之间，学习真实敬拜。",
      invitation: "在兴衰之间重新学习敬拜，让圣殿指向真实归向神的心。",
    },
    summary: "回顾犹大诸王，呼吁百姓归向神。",
    keywords: ["圣殿", "敬拜", "复兴", "荒凉", "归向"],
  },
  {
    bookId: "EZR",
    stageId: "history-promise-kingdom",
    groupId: "return-rebuilding",
    spiritualFrame: {
      divine: "恢复敬拜的神",
      human: "重新回到神的话语与敬拜中。",
      invitation: "从荒凉中重新回到神的话语，让敬拜再次被恢复。",
    },
    summary: "被掳归回的犹太人重建圣殿。",
    keywords: ["归回", "以斯拉", "律法", "恢复", "敬拜"],
  },
  {
    bookId: "NEH",
    stageId: "history-promise-kingdom",
    groupId: "return-rebuilding",
    spiritualFrame: {
      divine: "重建破碎的神",
      human: "在荒凉中重新站立起来。",
      invitation: "面对破口不再停留在哀伤里，与神同工重建。",
    },
    summary: "尼希米带领百姓重建耶路撒冷城墙。",
    keywords: ["尼希米", "城墙", "重建", "破碎", "祷告"],
  },
  {
    bookId: "EST",
    stageId: "history-promise-kingdom",
    groupId: "return-rebuilding",
    spiritualFrame: {
      divine: "隐藏却仍掌权的神",
      human: "即使看不见神，仍学习信靠祂。",
      invitation: "在看不见神名字的处境里，仍相信祂暗中掌权。",
    },
    summary: "神暗中保护犹太人免于灭族。",
    keywords: ["以斯帖", "隐藏", "掌权", "拯救", "勇气"],
  },
  {
    bookId: "JOB",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "在人无法理解中仍掌权的神",
      human: "在痛苦与困惑中，仍然寻找神。",
      invitation: "把无法解释的痛苦带到神面前，在困惑中仍继续寻找祂。",
    },
    summary: "探讨义人受苦，并教导人在苦难中信靠神。",
    keywords: ["痛苦", "约伯", "困惑", "掌权", "寻找"],
  },
  {
    bookId: "PSA",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "牧者、磐石、避难所",
      human: "在喜乐、忧伤与黑夜中，向神倾心吐意。",
      invitation: "把整颗心带到神面前，在赞美与哀歌中学习祷告。",
    },
    summary: "用诗歌表达赞美、祷告、哀求和信靠。",
    keywords: ["诗歌", "祷告", "牧者", "避难所", "赞美"],
  },
  {
    bookId: "PRO",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "智慧的源头",
      human: "学习在生活中敬畏神、活出智慧。",
      invitation: "在日常选择里敬畏神，让智慧进入生活细节。",
    },
    summary: "教导人敬畏神，活出智慧人生。",
    keywords: ["智慧", "敬畏神", "生活", "选择", "训诲"],
  },
  {
    bookId: "ECC",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "永恒的主",
      human: "在短暂与虚空中，重新寻找生命意义。",
      invitation: "穿过日光之下的虚空，回到敬畏神的生命中心。",
    },
    summary: "说明离开神的人生终究虚空。",
    keywords: ["虚空", "意义", "日光之下", "永恒", "敬畏"],
  },
  {
    bookId: "SNG",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "爱的源头",
      human: "在爱与被爱中，经历关系的美好。",
      invitation: "在爱与被爱中学习珍惜、忠贞与彼此属于。",
    },
    summary: "描写爱情与婚姻之美。",
    keywords: ["爱情", "盟约", "亲密", "忠贞", "美好"],
  },
  {
    bookId: "ISA",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "圣者与救赎主",
      human: "在黑暗与审判中，仍等待神的光。",
      invitation: "在审判中仰望救赎主，等候神应许的光。",
    },
    summary: "宣告审判和拯救，并预言弥赛亚。",
    keywords: ["圣者", "救赎主", "以马内利", "仆人", "盼望"],
  },
  {
    bookId: "JER",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "仍然呼唤人归回的神",
      human: "即使悖逆远离，仍被神不断呼唤。",
      invitation: "在悖逆中听见神带泪的呼唤，重新归回祂。",
    },
    summary: "警告犹大将被掳，也应许新约。",
    keywords: ["归回", "耶利米", "新约", "眼泪", "悖逆"],
  },
  {
    bookId: "LAM",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "人在废墟中的盼望",
      human: "在失去与眼泪中，重新仰望神。",
      invitation: "在废墟和眼泪里，不让悲伤终止对神怜悯的盼望。",
    },
    summary: "为耶路撒冷被毁哀哭，同时仰望神怜悯。",
    keywords: ["哀歌", "废墟", "眼泪", "怜悯", "盼望"],
  },
  {
    bookId: "EZK",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "荣耀仍然同在的神",
      human: "即使身处被掳之地，仍学习相信神没有离开。",
      invitation: "在被掳与破碎中，相信神的荣耀仍能临到枯干之处。",
    },
    summary: "在被掳中宣告神的审判和复兴。",
    keywords: ["荣耀", "被掳", "枯骨", "新心", "以西结"],
  },
  {
    bookId: "DAN",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "掌管列国的至高者",
      human: "在异邦世界里，仍忠心跟随神。",
      invitation: "在陌生权势中持守忠心，相信至高者掌管列国。",
    },
    summary: "显明神掌管列国，忠心的人应信靠祂。",
    keywords: ["但以理", "忠心", "列国", "异邦", "异象"],
  },
  {
    bookId: "HOS",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "永不放弃的爱",
      human: "即使不断离弃，仍被神深爱。",
      invitation: "在反复离弃后仍回到那位坚持爱人的神面前。",
    },
    summary: "用婚姻比喻神对悖逆百姓不变的爱。",
    keywords: ["何西阿", "慈爱", "不忠", "归回", "盟约"],
  },
  {
    bookId: "JOL",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "赐下圣灵的神",
      human: "在荒凉之后，被呼唤重新归向神。",
      invitation: "在荒凉之后撕裂心肠归向神，等候祂赐下圣灵。",
    },
    summary: "呼吁悔改，并预言神的灵浇灌。",
    keywords: ["圣灵", "回转", "荒凉", "约珥", "耶和华的日子"],
  },
  {
    bookId: "AMO",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "公义的神",
      human: "学习真正的敬拜不是外表，而是公义与怜悯。",
      invitation: "让敬拜离开空壳，使公义如江河在生活中流出。",
    },
    summary: "责备社会不公和虚假敬拜。",
    keywords: ["公义", "敬拜", "怜悯", "贫弱", "审判"],
  },
  {
    bookId: "OBA",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "降卑骄傲者的神",
      human: "骄傲终将被拆毁。",
      invitation: "离开旁观与骄傲，学习在神面前降卑。",
    },
    summary: "宣告以东因骄傲和敌对神子民受审判。",
    keywords: ["骄傲", "以东", "降卑", "审判", "俄巴底亚"],
  },
  {
    bookId: "JON",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "怜悯万民的神",
      human: "学习放下自己的狭窄与偏见。",
      invitation: "让神扩张你的怜悯，接纳祂也怜悯你不愿接纳的人。",
    },
    summary: "神怜悯外邦人，也教导约拿认识祂的慈爱。",
    keywords: ["约拿", "尼尼微", "怜悯", "偏见", "万民"],
  },
  {
    bookId: "MIC",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "喜爱怜悯的神",
      human: "被呼唤活出公义、谦卑与怜悯。",
      invitation: "行公义、好怜悯，存谦卑的心与神同行。",
    },
    summary: "责备罪恶，也预言弥赛亚将从伯利恒而来。",
    keywords: ["公义", "怜悯", "谦卑", "弥迦", "同行"],
  },
  {
    bookId: "NAM",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "审判邪恶的神",
      human: "在混乱与暴力中，仍盼望神的公义。",
      invitation: "在邪恶似乎得势时，仍把盼望放在神最终的公义上。",
    },
    summary: "宣告尼尼微因邪恶必受审判。",
    keywords: ["那鸿", "尼尼微", "邪恶", "审判", "公义"],
  },
  {
    bookId: "HAB",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "义人所信靠的神",
      human: "即使不明白，也学习凭信心而活。",
      invitation: "把疑问带到神面前，在不明白中仍因信而活。",
    },
    summary: "先知在疑问中学习因信而活。",
    keywords: ["哈巴谷", "疑问", "信心", "义人", "等候"],
  },
  {
    bookId: "ZEP",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "仍然喜乐爱人的神",
      human: "在审判之后，仍被神重新恢复。",
      invitation: "在审判的严肃中等候恢复，听见神以爱为你欢呼。",
    },
    summary: "宣告神审判的日子，也赐下复兴盼望。",
    keywords: ["西番雅", "审判", "恢复", "喜乐", "余民"],
  },
  {
    bookId: "HAG",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "呼唤人重新以祂为中心的神",
      human: "重新把神放回生命中心。",
      invitation: "停下只顾自己的建造，重新把神放在生命中心。",
    },
    summary: "鼓励归回百姓重建圣殿。",
    keywords: ["哈该", "圣殿", "中心", "优先次序", "重建"],
  },
  {
    bookId: "ZEC",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "赐下盼望与异象的神",
      human: "在软弱与等待中，继续仰望神。",
      invitation: "在微小与等待中继续仰望，领受神赐下的盼望异象。",
    },
    summary: "鼓励重建圣殿，并预言弥赛亚和神国。",
    keywords: ["撒迦利亚", "异象", "盼望", "重建", "弥赛亚"],
  },
  {
    bookId: "MAL",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "信实不改变的神",
      human: "在冷淡之后，再次归向神。",
      invitation: "在属灵冷淡中重新归向那位信实不改变的神。",
    },
    summary: "责备百姓冷淡，预告主的使者将来。",
    keywords: ["玛拉基", "信实", "冷淡", "归向", "等候"],
  },
  {
    bookId: "MAT",
    stageId: "christ-advent",
    groupId: "gospels",
    spiritualFrame: {
      divine: "应许中的君王",
      human: "迎接神真正的国度来到。",
      invitation: "迎接应许中的君王，进入天国临近的新现实。",
    },
    summary: "证明耶稣是应许中的弥赛亚君王。",
    keywords: ["君王", "天国", "马太", "应许", "弥赛亚"],
  },
  {
    bookId: "MRK",
    stageId: "christ-advent",
    groupId: "gospels",
    spiritualFrame: {
      divine: "服事人的仆人君王",
      human: "学习跟随耶稣走舍己服事的道路。",
      invitation: "跟随舍己服事的主，在行动中认识神儿子的权柄与爱。",
    },
    summary: "描写耶稣以行动服事、受苦并复活。",
    keywords: ["仆人", "舍己", "马可", "服事", "跟随"],
  },
  {
    bookId: "LUK",
    stageId: "christ-advent",
    groupId: "gospels",
    spiritualFrame: {
      divine: "充满怜悯的救主",
      human: "在软弱中经历神的怜悯。",
      invitation: "让耶稣走近你的软弱，在祂怜悯里重新被看见。",
    },
    summary: "强调耶稣是怜悯罪人和万民的救主。",
    keywords: ["怜悯", "救主", "路加", "软弱", "福音"],
  },
  {
    bookId: "JHN",
    stageId: "christ-advent",
    groupId: "gospels",
    spiritualFrame: {
      divine: "生命的光",
      human: "在黑暗中走向真正的生命。",
      invitation: "走向那位道成肉身的生命之光，在祂里面得生命。",
    },
    summary: "宣告耶稣是神的儿子，使信祂的人得生命。",
    keywords: ["生命", "光", "道成肉身", "约翰", "相信"],
  },
  {
    bookId: "ACT",
    stageId: "church-spirit-epistles",
    groupId: "church-history",
    spiritualFrame: {
      divine: "借着圣灵运行的神",
      human: "顺着圣灵，把福音带向世界。",
      invitation: "顺服圣灵的推动，让福音从近处走向万民。",
    },
    summary: "圣灵降临，教会建立，福音传向外邦。",
    keywords: ["圣灵", "教会", "宣教", "使徒", "福音"],
  },
  {
    bookId: "ROM",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "使人称义的神",
      human: "因信重新与神和好。",
      invitation: "离开自义与定罪，凭信进入与神和好的恩典。",
    },
    summary: "说明人因信耶稣被神称义。",
    keywords: ["称义", "信心", "恩典", "罗马书", "和好"],
  },
  {
    bookId: "1CO",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "使教会合一的神",
      human: "在混乱中重新学习爱。",
      invitation: "在分裂与混乱中回到十字架，重新学习爱与合一。",
    },
    summary: "处理教会分裂、道德和属灵恩赐等问题。",
    keywords: ["教会", "合一", "爱", "恩赐", "十字架"],
  },
  {
    bookId: "2CO",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "在软弱中显出能力的神",
      human: "在软弱里经历神真正的能力。",
      invitation: "不再逃避软弱，让基督的能力在瓦器里显明。",
    },
    summary: "保罗说明真正的使徒服事是在软弱中显出神能力。",
    keywords: ["软弱", "能力", "安慰", "和好", "瓦器"],
  },
  {
    bookId: "GAL",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "使人得自由的神",
      human: "离开捆绑，活在恩典中。",
      invitation: "从靠行为证明自己中出来，活在基督释放的自由里。",
    },
    summary: "强调得救靠信基督，不靠守律法。",
    keywords: ["自由", "恩典", "律法", "圣灵", "加拉太"],
  },
  {
    bookId: "EPH",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "建立基督身体的神",
      human: "学习彼此连接，成为一个身体。",
      invitation: "在基督里认识新的身份，与众圣徒一同被建造。",
    },
    summary: "说明教会在基督里的合一和新生命。",
    keywords: ["基督身体", "教会", "身份", "合一", "建造"],
  },
  {
    bookId: "PHP",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "赐人喜乐与平安的神",
      human: "即使在困境中，仍然喜乐。",
      invitation: "在困境中以基督为至宝，学习不被环境夺去喜乐。",
    },
    summary: "教导信徒在基督里喜乐并效法祂。",
    keywords: ["喜乐", "平安", "基督", "困境", "腓立比"],
  },
  {
    bookId: "COL",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "超越万有的主",
      human: "让基督成为生命真正的中心。",
      invitation: "让超越万有的基督成为思想、生活与关系的中心。",
    },
    summary: "高举基督超越万有、完全充足。",
    keywords: ["基督", "万有", "中心", "新人", "歌罗西"],
  },
  {
    bookId: "1TH",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "将再来的主",
      human: "在等待中持守盼望。",
      invitation: "在等候主再来时，以信心、爱心与盼望生活。",
    },
    summary: "鼓励信徒圣洁生活，等候主再来。",
    keywords: ["再来", "盼望", "等候", "圣洁", "帖撒罗尼迦"],
  },
  {
    bookId: "2TH",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "掌管末后的主",
      human: "在混乱中仍坚定信心。",
      invitation: "在末世混乱与误解中安静持守，忠心生活。",
    },
    summary: "澄清主再来的误解，劝信徒忠心生活。",
    keywords: ["末后", "坚定", "混乱", "信心", "忍耐"],
  },
  {
    bookId: "1TI",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "托付真道的神",
      human: "忠心牧养并守护真理。",
      invitation: "在教会生活中守护真道，以忠心牧养神的群羊。",
    },
    summary: "教导教会治理、领袖资格和敬虔生活。",
    keywords: ["真道", "牧养", "教会", "忠心", "提摩太"],
  },
  {
    bookId: "2TI",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "值得人忠心到底的神",
      human: "即使走到尽头，也持守所信。",
      invitation: "在疲惫与临别中继续守住所信，忠心到底。",
    },
    summary: "保罗临终前劝提摩太忠心传道。",
    keywords: ["忠心到底", "圣经", "苦难", "传道", "持守"],
  },
  {
    bookId: "TIT",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "更新生命的神",
      human: "活出被福音更新后的生命。",
      invitation: "让福音不止停在口中，而是更新品格与生活。",
    },
    summary: "教导设立长老，并以善行见证信仰。",
    keywords: ["更新", "善行", "教会秩序", "生命", "提多"],
  },
  {
    bookId: "PHM",
    stageId: "church-spirit-epistles",
    groupId: "paul-letters",
    spiritualFrame: {
      divine: "使人和好的神",
      human: "在关系中学习饶恕与和好。",
      invitation: "让福音进入具体关系，学习接纳、饶恕与和好。",
    },
    summary: "请求腓利门接纳悔改归主的阿尼西母。",
    keywords: ["和好", "饶恕", "关系", "阿尼西母", "腓利门"],
  },
  {
    bookId: "HEB",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "更美之约的大祭司",
      human: "定睛仰望基督，不再后退。",
      invitation: "在疲惫与试探中定睛基督，进入更美之约的稳固盼望。",
    },
    summary: "说明耶稣超越旧约一切，是更美之约的中保。",
    keywords: ["大祭司", "更美之约", "信心", "忍耐", "基督"],
  },
  {
    bookId: "JAS",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "使信心活出来的神",
      human: "让信心真实进入生活。",
      invitation: "让信心从言语进入行动，在生活里显出真实生命。",
    },
    summary: "强调真实信心会表现为行为。",
    keywords: ["信心", "行为", "试炼", "言语", "智慧"],
  },
  {
    bookId: "1PE",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "苦难中的盼望",
      human: "在苦难中仍持守盼望。",
      invitation: "在寄居与苦难中持守圣洁，活在复活带来的盼望里。",
    },
    summary: "鼓励受苦信徒持守盼望和圣洁。",
    keywords: ["苦难", "盼望", "寄居", "圣洁", "彼得"],
  },
  {
    bookId: "2PE",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "真实可信的主",
      human: "在混乱中持守真理。",
      invitation: "在谎言与混乱中扎根真理，等候主真实可信的应许。",
    },
    summary: "警告假教师，提醒信徒等候主再来。",
    keywords: ["真理", "假教师", "应许", "等候", "警醒"],
  },
  {
    bookId: "1JN",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "爱",
      human: "学习住在爱里，也彼此相爱。",
      invitation: "住在神的爱与光中，让彼此相爱成为真实生命的记号。",
    },
    summary: "教导信徒住在真理和爱中。",
    keywords: ["爱", "光", "相交", "确据", "约翰"],
  },
  {
    bookId: "2JN",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "真理中的神",
      human: "在真理与爱中同行。",
      invitation: "不把爱和真理拆开，在真理中彼此相爱。",
    },
    summary: "劝信徒持守真理并防备假教导。",
    keywords: ["真理", "爱", "同行", "持守", "接待"],
  },
  {
    bookId: "3JN",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "在真实关系中同在的神",
      human: "在平凡关系里活出真理。",
      invitation: "在接待、同工与真实关系中，让真理成为可见的生命。",
    },
    summary: "称赞接待真传道人，批评骄傲的领袖。",
    keywords: ["接待", "真理", "同工", "关系", "忠心"],
  },
  {
    bookId: "JUD",
    stageId: "church-spirit-epistles",
    groupId: "general-letters",
    spiritualFrame: {
      divine: "保守人到底的神",
      human: "竭力持守已经领受的信仰。",
      invitation: "在混乱中持守所托付的信仰，也相信神能保守到底。",
    },
    summary: "劝信徒为真道竭力争辩。",
    keywords: ["持守", "信仰", "保守", "警醒", "犹大"],
  },
  {
    bookId: "REV",
    stageId: "new-creation",
    groupId: "revelation",
    spiritualFrame: {
      divine: "阿拉法与俄梅戛，开始与末后",
      human: "在等待中持守盼望，直到神更新万有。",
      invitation: "在患难与等待中持守盼望，仰望神最终更新万有。",
    },
    summary: "显明基督最终得胜，神更新天地。",
    keywords: ["启示", "新天新地", "羔羊", "盼望", "更新万有"],
  },
];
