import type { ScriptureBookNote } from './scriptureBookNoteTypes';

export const scriptureBookNotesOtPoetry: ScriptureBookNote[] = [
{
    bookId: "PSA",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "牧者、磐石、避难所",
      human: "在喜乐、忧伤与黑夜中，向神倾心吐意。",
      invitation: "把整颗心带到神面前，在赞美与哀歌中学习祷告。",
    },
    summary: "用诗歌表达赞美、祷告、哀求和信靠。",
    keywords: ["诗歌", "祷告", "牧者", "避难所", "赞美"],
  },
{
    bookId: "PRO",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "智慧的源头",
      human: "学习在生活中敬畏神、活出智慧。",
      invitation: "在日常选择里敬畏神，让智慧进入生活细节。",
    },
    summary: "教导人敬畏神，活出智慧人生。",
    keywords: ["智慧", "敬畏神", "生活", "选择", "训诲"],
  },
{
    bookId: "ECC",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "永恒的主",
      human: "在短暂与虚空中，重新寻找生命意义。",
      invitation: "穿过日光之下的虚空，回到敬畏神的生命中心。",
    },
    summary: "说明离开神的人生终究虚空。",
    keywords: ["虚空", "意义", "日光之下", "永恒", "敬畏"],
  },
{
    bookId: "SNG",
    stageId: "wisdom-poetry-life",
    groupId: "wisdom-poetry",
    spiritualFrame: {
      divine: "爱的源头",
      human: "在爱与被爱中，经历关系的美好。",
      invitation: "在爱与被爱中学习珍惜、忠贞与彼此属于。",
    },
    summary: "描写爱情与婚姻之美。",
    keywords: ["爱情", "盟约", "亲密", "忠贞", "美好"],
  },
{
    bookId: "ISA",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "圣者与救赎主",
      human: "在黑暗与审判中，仍等待神的光。",
      invitation: "在审判中仰望救赎主，等候神应许的光。",
    },
    summary: "宣告审判和拯救，并预言弥赛亚。",
    keywords: ["圣者", "救赎主", "以马内利", "仆人", "盼望"],
  },
{
    bookId: "JER",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "仍然呼唤人归回的神",
      human: "即使悖逆远离，仍被神不断呼唤。",
      invitation: "在悖逆中听见神带泪的呼唤，重新归回祂。",
    },
    summary: "警告犹大将被掳，也应许新约。",
    keywords: ["归回", "耶利米", "新约", "眼泪", "悖逆"],
  },
{
    bookId: "LAM",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "人在废墟中的盼望",
      human: "在失去与眼泪中，重新仰望神。",
      invitation: "在废墟和眼泪里，不让悲伤终止对神怜悯的盼望。",
    },
    summary: "为耶路撒冷被毁哀哭，同时仰望神怜悯。",
    keywords: ["哀歌", "废墟", "眼泪", "怜悯", "盼望"],
  },
{
    bookId: "EZK",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "荣耀仍然同在的神",
      human: "即使身处被掳之地，仍学习相信神没有离开。",
      invitation: "在被掳与破碎中，相信神的荣耀仍能临到枯干之处。",
    },
    summary: "在被掳中宣告神的审判和复兴。",
    keywords: ["荣耀", "被掳", "枯骨", "新心", "以西结"],
  },
{
    bookId: "DAN",
    stageId: "prophets-judgment-hope",
    groupId: "major-prophets",
    spiritualFrame: {
      divine: "掌管列国的至高者",
      human: "在异邦世界里，仍忠心跟随神。",
      invitation: "在陌生权势中持守忠心，相信至高者掌管列国。",
    },
    summary: "显明神掌管列国，忠心的人应信靠祂。",
    keywords: ["但以理", "忠心", "列国", "异邦", "异象"],
  },
{
    bookId: "HOS",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "永不放弃的爱",
      human: "即使不断离弃，仍被神深爱。",
      invitation: "在反复离弃后仍回到那位坚持爱人的神面前。",
    },
    summary: "用婚姻比喻神对悖逆百姓不变的爱。",
    keywords: ["何西阿", "慈爱", "不忠", "归回", "盟约"],
  },
{
    bookId: "JOL",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "赐下圣灵的神",
      human: "在荒凉之后，被呼唤重新归向神。",
      invitation: "在荒凉之后撕裂心肠归向神，等候祂赐下圣灵。",
    },
    summary: "呼吁悔改，并预言神的灵浇灌。",
    keywords: ["圣灵", "回转", "荒凉", "约珥", "耶和华的日子"],
  },
{
    bookId: "AMO",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "公义的神",
      human: "学习真正的敬拜不是外表，而是公义与怜悯。",
      invitation: "让敬拜离开空壳，使公义如江河在生活中流出。",
    },
    summary: "责备社会不公和虚假敬拜。",
    keywords: ["公义", "敬拜", "怜悯", "贫弱", "审判"],
  },
{
    bookId: "OBA",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "降卑骄傲者的神",
      human: "骄傲终将被拆毁。",
      invitation: "离开旁观与骄傲，学习在神面前降卑。",
    },
    summary: "宣告以东因骄傲和敌对神子民受审判。",
    keywords: ["骄傲", "以东", "降卑", "审判", "俄巴底亚"],
  },
{
    bookId: "JON",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "怜悯万民的神",
      human: "学习放下自己的狭窄与偏见。",
      invitation: "让神扩张你的怜悯，接纳祂也怜悯你不愿接纳的人。",
    },
    summary: "神怜悯外邦人，也教导约拿认识祂的慈爱。",
    keywords: ["约拿", "尼尼微", "怜悯", "偏见", "万民"],
  },
{
    bookId: "MIC",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "喜爱怜悯的神",
      human: "被呼唤活出公义、谦卑与怜悯。",
      invitation: "行公义、好怜悯，存谦卑的心与神同行。",
    },
    summary: "责备罪恶，也预言弥赛亚将从伯利恒而来。",
    keywords: ["公义", "怜悯", "谦卑", "弥迦", "同行"],
  },
{
    bookId: "NAM",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "审判邪恶的神",
      human: "在混乱与暴力中，仍盼望神的公义。",
      invitation: "在邪恶似乎得势时，仍把盼望放在神最终的公义上。",
    },
    summary: "宣告尼尼微因邪恶必受审判。",
    keywords: ["那鸿", "尼尼微", "邪恶", "审判", "公义"],
  },
{
    bookId: "HAB",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "义人所信靠的神",
      human: "即使不明白，也学习凭信心而活。",
      invitation: "把疑问带到神面前，在不明白中仍因信而活。",
    },
    summary: "先知在疑问中学习因信而活。",
    keywords: ["哈巴谷", "疑问", "信心", "义人", "等候"],
  },
{
    bookId: "ZEP",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "仍然喜乐爱人的神",
      human: "在审判之后，仍被神重新恢复。",
      invitation: "在审判的严肃中等候恢复，听见神以爱为你欢呼。",
    },
    summary: "宣告神审判的日子，也赐下复兴盼望。",
    keywords: ["西番雅", "审判", "恢复", "喜乐", "余民"],
  },
{
    bookId: "HAG",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "呼唤人重新以祂为中心的神",
      human: "重新把神放回生命中心。",
      invitation: "停下只顾自己的建造，重新把神放在生命中心。",
    },
    summary: "鼓励归回百姓重建圣殿。",
    keywords: ["哈该", "圣殿", "中心", "优先次序", "重建"],
  },
{
    bookId: "ZEC",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "赐下盼望与异象的神",
      human: "在软弱与等待中，继续仰望神。",
      invitation: "在微小与等待中继续仰望，领受神赐下的盼望异象。",
    },
    summary: "鼓励重建圣殿，并预言弥赛亚和神国。",
    keywords: ["撒迦利亚", "异象", "盼望", "重建", "弥赛亚"],
  },
{
    bookId: "MAL",
    stageId: "prophets-judgment-hope",
    groupId: "minor-prophets",
    spiritualFrame: {
      divine: "信实不改变的神",
      human: "在冷淡之后，再次归向神。",
      invitation: "在属灵冷淡中重新归向那位信实不改变的神。",
    },
    summary: "责备百姓冷淡，预告主的使者将来。",
    keywords: ["玛拉基", "信实", "冷淡", "归向", "等候"],
  }
];
