import { BREATH_RING_WRAP_HEIGHT, BREATH_RING_WRAP_MARGIN_BOTTOM } from "./musicAlbumVisualConstants";

export const musicAlbumVisualCoreStyleDefs = {
  centerVisualLandscape: {
    marginBottom: 0,
  },
  breathRingWrap: {
    width: 220,
    height: BREATH_RING_WRAP_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: BREATH_RING_WRAP_MARGIN_BOTTOM,
  },
  coffeeWrap: {
    width: 220,
    height: BREATH_RING_WRAP_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: BREATH_RING_WRAP_MARGIN_BOTTOM,
  },
  coffeeGlow: {
    position: "absolute",
    width: 98,
    height: 98,
    borderRadius: 999,
    backgroundColor: "rgba(255,245,232,0.28)",
    shadowColor: "#fff3e6",
    shadowOpacity: 0.95,
    shadowRadius: 34,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  coffeeCupIcon: {
    textShadowColor: "rgba(255,245,232,0.5)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 0 },
  },
  sleepMoonWrap: {
    width: 220,
    height: BREATH_RING_WRAP_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: BREATH_RING_WRAP_MARGIN_BOTTOM + 24,
  },
  sleepMoonImage: {
    width: 86,
    height: 86,
    tintColor: "rgba(229,242,255,0.98)",
  },
  breathPulseCircle: {
    position: "absolute",
    width: 154,
    height: 154,
    borderRadius: 999,
    backgroundColor: "rgba(234,238,244,0.84)",
    shadowColor: "#d6deea",
    shadowOpacity: 0.9,
    shadowRadius: 64,
    shadowOffset: { width: 0, height: 0 },
    elevation: 9,
    overflow: "hidden",
  },
  breathPulseGlow: {
    position: "absolute",
    width: 182,
    height: 182,
    borderRadius: 999,
    backgroundColor: "rgba(217,229,243,0.34)",
    shadowColor: "#d7e6f6",
    shadowOpacity: 1,
    shadowRadius: 72,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
} as const;
