import { useMemo } from "react";
import type { MusicPlaybackContextValue } from "./musicPlaybackContextTypes";
import {
  buildMusicPlaybackContextValue,
  type MusicPlaybackContextValueArgs,
} from "./musicPlaybackContextValueBuild";

export function useMusicPlaybackContextValue(args: MusicPlaybackContextValueArgs): MusicPlaybackContextValue {
  const {
    store,
    tracks,
    trackIndex,
    playing,
    loading,
    playbackMode,
    musicCurrentSec,
    musicDurationSec,
    canTogglePlayback,
    scriptureCurrentSec,
    scriptureDurationSec,
    readChapterAudioAvailable,
    scripturePreparing,
    scriptureAudioRepeatMode,
    setScriptureAudioRepeatMode,
    scripturePlaybackRate,
    setScripturePlaybackRate,
    seekRatio,
    shell,
    setMusicGain,
    musicRepeatMode,
    setMusicRepeatMode,
    toggleMusicRepeatOne,
    toggleMusicRepeatAll,
    sleepTimerMinutes,
    setSleepTimerMinutes,
    musicCatalogUpdateAvailable,
    checkMusicCatalogUpdate,
    downloadMusicCatalogUpdate,
    downloadingTrackId,
  } = args;

  return useMemo(
    () =>
      buildMusicPlaybackContextValue({
        store,
        tracks,
        trackIndex,
        playing,
        loading,
        playbackMode,
        musicCurrentSec,
        musicDurationSec,
        canTogglePlayback,
        scriptureCurrentSec,
        scriptureDurationSec,
        readChapterAudioAvailable,
        scripturePreparing,
        scriptureAudioRepeatMode,
        setScriptureAudioRepeatMode,
        scripturePlaybackRate,
        setScripturePlaybackRate,
        seekRatio,
        shell,
        setMusicGain,
        musicRepeatMode,
        setMusicRepeatMode,
        toggleMusicRepeatOne,
        toggleMusicRepeatAll,
        sleepTimerMinutes,
        setSleepTimerMinutes,
        musicCatalogUpdateAvailable,
        checkMusicCatalogUpdate,
        downloadMusicCatalogUpdate,
        downloadingTrackId,
      }),
    [
      store,
      tracks,
      trackIndex,
      playing,
      loading,
      playbackMode,
      musicCurrentSec,
      musicDurationSec,
      canTogglePlayback,
      scriptureCurrentSec,
      scriptureDurationSec,
      readChapterAudioAvailable,
      scripturePreparing,
      scriptureAudioRepeatMode,
      setScriptureAudioRepeatMode,
      scripturePlaybackRate,
      setScripturePlaybackRate,
      seekRatio,
      shell,
      setMusicGain,
      musicRepeatMode,
      setMusicRepeatMode,
      toggleMusicRepeatOne,
      toggleMusicRepeatAll,
      sleepTimerMinutes,
      setSleepTimerMinutes,
      musicCatalogUpdateAvailable,
      checkMusicCatalogUpdate,
      downloadMusicCatalogUpdate,
      downloadingTrackId,
    ],
  );
}
