import type { BibleTranslationMeta, BibleTranslationsIndex } from "@/lib/bible/translations-types";
import { readTranslationsIndexSync } from "@/lib/bible/translations-store";

export type BibleTranslationProvider = "local" | "youversion" | "api-bible" | "esv";
export type BibleTranslationDelivery = "bundled" | "local-download" | "chapter-api";

type RegistryMeta = BibleTranslationMeta & {
  provider: BibleTranslationProvider;
  remoteId: string;
  delivery: BibleTranslationDelivery;
  enabled: boolean;
};

const REMOTE_TRANSLATION_REGISTRY: RegistryMeta[] = [
  {
    id: "cccbst-zh-hant",
    labelZh: "四福音書 – 共同譯本",
    labelEn: "Four Gospels Interconfessional Version",
    language: "zh-Hant",
    sourceFile: "remote/youversion/cccbst-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "2361",
    delivery: "chapter-api",
    enabled: false,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "ccb-zh-hans",
    labelZh: "当代译本（简体）",
    labelEn: "Contemporary Chinese Bible (Simplified)",
    language: "zh-Hans",
    sourceFile: "remote/youversion/ccb-zh-hans",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "36",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "ccb-zh-hant",
    labelZh: "當代譯本（繁體）",
    labelEn: "Contemporary Chinese Bible (Traditional)",
    language: "zh-Hant",
    sourceFile: "remote/youversion/ccb-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "1392",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "cnv-zh-hant",
    labelZh: "新譯本（繁體）",
    labelEn: "Chinese New Version (Traditional)",
    language: "zh-Hant",
    sourceFile: "remote/youversion/cnv-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "40",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "cnvs-zh-hans",
    labelZh: "新译本（简体）",
    labelEn: "Chinese New Version (Simplified)",
    language: "zh-Hans",
    sourceFile: "remote/youversion/cnvs-zh-hans",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "41",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "csbs-zh-hans",
    labelZh: "中文标准译本（简体）",
    labelEn: "Chinese Standard Bible (Simplified)",
    language: "zh-Hans",
    sourceFile: "remote/youversion/csbs-zh-hans",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "43",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "csbt-zh-hant",
    labelZh: "中文標準譯本（繁體）",
    labelEn: "Chinese Standard Bible (Traditional)",
    language: "zh-Hant",
    sourceFile: "remote/youversion/csbt-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "312",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "rcuv-zh-hant",
    labelZh: "和合本修訂版",
    labelEn: "Revised Chinese Union Version",
    language: "zh-Hant",
    sourceFile: "remote/youversion/rcuv-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "139",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "rcuvss-zh-hans",
    labelZh: "和合本修订版",
    labelEn: "Revised Chinese Union Version (Simplified)",
    language: "zh-Hans",
    sourceFile: "remote/youversion/rcuvss-zh-hans",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "140",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "rcv-zh-hant",
    labelZh: "恢復本（繁體）",
    labelEn: "Recovery Version Traditional Chinese",
    language: "zh-Hant",
    sourceFile: "remote/youversion/rcv-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "4230",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "cunp-zh-hant",
    labelZh: "新標點和合本, 神版",
    labelEn: "Chinese Union Version with New Punctuation, God-Version",
    language: "zh-Hant",
    sourceFile: "remote/youversion/cunp-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "46",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "cunp-zh-hant-god",
    labelZh: "新標點和合本, 上帝版",
    labelEn: "Chinese Union Version with New Punctuation, God-Version",
    language: "zh-Hant",
    sourceFile: "remote/youversion/cunp-zh-hant-god",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "414",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "cunpss-zh-hant",
    labelZh: "新標點和合本, 上帝版",
    labelEn: "Chinese Union Version with New Punctuation, God-Version",
    language: "zh-Hant",
    sourceFile: "remote/youversion/cunpss-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "47",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "cunpss-zh-hans",
    labelZh: "新标点和合本, 神版",
    labelEn: "Chinese Union Version with New Punctuation, God-Version",
    language: "zh-Hans",
    sourceFile: "remote/youversion/cunpss-zh-hans",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "2224",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "feb-zh-hans",
    labelZh: "免费的易读圣经",
    labelEn: "Free Easy-to-Read Bible",
    language: "zh-Hans",
    sourceFile: "remote/youversion/feb-zh-hans",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "3354",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "mandarin-zh-hans",
    labelZh: "普通话本",
    labelEn: "Mandarin Bible",
    language: "zh-Hans",
    sourceFile: "remote/youversion/mandarin-zh-hans",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "3780",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "tcv2019t-zh-hant",
    labelZh: "現代中文譯本2019（繁體版）",
    labelEn: "Today's Chinese Version 2019 (Traditional)",
    language: "zh-Hant",
    sourceFile: "remote/youversion/tcv2019t-zh-hant",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "3283",
    delivery: "chapter-api",
    enabled: false,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "niv",
    labelZh: "NIV 英文新国际版",
    labelEn: "New International Version (NIV)",
    language: "en",
    sourceFile: "remote/youversion/niv",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "youversion",
    remoteId: "111",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "esv",
    labelZh: "ESV 英文标准版",
    labelEn: "English Standard Version (ESV)",
    language: "en",
    sourceFile: "remote/esv/esv",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "esv",
    remoteId: null,
    delivery: "chapter-api",
    enabled: true,
    copyright:
      "Scripture quotations are from the ESV® Bible (The Holy Bible, English Standard Version®), © 2001 Crossway.",
    publisherUrl: "https://www.esv.org",
  },
  {
    id: "nlt",
    labelZh: "NLT 现代英语译本",
    labelEn: "New Living Translation (NLT)",
    language: "en",
    sourceFile: "remote/api-bible/nlt",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "api-bible",
    remoteId: "d6e14a625393b4da-01",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
  {
    id: "nkjv",
    labelZh: "NKJV 新钦定版",
    labelEn: "New King James Version (NKJV)",
    language: "en",
    sourceFile: "remote/api-bible/nkjv",
    updatedAt: new Date(0).toISOString(),
    bytes: 0,
    verseCount: 0,
    provider: "api-bible",
    remoteId: "63097d2a0a2f7db3-01",
    delivery: "chapter-api",
    enabled: true,
    copyright: null,
    publisherUrl: null,
  },
];

function normalizeMeta(meta: BibleTranslationMeta): BibleTranslationMeta {
  return {
    ...meta,
    id: String(meta.id || "").trim(),
    labelZh: String(meta.labelZh || "").trim(),
    labelEn: String(meta.labelEn || "").trim(),
    language: String(meta.language || "").trim(),
    sourceFile: String(meta.sourceFile || "").trim(),
    updatedAt: String(meta.updatedAt || "").trim() || new Date(0).toISOString(),
    bytes: Number.isFinite(meta.bytes) ? meta.bytes : 0,
    verseCount: Number.isFinite(meta.verseCount) ? meta.verseCount : 0,
  };
}

export function readBibleTranslationRegistry(cwd: string): BibleTranslationsIndex {
  const index = readTranslationsIndexSync(cwd);
  const local = index.translations.map(normalizeMeta);
  const seen = new Set(local.map((item) => item.id));
  const merged = [...local];
  for (const meta of REMOTE_TRANSLATION_REGISTRY) {
    if (meta.enabled === false) continue;
    if (seen.has(meta.id)) continue;
    merged.push({ ...meta });
  }
  merged.sort((a, b) => a.id.localeCompare(b.id));
  return {
    translations: merged,
    defaultTranslationId:
      index.defaultTranslationId && merged.some((item) => item.id === index.defaultTranslationId)
        ? index.defaultTranslationId
        : merged[0]?.id ?? null,
  };
}

export function resolveBibleTranslationMeta(cwd: string, translationId: string): BibleTranslationMeta | null {
  const id = String(translationId || "").trim();
  if (!id) return null;
  const index = readBibleTranslationRegistry(cwd);
  return index.translations.find((meta) => meta.id === id) ?? null;
}

export function isRemoteBibleTranslationMeta(
  meta: BibleTranslationMeta | null | undefined,
): meta is RegistryMeta {
  return Boolean(meta && meta.provider && meta.provider !== "local" && meta.enabled !== false);
}
